sudo apt-get install -y --force-yes acl
sudo apt-get install -y --force-yes acpi
sudo apt-get install -y --force-yes acpi-support-base
sudo apt-get install -y --force-yes acpid
sudo apt-get install -y --force-yes adduser
sudo apt-get install -y --force-yes apache2
sudo apt-get install -y --force-yes apache2-mpm-prefork
sudo apt-get install -y --force-yes apache2-utils
sudo apt-get install -y --force-yes apache2.2-bin
sudo apt-get install -y --force-yes apache2.2-common
sudo apt-get install -y --force-yes apt
sudo apt-get install -y --force-yes apt-listchanges
sudo apt-get install -y --force-yes apt-show-versions
sudo apt-get install -y --force-yes apt-utils
sudo apt-get install -y --force-yes aptitude
sudo apt-get install -y --force-yes aptitude-common
sudo apt-get install -y --force-yes at
sudo apt-get install -y --force-yes at-spi2-core
sudo apt-get install -y --force-yes autoconf
sudo apt-get install -y --force-yes automake
sudo apt-get install -y --force-yes autopoint
sudo apt-get install -y --force-yes autotools-dev
sudo apt-get install -y --force-yes base-files
sudo apt-get install -y --force-yes base-passwd
sudo apt-get install -y --force-yes bash
sudo apt-get install -y --force-yes bash-completion
sudo apt-get install -y --force-yes bc
sudo apt-get install -y --force-yes bind9-host
sudo apt-get install -y --force-yes binutils
sudo apt-get install -y --force-yes bsd-mailx
sudo apt-get install -y --force-yes bsdmainutils
sudo apt-get install -y --force-yes bsdutils
sudo apt-get install -y --force-yes build-essential
sudo apt-get install -y --force-yes busybox
sudo apt-get install -y --force-yes bzip2
sudo apt-get install -y --force-yes ca-certificates
sudo apt-get install -y --force-yes colord
sudo apt-get install -y --force-yes console-setup
sudo apt-get install -y --force-yes console-setup-linux
sudo apt-get install -y --force-yes consolekit
sudo apt-get install -y --force-yes coreutils
sudo apt-get install -y --force-yes cpio
sudo apt-get install -y --force-yes cpp
sudo apt-get install -y --force-yes cpp-4.7
sudo apt-get install -y --force-yes cron
sudo apt-get install -y --force-yes curl
sudo apt-get install -y --force-yes dash
sudo apt-get install -y --force-yes db5.1-util
sudo apt-get install -y --force-yes dbconfig-common
sudo apt-get install -y --force-yes dbus
sudo apt-get install -y --force-yes dc
sudo apt-get install -y --force-yes dconf-gsettings-backend
sudo apt-get install -y --force-yes dconf-service
sudo apt-get install -y --force-yes debconf
sudo apt-get install -y --force-yes debconf-i18n
sudo apt-get install -y --force-yes debhelper
sudo apt-get install -y --force-yes debian-archive-keyring
sudo apt-get install -y --force-yes debian-faq
sudo apt-get install -y --force-yes debianutils
sudo apt-get install -y --force-yes diffutils
sudo apt-get install -y --force-yes discover
sudo apt-get install -y --force-yes discover-data
sudo apt-get install -y --force-yes dmidecode
sudo apt-get install -y --force-yes dmsetup
sudo apt-get install -y --force-yes dnsutils
sudo apt-get install -y --force-yes doc-debian
sudo apt-get install -y --force-yes dpkg
sudo apt-get install -y --force-yes dpkg-dev
sudo apt-get install -y --force-yes dpkg-repack
sudo apt-get install -y --force-yes e2fslibs
sudo apt-get install -y --force-yes e2fsprogs
sudo apt-get install -y --force-yes eject
sudo apt-get install -y --force-yes exim4
sudo apt-get install -y --force-yes exim4-base
sudo apt-get install -y --force-yes exim4-config
sudo apt-get install -y --force-yes exim4-daemon-light
sudo apt-get install -y --force-yes fakeroot
sudo apt-get install -y --force-yes file
sudo apt-get install -y --force-yes findutils
sudo apt-get install -y --force-yes fontconfig
sudo apt-get install -y --force-yes fontconfig-config
sudo apt-get install -y --force-yes fonts-droid
sudo apt-get install -y --force-yes fonts-liberation
sudo apt-get install -y --force-yes ftp
sudo apt-get install -y --force-yes g++
sudo apt-get install -y --force-yes g++-4.7
sudo apt-get install -y --force-yes gcc
sudo apt-get install -y --force-yes gcc-4.7
sudo apt-get install -y --force-yes gcc-4.7-base
sudo apt-get install -y --force-yes geoip-database
sudo apt-get install -y --force-yes gettext
sudo apt-get install -y --force-yes gettext-base
sudo apt-get install -y --force-yes ghostscript
sudo apt-get install -y --force-yes gir1.2-atk-1.0
sudo apt-get install -y --force-yes gir1.2-atspi-2.0
sudo apt-get install -y --force-yes gir1.2-freedesktop
sudo apt-get install -y --force-yes gir1.2-gdkpixbuf-2.0
sudo apt-get install -y --force-yes gir1.2-glib-2.0
sudo apt-get install -y --force-yes gir1.2-gtk-3.0
sudo apt-get install -y --force-yes gir1.2-pango-1.0
sudo apt-get install -y --force-yes gir1.2-wnck-3.0
sudo apt-get install -y --force-yes git
sudo apt-get install -y --force-yes git-man
sudo apt-get install -y --force-yes gnupg
sudo apt-get install -y --force-yes gnuplot
sudo apt-get install -y --force-yes gnuplot-nox
sudo apt-get install -y --force-yes gpgv
sudo apt-get install -y --force-yes grep
sudo apt-get install -y --force-yes groff
sudo apt-get install -y --force-yes groff-base
sudo apt-get install -y --force-yes grub-common
sudo apt-get install -y --force-yes grub-pc
sudo apt-get install -y --force-yes grub-pc-bin
sudo apt-get install -y --force-yes grub2-common
sudo apt-get install -y --force-yes gsfonts
sudo apt-get install -y --force-yes gzip
sudo apt-get install -y --force-yes hicolor-icon-theme
sudo apt-get install -y --force-yes host
sudo apt-get install -y --force-yes hostname
sudo apt-get install -y --force-yes html2text
sudo apt-get install -y --force-yes htop
sudo apt-get install -y --force-yes iftop
sudo apt-get install -y --force-yes ifupdown
sudo apt-get install -y --force-yes imagemagick
sudo apt-get install -y --force-yes imagemagick-common
sudo apt-get install -y --force-yes info
sudo apt-get install -y --force-yes initramfs-tools
sudo apt-get install -y --force-yes initscripts
sudo apt-get install -y --force-yes insserv
sudo apt-get install -y --force-yes install-info
sudo apt-get install -y --force-yes installation-report
sudo apt-get install -y --force-yes intltool-debian
sudo apt-get install -y --force-yes iproute
sudo apt-get install -y --force-yes iptables
sudo apt-get install -y --force-yes iputils-ping
sudo apt-get install -y --force-yes isc-dhcp-client
sudo apt-get install -y --force-yes isc-dhcp-common
sudo apt-get install -y --force-yes iso-codes
sudo apt-get install -y --force-yes javascript-common
sudo apt-get install -y --force-yes kbd
sudo apt-get install -y --force-yes keyboard-configuration
sudo apt-get install -y --force-yes klibc-utils
sudo apt-get install -y --force-yes kmod
sudo apt-get install -y --force-yes krb5-locales
sudo apt-get install -y --force-yes laptop-detect
sudo apt-get install -y --force-yes ldtp
sudo apt-get install -y --force-yes less
sudo apt-get install -y --force-yes libacl1
sudo apt-get install -y --force-yes libaio1
sudo apt-get install -y --force-yes libalgorithm-diff-perl
sudo apt-get install -y --force-yes libalgorithm-diff-xs-perl
sudo apt-get install -y --force-yes libalgorithm-merge-perl
sudo apt-get install -y --force-yes libapache2-mod-evasive
sudo apt-get install -y --force-yes libapache2-mod-php5
sudo apt-get install -y --force-yes libapache2-modsecurity
sudo apt-get install -y --force-yes libapr1
sudo apt-get install -y --force-yes libaprutil1
sudo apt-get install -y --force-yes libaprutil1-dbd-sqlite3
sudo apt-get install -y --force-yes libaprutil1-ldap
sudo apt-get install -y --force-yes libapt-inst1.5
sudo apt-get install -y --force-yes libapt-pkg-perl
sudo apt-get install -y --force-yes libapt-pkg4.12
sudo apt-get install -y --force-yes libasprintf0c2
sudo apt-get install -y --force-yes libatk-adaptor
sudo apt-get install -y --force-yes libatk-adaptor-data
sudo apt-get install -y --force-yes libatk-bridge2.0-0
sudo apt-get install -y --force-yes libatk1.0-0
sudo apt-get install -y --force-yes libatk1.0-data
sudo apt-get install -y --force-yes libatspi2.0-0
sudo apt-get install -y --force-yes libattr1
sudo apt-get install -y --force-yes libauthen-pam-perl
sudo apt-get install -y --force-yes libavahi-client3
sudo apt-get install -y --force-yes libavahi-common-data
sudo apt-get install -y --force-yes libavahi-common3
sudo apt-get install -y --force-yes libbind9-80
sudo apt-get install -y --force-yes libblas3
sudo apt-get install -y --force-yes libblas3gf
sudo apt-get install -y --force-yes libblkid1
sudo apt-get install -y --force-yes libboost-iostreams1.49.0
sudo apt-get install -y --force-yes libbsd0
sudo apt-get install -y --force-yes libbz2-1.0
sudo apt-get install -y --force-yes libc-bin
sudo apt-get install -y --force-yes libc-client2007e
sudo apt-get install -y --force-yes libc-dev-bin
sudo apt-get install -y --force-yes libc6
sudo apt-get install -y --force-yes libc6-dev
sudo apt-get install -y --force-yes libcairo-gobject2
sudo apt-get install -y --force-yes libcairo2
sudo apt-get install -y --force-yes libcap2
sudo apt-get install -y --force-yes libck-connector0
sudo apt-get install -y --force-yes libclass-isa-perl
sudo apt-get install -y --force-yes libcln-dev
sudo apt-get install -y --force-yes libcln6
sudo apt-get install -y --force-yes libcolord1
sudo apt-get install -y --force-yes libcomerr2
sudo apt-get install -y --force-yes libcroco3
sudo apt-get install -y --force-yes libcups2
sudo apt-get install -y --force-yes libcupsimage2
sudo apt-get install -y --force-yes libcurl3
sudo apt-get install -y --force-yes libcurl3-gnutls
sudo apt-get install -y --force-yes libcwidget3
sudo apt-get install -y --force-yes libdatrie1
sudo apt-get install -y --force-yes libdb5.1
sudo apt-get install -y --force-yes libdbd-mysql-perl
sudo apt-get install -y --force-yes libdbi-perl
sudo apt-get install -y --force-yes libdbus-1-3
sudo apt-get install -y --force-yes libdbus-glib-1-2
sudo apt-get install -y --force-yes libdconf0
sudo apt-get install -y --force-yes libdevmapper1.02.1
sudo apt-get install -y --force-yes libdiscover2
sudo apt-get install -y --force-yes libdjvulibre-text
sudo apt-get install -y --force-yes libdjvulibre21
sudo apt-get install -y --force-yes libdns88
sudo apt-get install -y --force-yes libdpkg-perl
sudo apt-get install -y --force-yes libedit2
sudo apt-get install -y --force-yes libept1.4.12
sudo apt-get install -y --force-yes liberror-perl
sudo apt-get install -y --force-yes libevent-2.0-5
sudo apt-get install -y --force-yes libexif12
sudo apt-get install -y --force-yes libexiv2-12
sudo apt-get install -y --force-yes libexpat1
sudo apt-get install -y --force-yes libffi5
sudo apt-get install -y --force-yes libfile-copy-recursive-perl
sudo apt-get install -y --force-yes libfile-fcntllock-perl
sudo apt-get install -y --force-yes libfontconfig1
sudo apt-get install -y --force-yes libfreetype6
sudo apt-get install -y --force-yes libfuse2
sudo apt-get install -y --force-yes libgail-common
sudo apt-get install -y --force-yes libgail18
sudo apt-get install -y --force-yes libgc1c2
sudo apt-get install -y --force-yes libgcc1
sudo apt-get install -y --force-yes libgcrypt11
sudo apt-get install -y --force-yes libgd2-xpm
sudo apt-get install -y --force-yes libgdbm3
sudo apt-get install -y --force-yes libgdk-pixbuf2.0-0
sudo apt-get install -y --force-yes libgdk-pixbuf2.0-common
sudo apt-get install -y --force-yes libgeoip1
sudo apt-get install -y --force-yes libgettextpo0
sudo apt-get install -y --force-yes libgfortran3
sudo apt-get install -y --force-yes libgirepository-1.0-1
sudo apt-get install -y --force-yes libglib2.0-0
sudo apt-get install -y --force-yes libglib2.0-data
sudo apt-get install -y --force-yes libgmp-dev
sudo apt-get install -y --force-yes libgmp10
sudo apt-get install -y --force-yes libgmpxx4ldbl
sudo apt-get install -y --force-yes libgnutls26
sudo apt-get install -y --force-yes libgomp1
sudo apt-get install -y --force-yes libgpg-error0
sudo apt-get install -y --force-yes libgpgme11
sudo apt-get install -y --force-yes libgphoto2-2
sudo apt-get install -y --force-yes libgphoto2-l10n
sudo apt-get install -y --force-yes libgphoto2-port0
sudo apt-get install -y --force-yes libgpm2
sudo apt-get install -y --force-yes libgs9
sudo apt-get install -y --force-yes libgs9-common
sudo apt-get install -y --force-yes libgssapi-krb5-2
sudo apt-get install -y --force-yes libgssglue1
sudo apt-get install -y --force-yes libgtk-3-0
sudo apt-get install -y --force-yes libgtk-3-bin
sudo apt-get install -y --force-yes libgtk-3-common
sudo apt-get install -y --force-yes libgtk2.0-0
sudo apt-get install -y --force-yes libgtk2.0-bin
sudo apt-get install -y --force-yes libgtk2.0-common
sudo apt-get install -y --force-yes libgudev-1.0-0
sudo apt-get install -y --force-yes libgusb2
sudo apt-get install -y --force-yes libhtml-template-perl
sudo apt-get install -y --force-yes libice6
sudo apt-get install -y --force-yes libidn11
sudo apt-get install -y --force-yes libieee1284-3
sudo apt-get install -y --force-yes libijs-0.35
sudo apt-get install -y --force-yes libilmbase6
sudo apt-get install -y --force-yes libio-pty-perl
sudo apt-get install -y --force-yes libisc84
sudo apt-get install -y --force-yes libisccc80
sudo apt-get install -y --force-yes libisccfg82
sudo apt-get install -y --force-yes libitm1
sudo apt-get install -y --force-yes libjasper1
sudo apt-get install -y --force-yes libjbig0
sudo apt-get install -y --force-yes libjbig2dec0
sudo apt-get install -y --force-yes libjpeg8
sudo apt-get install -y --force-yes libjs-jquery
sudo apt-get install -y --force-yes libjs-yui
sudo apt-get install -y --force-yes libk5crypto3
sudo apt-get install -y --force-yes libkeyutils1
sudo apt-get install -y --force-yes libklibc
sudo apt-get install -y --force-yes libkmod2
sudo apt-get install -y --force-yes libkrb5-3
sudo apt-get install -y --force-yes libkrb5support0
sudo apt-get install -y --force-yes liblcms1
sudo apt-get install -y --force-yes liblcms2-2
sudo apt-get install -y --force-yes libldap-2.4-2
sudo apt-get install -y --force-yes liblensfun-data
sudo apt-get install -y --force-yes liblensfun0
sudo apt-get install -y --force-yes liblinear-tools
sudo apt-get install -y --force-yes liblinear1
sudo apt-get install -y --force-yes liblocale-gettext-perl
sudo apt-get install -y --force-yes liblockfile-bin
sudo apt-get install -y --force-yes liblockfile1
sudo apt-get install -y --force-yes liblqr-1-0
sudo apt-get install -y --force-yes libltdl-dev
sudo apt-get install -y --force-yes libltdl7
sudo apt-get install -y --force-yes liblua5.1-0
sudo apt-get install -y --force-yes liblwres80
sudo apt-get install -y --force-yes liblzma5
sudo apt-get install -y --force-yes libmagic1
sudo apt-get install -y --force-yes libmagickcore5
sudo apt-get install -y --force-yes libmagickcore5-extra
sudo apt-get install -y --force-yes libmagickwand5
sudo apt-get install -y --force-yes libmail-sendmail-perl
sudo apt-get install -y --force-yes libmcrypt4
sudo apt-get install -y --force-yes libmhash2
sudo apt-get install -y --force-yes libmount1
sudo apt-get install -y --force-yes libmpc2
sudo apt-get install -y --force-yes libmpfr4
sudo apt-get install -y --force-yes libmysqlclient18
sudo apt-get install -y --force-yes libncurses5
sudo apt-get install -y --force-yes libncursesw5
sudo apt-get install -y --force-yes libnet-ssleay-perl
sudo apt-get install -y --force-yes libnetpbm10
sudo apt-get install -y --force-yes libnewt0.52
sudo apt-get install -y --force-yes libnfnetlink0
sudo apt-get install -y --force-yes libnfsidmap2
sudo apt-get install -y --force-yes libonig2
sudo apt-get install -y --force-yes libopenexr6
sudo apt-get install -y --force-yes libopts25
sudo apt-get install -y --force-yes libp11-kit0
sudo apt-get install -y --force-yes libpam-ck-connector
sudo apt-get install -y --force-yes libpam-modules
sudo apt-get install -y --force-yes libpam-modules-bin
sudo apt-get install -y --force-yes libpam-runtime
sudo apt-get install -y --force-yes libpam0g
sudo apt-get install -y --force-yes libpango1.0-0
sudo apt-get install -y --force-yes libpaper-utils
sudo apt-get install -y --force-yes libpaper1
sudo apt-get install -y --force-yes libpcap0.8
sudo apt-get install -y --force-yes libpci3
sudo apt-get install -y --force-yes libpcre3
sudo apt-get install -y --force-yes libperl5.14
sudo apt-get install -y --force-yes libpipeline1
sudo apt-get install -y --force-yes libpixman-1-0
sudo apt-get install -y --force-yes libpng12-0
sudo apt-get install -y --force-yes libpolkit-agent-1-0
sudo apt-get install -y --force-yes libpolkit-backend-1-0
sudo apt-get install -y --force-yes libpolkit-gobject-1-0
sudo apt-get install -y --force-yes libpopt0
sudo apt-get install -y --force-yes libpq5
sudo apt-get install -y --force-yes libprocps0
sudo apt-get install -y --force-yes libpth20
sudo apt-get install -y --force-yes libqdbm14
sudo apt-get install -y --force-yes libquadmath0
sudo apt-get install -y --force-yes libreadline6
sudo apt-get install -y --force-yes librsvg2-2
sudo apt-get install -y --force-yes librsvg2-common
sudo apt-get install -y --force-yes librtmp0
sudo apt-get install -y --force-yes libsane
sudo apt-get install -y --force-yes libsane-common
sudo apt-get install -y --force-yes libsane-extras
sudo apt-get install -y --force-yes libsane-extras-common
sudo apt-get install -y --force-yes libsasl2-2
sudo apt-get install -y --force-yes libsasl2-modules
sudo apt-get install -y --force-yes libselinux1
sudo apt-get install -y --force-yes libsemanage-common
sudo apt-get install -y --force-yes libsemanage1
sudo apt-get install -y --force-yes libsensors4
sudo apt-get install -y --force-yes libsepol1
sudo apt-get install -y --force-yes libsigc++-2.0-0c2a
sudo apt-get install -y --force-yes libslang2
sudo apt-get install -y --force-yes libsm6
sudo apt-get install -y --force-yes libsnmp-base
sudo apt-get install -y --force-yes libsnmp15
sudo apt-get install -y --force-yes libsqlite3-0
sudo apt-get install -y --force-yes libss2
sudo apt-get install -y --force-yes libssh2-1
sudo apt-get install -y --force-yes libssl-dev
sudo apt-get install -y --force-yes libssl-doc
sudo apt-get install -y --force-yes libssl1.0.0
sudo apt-get install -y --force-yes libstartup-notification0
sudo apt-get install -y --force-yes libstdc++6
sudo apt-get install -y --force-yes libstdc++6-4.7-dev
sudo apt-get install -y --force-yes libsvm-tools
sudo apt-get install -y --force-yes libswitch-perl
sudo apt-get install -y --force-yes libsys-hostname-long-perl
sudo apt-get install -y --force-yes libsystemd-login0
sudo apt-get install -y --force-yes libt1-5
sudo apt-get install -y --force-yes libtasn1-3
sudo apt-get install -y --force-yes libtext-charwidth-perl
sudo apt-get install -y --force-yes libtext-iconv-perl
sudo apt-get install -y --force-yes libtext-wrapi18n-perl
sudo apt-get install -y --force-yes libthai-data
sudo apt-get install -y --force-yes libthai0
sudo apt-get install -y --force-yes libtiff4
sudo apt-get install -y --force-yes libtimedate-perl
sudo apt-get install -y --force-yes libtinfo5
sudo apt-get install -y --force-yes libtirpc1
sudo apt-get install -y --force-yes libtokyocabinet9
sudo apt-get install -y --force-yes libtool
sudo apt-get install -y --force-yes libudev0
sudo apt-get install -y --force-yes libunistring0
sudo apt-get install -y --force-yes libusb-0.1-4
sudo apt-get install -y --force-yes libusb-1.0-0
sudo apt-get install -y --force-yes libustr-1.0-1
sudo apt-get install -y --force-yes libuuid-perl
sudo apt-get install -y --force-yes libuuid1
sudo apt-get install -y --force-yes libv4l-0
sudo apt-get install -y --force-yes libv4lconvert0
sudo apt-get install -y --force-yes libvpx1
sudo apt-get install -y --force-yes libwmf0.2-7
sudo apt-get install -y --force-yes libwnck-3-0
sudo apt-get install -y --force-yes libwnck-3-common
sudo apt-get install -y --force-yes libwrap0
sudo apt-get install -y --force-yes libx11-6
sudo apt-get install -y --force-yes libx11-data
sudo apt-get install -y --force-yes libx11-xcb1
sudo apt-get install -y --force-yes libxapian22
sudo apt-get install -y --force-yes libxau6
sudo apt-get install -y --force-yes libxaw7
sudo apt-get install -y --force-yes libxcb-render0
sudo apt-get install -y --force-yes libxcb-shm0
sudo apt-get install -y --force-yes libxcb-util0
sudo apt-get install -y --force-yes libxcb1
sudo apt-get install -y --force-yes libxcomposite1
sudo apt-get install -y --force-yes libxcursor1
sudo apt-get install -y --force-yes libxdamage1
sudo apt-get install -y --force-yes libxdmcp6
sudo apt-get install -y --force-yes libxext6
sudo apt-get install -y --force-yes libxfixes3
sudo apt-get install -y --force-yes libxft2
sudo apt-get install -y --force-yes libxi6
sudo apt-get install -y --force-yes libxinerama1
sudo apt-get install -y --force-yes libxml2
sudo apt-get install -y --force-yes libxmu6
sudo apt-get install -y --force-yes libxmuu1
sudo apt-get install -y --force-yes libxpm4
sudo apt-get install -y --force-yes libxrandr2
sudo apt-get install -y --force-yes libxrender1
sudo apt-get install -y --force-yes libxres1
sudo apt-get install -y --force-yes libxslt1.1
sudo apt-get install -y --force-yes libxt6
sudo apt-get install -y --force-yes libxtst6
sudo apt-get install -y --force-yes linux-base
sudo apt-get install -y --force-yes linux-image-3.2.0-4-amd64
sudo apt-get install -y --force-yes linux-image-amd64
sudo apt-get install -y --force-yes linux-libc-dev
sudo apt-get install -y --force-yes locales
sudo apt-get install -y --force-yes lockfile-progs
sudo apt-get install -y --force-yes login
sudo apt-get install -y --force-yes logrotate
sudo apt-get install -y --force-yes lsb-base
sudo apt-get install -y --force-yes lsb-release
sudo apt-get install -y --force-yes lsof
sudo apt-get install -y --force-yes m4
sudo apt-get install -y --force-yes make
sudo apt-get install -y --force-yes man-db
sudo apt-get install -y --force-yes manpages
sudo apt-get install -y --force-yes manpages-dev
sudo apt-get install -y --force-yes mawk
sudo apt-get install -y --force-yes mcrypt
sudo apt-get install -y --force-yes mime-support
sudo apt-get install -y --force-yes mlocate
sudo apt-get install -y --force-yes mlock
sudo apt-get install -y --force-yes modsecurity-crs
sudo apt-get install -y --force-yes module-init-tools
sudo apt-get install -y --force-yes mount
sudo apt-get install -y --force-yes multiarch-support
sudo apt-get install -y --force-yes mutt
sudo apt-get install -y --force-yes mysql-client-5.5
sudo apt-get install -y --force-yes mysql-common
sudo apt-get install -y --force-yes mysql-server
sudo apt-get install -y --force-yes mysql-server-5.5
sudo apt-get install -y --force-yes mysql-server-core-5.5
sudo apt-get install -y --force-yes nano
sudo apt-get install -y --force-yes ncurses-base
sudo apt-get install -y --force-yes ncurses-bin
sudo apt-get install -y --force-yes ncurses-term
sudo apt-get install -y --force-yes net-tools
sudo apt-get install -y --force-yes netbase
sudo apt-get install -y --force-yes netcat-traditional
sudo apt-get install -y --force-yes netpbm
sudo apt-get install -y --force-yes nfs-common
sudo apt-get install -y --force-yes nmap
sudo apt-get install -y --force-yes ntp
sudo apt-get install -y --force-yes ntpdate
sudo apt-get install -y --force-yes openssh-blacklist
sudo apt-get install -y --force-yes openssh-blacklist-extra
sudo apt-get install -y --force-yes openssh-client
sudo apt-get install -y --force-yes openssh-server
sudo apt-get install -y --force-yes openssl
sudo apt-get install -y --force-yes os-prober
sudo apt-get install -y --force-yes passwd
sudo apt-get install -y --force-yes patch
sudo apt-get install -y --force-yes pciutils
sudo apt-get install -y --force-yes pear-phpunit-channel
sudo apt-get install -y --force-yes pear-symfony-project-channel
sudo apt-get install -y --force-yes perl
sudo apt-get install -y --force-yes perl-base
sudo apt-get install -y --force-yes perl-modules
sudo apt-get install -y --force-yes php-codecoverage
sudo apt-get install -y --force-yes php-db
sudo apt-get install -y --force-yes php-file-iterator
sudo apt-get install -y --force-yes php-invoker
sudo apt-get install -y --force-yes php-pear
sudo apt-get install -y --force-yes php-symfony-yaml
sudo apt-get install -y --force-yes php-text-template
sudo apt-get install -y --force-yes php-timer
sudo apt-get install -y --force-yes php-token-stream
sudo apt-get install -y --force-yes php5
sudo apt-get install -y --force-yes php5-cli
sudo apt-get install -y --force-yes php5-common
sudo apt-get install -y --force-yes php5-curl
sudo apt-get install -y --force-yes php5-dev
sudo apt-get install -y --force-yes php5-gd
sudo apt-get install -y --force-yes php5-imagick
sudo apt-get install -y --force-yes php5-imap
sudo apt-get install -y --force-yes php5-mcrypt
sudo apt-get install -y --force-yes php5-memcache
sudo apt-get install -y --force-yes php5-mysqlnd
sudo apt-get install -y --force-yes php5-pgsql
sudo apt-get install -y --force-yes php5-readline
sudo apt-get install -y --force-yes php5-snmp
sudo apt-get install -y --force-yes php5-sqlite
sudo apt-get install -y --force-yes php5-xdebug
sudo apt-get install -y --force-yes php5-xsl
sudo apt-get install -y --force-yes phpmyadmin
sudo apt-get install -y --force-yes phpunit
sudo apt-get install -y --force-yes phpunit-mock-object
sudo apt-get install -y --force-yes phpunit-story
sudo apt-get install -y --force-yes pkg-php-tools
sudo apt-get install -y --force-yes po-debconf
sudo apt-get install -y --force-yes policykit-1
sudo apt-get install -y --force-yes poppler-data
sudo apt-get install -y --force-yes procmail
sudo apt-get install -y --force-yes procps
sudo apt-get install -y --force-yes psmisc
sudo apt-get install -y --force-yes psutils
sudo apt-get install -y --force-yes python
sudo apt-get install -y --force-yes python-apt
sudo apt-get install -y --force-yes python-apt-common
sudo apt-get install -y --force-yes python-chardet
sudo apt-get install -y --force-yes python-debian
sudo apt-get install -y --force-yes python-debianbts
sudo apt-get install -y --force-yes python-fpconst
sudo apt-get install -y --force-yes python-gi
sudo apt-get install -y --force-yes python-gobject
sudo apt-get install -y --force-yes python-gobject-2
sudo apt-get install -y --force-yes python-minimal
sudo apt-get install -y --force-yes python-openssl
sudo apt-get install -y --force-yes python-pam
sudo apt-get install -y --force-yes python-pkg-resources
sudo apt-get install -y --force-yes python-pyatspi
sudo apt-get install -y --force-yes python-pyatspi2
sudo apt-get install -y --force-yes python-reportbug
sudo apt-get install -y --force-yes python-serial
sudo apt-get install -y --force-yes python-soappy
sudo apt-get install -y --force-yes python-support
sudo apt-get install -y --force-yes python-twisted-bin
sudo apt-get install -y --force-yes python-twisted-core
sudo apt-get install -y --force-yes python-twisted-web
sudo apt-get install -y --force-yes python-zope.interface
sudo apt-get install -y --force-yes python2.6
sudo apt-get install -y --force-yes python2.6-minimal
sudo apt-get install -y --force-yes python2.7
sudo apt-get install -y --force-yes python2.7-minimal
sudo apt-get install -y --force-yes rcconf
sudo apt-get install -y --force-yes readline-common
sudo apt-get install -y --force-yes reportbug
sudo apt-get install -y --force-yes rpcbind
sudo apt-get install -y --force-yes rsync
sudo apt-get install -y --force-yes rsyslog
sudo apt-get install -y --force-yes sane-utils
sudo apt-get install -y --force-yes sed
sudo apt-get install -y --force-yes sensible-utils
sudo apt-get install -y --force-yes sgml-base
sudo apt-get install -y --force-yes shared-mime-info
sudo apt-get install -y --force-yes shtool
sudo apt-get install -y --force-yes sqlite3
sudo apt-get install -y --force-yes ssl-cert
sudo apt-get install -y --force-yes sudo
sudo apt-get install -y --force-yes sysv-rc
sudo apt-get install -y --force-yes sysvinit
sudo apt-get install -y --force-yes sysvinit-utils
sudo apt-get install -y --force-yes tar
sudo apt-get install -y --force-yes tasksel
sudo apt-get install -y --force-yes tasksel-data
sudo apt-get install -y --force-yes tcpd
sudo apt-get install -y --force-yes tcptrack
sudo apt-get install -y --force-yes telnet
sudo apt-get install -y --force-yes texinfo
sudo apt-get install -y --force-yes time
sudo apt-get install -y --force-yes traceroute
sudo apt-get install -y --force-yes ttf-dejavu-core
sudo apt-get install -y --force-yes tzdata
sudo apt-get install -y --force-yes ucf
sudo apt-get install -y --force-yes udev
sudo apt-get install -y --force-yes ufraw-batch
sudo apt-get install -y --force-yes update-inetd
sudo apt-get install -y --force-yes util-linux
sudo apt-get install -y --force-yes vim
sudo apt-get install -y --force-yes vim-common
sudo apt-get install -y --force-yes vim-runtime
sudo apt-get install -y --force-yes vim-tiny
sudo apt-get install -y --force-yes w3m
sudo apt-get install -y --force-yes wamerican
sudo apt-get install -y --force-yes webmin
sudo apt-get install -y --force-yes wget
sudo apt-get install -y --force-yes whiptail
sudo apt-get install -y --force-yes whois
sudo apt-get install -y --force-yes wwwconfig-common
sudo apt-get install -y --force-yes x11-common
sudo apt-get install -y --force-yes xauth
sudo apt-get install -y --force-yes xkb-data
sudo apt-get install -y --force-yes xml-core
sudo apt-get install -y --force-yes xz-utils
sudo apt-get install -y --force-yes zlib1g
sudo apt-get install -y --force-yes zlib1g-dev
