sudo apt-get install abiword-common
sudo apt-get install accountsservice
sudo apt-get install acl
sudo apt-get install acpi-support
sudo apt-get install acpid
sudo apt-get install adduser
sudo apt-get install adobereader-enu
sudo apt-get install agave
sudo apt-get install alien
sudo apt-get install alsa-base
sudo apt-get install alsa-utils
sudo apt-get install anacron
sudo apt-get install app-install-data
sudo apt-get install app-install-data-partner
sudo apt-get install apparmor
sudo apt-get install apport
sudo apt-get install apport-gtk
sudo apt-get install apport-symptoms
sudo apt-get install apt
sudo apt-get install apt-offline
sudo apt-get install apt-transport-https
sudo apt-get install apt-utils
sudo apt-get install apt-xapian-index
sudo apt-get install aptdaemon
sudo apt-get install aptdaemon-data
sudo apt-get install aspell
sudo apt-get install aspell-en
sudo apt-get install aspell-pt
sudo apt-get install aspell-pt-br
sudo apt-get install aspell-pt-pt
sudo apt-get install at-spi2-core
sudo apt-get install attr
sudo apt-get install audacious
sudo apt-get install audacious-plugins:amd64
sudo apt-get install audacious-plugins-data
sudo apt-get install autoconf
sudo apt-get install automake
sudo apt-get install autotools-dev
sudo apt-get install avahi-autoipd
sudo apt-get install avahi-daemon
sudo apt-get install avahi-utils
sudo apt-get install baobab
sudo apt-get install base-files
sudo apt-get install base-passwd
sudo apt-get install bash
sudo apt-get install bash-completion
sudo apt-get install bc
sudo apt-get install bcmwl-kernel-source
sudo apt-get install bind9-host
sudo apt-get install binfmt-support
sudo apt-get install binutils
sudo apt-get install blueman
sudo apt-get install bluez
sudo apt-get install bluez-alsa:amd64
sudo apt-get install bluez-cups
sudo apt-get install brasero
sudo apt-get install brasero-cdrkit
sudo apt-get install brasero-common
sudo apt-get install brltty
sudo apt-get install brltty-x11
sudo apt-get install bsdmainutils
sudo apt-get install bsdutils
sudo apt-get install build-essential
sudo apt-get install bum
sudo apt-get install busybox-initramfs
sudo apt-get install busybox-static
sudo apt-get install bzip2
sudo apt-get install ca-certificates
sudo apt-get install cabextract
sudo apt-get install catfish
sudo apt-get install cheese
sudo apt-get install cheese-common
sudo apt-get install chromium-browser
sudo apt-get install chromium-browser-l10n
sudo apt-get install chromium-codecs-ffmpeg-extra
sudo apt-get install colord
sudo apt-get install command-not-found
sudo apt-get install command-not-found-data
sudo apt-get install compiz-core
sudo apt-get install compiz-plugins-default
sudo apt-get install console-setup
sudo apt-get install coreutils
sudo apt-get install cpio
sudo apt-get install cpp
sudo apt-get install cpp-4.8
sudo apt-get install cracklib-runtime
sudo apt-get install crda
sudo apt-get install cron
sudo apt-get install cups
sudo apt-get install cups-browsed
sudo apt-get install cups-bsd
sudo apt-get install cups-client
sudo apt-get install cups-common
sudo apt-get install cups-core-drivers
sudo apt-get install cups-daemon
sudo apt-get install cups-filters
sudo apt-get install cups-filters-core-drivers
sudo apt-get install cups-ppdc
sudo apt-get install cups-server-common
sudo apt-get install curl
sudo apt-get install dash
sudo apt-get install dbus
sudo apt-get install dbus-x11
sudo apt-get install dc
sudo apt-get install dconf-gsettings-backend:amd64
sudo apt-get install dconf-service
sudo apt-get install debconf
sudo apt-get install debconf-i18n
sudo apt-get install debhelper
sudo apt-get install debianutils
sudo apt-get install debugedit
sudo apt-get install desktop-base
sudo apt-get install desktop-file-utils
sudo apt-get install dh-apparmor
sudo apt-get install dh-modaliases
sudo apt-get install dh-php5
sudo apt-get install dh-python
sudo apt-get install dialog
sudo apt-get install dictionaries-common
sudo apt-get install diffstat
sudo apt-get install diffutils
sudo apt-get install dkms
sudo apt-get install dmidecode
sudo apt-get install dmsetup
sudo apt-get install dmz-cursor-theme
sudo apt-get install dnsmasq-base
sudo apt-get install dnsutils
sudo apt-get install doc-base
sudo apt-get install docbook-xml
sudo apt-get install dosfstools
sudo apt-get install dpkg
sudo apt-get install dpkg-dev
sudo apt-get install dropbox
sudo apt-get install dvd+rw-tools
sudo apt-get install e2fslibs:amd64
sudo apt-get install e2fsprogs
sudo apt-get install ed
sudo apt-get install eject
sudo apt-get install enchant
sudo apt-get install espeak
sudo apt-get install espeak-data:amd64
sudo apt-get install ethtool
sudo apt-get install evince
sudo apt-get install evince-common
sudo apt-get install evolution-data-server-common
sudo apt-get install execstack
sudo apt-get install exo-utils
sudo apt-get install extlinux
sudo apt-get install fakeroot
sudo apt-get install fancontrol
sudo apt-get install file
sudo apt-get install file-roller
sudo apt-get install filezilla
sudo apt-get install filezilla-common
sudo apt-get install findutils
sudo apt-get install finger
sudo apt-get install firefox
sudo apt-get install firefox-locale-en
sudo apt-get install firefox-locale-pt
sudo apt-get install flashplugin-installer
sudo apt-get install fontconfig
sudo apt-get install fontconfig-config
sudo apt-get install fonts-dejavu-core
sudo apt-get install fonts-droid
sudo apt-get install fonts-freefont-ttf
sudo apt-get install fonts-horai-umefont
sudo apt-get install fonts-kacst
sudo apt-get install fonts-kacst-one
sudo apt-get install fonts-khmeros-core
sudo apt-get install fonts-lao
sudo apt-get install fonts-liberation
sudo apt-get install fonts-lklug-sinhala
sudo apt-get install fonts-lyx
sudo apt-get install fonts-nanum
sudo apt-get install fonts-opensymbol
sudo apt-get install fonts-sil-abyssinica
sudo apt-get install fonts-sil-padauk
sudo apt-get install fonts-takao-pgothic
sudo apt-get install fonts-thai-tlwg
sudo apt-get install fonts-tibetan-machine
sudo apt-get install fonts-tlwg-garuda
sudo apt-get install fonts-tlwg-kinnari
sudo apt-get install fonts-tlwg-loma
sudo apt-get install fonts-tlwg-mono
sudo apt-get install fonts-tlwg-norasi
sudo apt-get install fonts-tlwg-purisa
sudo apt-get install fonts-tlwg-sawasdee
sudo apt-get install fonts-tlwg-typewriter
sudo apt-get install fonts-tlwg-typist
sudo apt-get install fonts-tlwg-typo
sudo apt-get install fonts-tlwg-umpush
sudo apt-get install fonts-tlwg-waree
sudo apt-get install fonts-unfonts-core
sudo apt-get install fonts-wqy-microhei
sudo apt-get install foomatic-db-compressed-ppds
sudo apt-get install freepats
sudo apt-get install friendly-recovery
sudo apt-get install ftp
sudo apt-get install fuse
sudo apt-get install g++
sudo apt-get install g++-4.8
sudo apt-get install gawk
sudo apt-get install gcc
sudo apt-get install gcc-4.8
sudo apt-get install gcc-4.8-base:amd64
sudo apt-get install gcc-4.8-base:i386
sudo apt-get install gcc-4.9-base:amd64
sudo apt-get install gcc-4.9-base:i386
sudo apt-get install gconf-service
sudo apt-get install gconf-service-backend
sudo apt-get install gconf2
sudo apt-get install gconf2-common
sudo apt-get install gcr
sudo apt-get install gdb
sudo apt-get install gdebi
sudo apt-get install gdebi-core
sudo apt-get install gdisk
sudo apt-get install geany
sudo apt-get install geany-common
sudo apt-get install genisoimage
sudo apt-get install geoip-database
sudo apt-get install gettext
sudo apt-get install gettext-base
sudo apt-get install ghostscript
sudo apt-get install ghostscript-x
sudo apt-get install gigolo
sudo apt-get install gimp
sudo apt-get install gimp-data
sudo apt-get install gimp-help-common
sudo apt-get install gimp-help-en
sudo apt-get install gir1.2-appindicator3-0.1
sudo apt-get install gir1.2-atk-1.0
sudo apt-get install gir1.2-atspi-2.0
sudo apt-get install gir1.2-dbusmenu-glib-0.4
sudo apt-get install gir1.2-dee-1.0
sudo apt-get install gir1.2-freedesktop
sudo apt-get install gir1.2-gconf-2.0
sudo apt-get install gir1.2-gdkpixbuf-2.0
sudo apt-get install gir1.2-glib-2.0
sudo apt-get install gir1.2-gmenu-3.0
sudo apt-get install gir1.2-gst-plugins-base-1.0
sudo apt-get install gir1.2-gstreamer-1.0
sudo apt-get install gir1.2-gtk-3.0
sudo apt-get install gir1.2-gudev-1.0
sudo apt-get install gir1.2-javascriptcoregtk-3.0
sudo apt-get install gir1.2-nautilus-3.0
sudo apt-get install gir1.2-notify-0.7
sudo apt-get install gir1.2-packagekitglib-1.0
sudo apt-get install gir1.2-pango-1.0
sudo apt-get install gir1.2-soup-2.4
sudo apt-get install gir1.2-udisks-2.0
sudo apt-get install gir1.2-unity-5.0:amd64
sudo apt-get install gir1.2-vte-2.90
sudo apt-get install gir1.2-webkit-3.0
sudo apt-get install gir1.2-wnck-3.0
sudo apt-get install git
sudo apt-get install git-flow
sudo apt-get install git-gui
sudo apt-get install git-man
sudo apt-get install gitk
sudo apt-get install gkrellm
sudo apt-get install gksu
sudo apt-get install glib-networking:amd64
sudo apt-get install glib-networking-common
sudo apt-get install glib-networking-services
sudo apt-get install gnome-accessibility-themes
sudo apt-get install gnome-calculator
sudo apt-get install gnome-desktop-data
sudo apt-get install gnome-desktop3-data
sudo apt-get install gnome-disk-utility
sudo apt-get install gnome-exe-thumbnailer
sudo apt-get install gnome-icon-theme
sudo apt-get install gnome-icon-theme-full
sudo apt-get install gnome-icon-theme-symbolic
sudo apt-get install gnome-keyring
sudo apt-get install gnome-menus
sudo apt-get install gnome-mines
sudo apt-get install gnome-nettool
sudo apt-get install gnome-sudoku
sudo apt-get install gnome-system-log
sudo apt-get install gnome-system-monitor
sudo apt-get install gnome-system-tools
sudo apt-get install gnome-themes-standard:amd64
sudo apt-get install gnome-themes-standard-data
sudo apt-get install gnome-user-guide
sudo apt-get install gnome-video-effects
sudo apt-get install gnomine
sudo apt-get install gnumeric-common
sudo apt-get install gnumeric-doc
sudo apt-get install gnupg
sudo apt-get install gobject-introspection
sudo apt-get install google-chrome-beta
sudo apt-get install google-talkplugin
sudo apt-get install gpart
sudo apt-get install gparted
sudo apt-get install gpgv
sudo apt-get install grep
sudo apt-get install groff-base
sudo apt-get install growisofs
sudo apt-get install grub-common
sudo apt-get install grub-gfxpayload-lists
sudo apt-get install grub-pc
sudo apt-get install grub-pc-bin
sudo apt-get install grub2-common
sudo apt-get install gsettings-desktop-schemas
sudo apt-get install gsettings-ubuntu-schemas
sudo apt-get install gsfonts
sudo apt-get install gsfonts-x11
sudo apt-get install gshutdown
sudo apt-get install gsmartcontrol
sudo apt-get install gstreamer-tools
sudo apt-get install gstreamer0.10-alsa:amd64
sudo apt-get install gstreamer0.10-fluendo-mp3:amd64
sudo apt-get install gstreamer0.10-nice:amd64
sudo apt-get install gstreamer0.10-plugins-bad:amd64
sudo apt-get install gstreamer0.10-plugins-bad-multiverse
sudo apt-get install gstreamer0.10-plugins-base:amd64
sudo apt-get install gstreamer0.10-plugins-base-apps
sudo apt-get install gstreamer0.10-plugins-good:amd64
sudo apt-get install gstreamer0.10-plugins-ugly:amd64
sudo apt-get install gstreamer0.10-pulseaudio:amd64
sudo apt-get install gstreamer0.10-tools
sudo apt-get install gstreamer0.10-x:amd64
sudo apt-get install gstreamer1.0-clutter
sudo apt-get install gstreamer1.0-fluendo-mp3:amd64
sudo apt-get install gstreamer1.0-libav:amd64
sudo apt-get install gstreamer1.0-plugins-bad:amd64
sudo apt-get install gstreamer1.0-plugins-bad-faad:amd64
sudo apt-get install gstreamer1.0-plugins-bad-videoparsers:amd64
sudo apt-get install gstreamer1.0-plugins-base:amd64
sudo apt-get install gstreamer1.0-plugins-good:amd64
sudo apt-get install gstreamer1.0-plugins-ugly:amd64
sudo apt-get install gstreamer1.0-pulseaudio:amd64
sudo apt-get install gstreamer1.0-tools
sudo apt-get install gstreamer1.0-x:amd64
sudo apt-get install gtk-theme-config
sudo apt-get install gtk2-engines-murrine:amd64
sudo apt-get install gtk2-engines-pixbuf:amd64
sudo apt-get install gucharmap
sudo apt-get install gufw
sudo apt-get install gvfs:amd64
sudo apt-get install gvfs-backends
sudo apt-get install gvfs-bin
sudo apt-get install gvfs-common
sudo apt-get install gvfs-daemons
sudo apt-get install gvfs-fuse
sudo apt-get install gvfs-libs:amd64
sudo apt-get install gzip
sudo apt-get install hardening-includes
sudo apt-get install hddtemp
sudo apt-get install hdparm
sudo apt-get install heirloom-mailx
sudo apt-get install hicolor-icon-theme
sudo apt-get install hostname
sudo apt-get install hplip
sudo apt-get install hplip-data
sudo apt-get install hplip-gui
sudo apt-get install htop
sudo apt-get install humanity-icon-theme
sudo apt-get install hunspell-en-us
sudo apt-get install hwdata
sudo apt-get install i2c-tools
sudo apt-get install icoutils
sudo apt-get install iftop
sudo apt-get install ifupdown
sudo apt-get install im-config
sudo apt-get install imagemagick
sudo apt-get install imagemagick-common
sudo apt-get install indicator-application
sudo apt-get install indicator-keylock
sudo apt-get install indicator-messages
sudo apt-get install indicator-power
sudo apt-get install indicator-sound
sudo apt-get install indicator-sysmonitor
sudo apt-get install info
sudo apt-get install init-system-helpers
sudo apt-get install initramfs-tools
sudo apt-get install initramfs-tools-bin
sudo apt-get install initscripts
sudo apt-get install inkscape
sudo apt-get install inputattach
sudo apt-get install insserv
sudo apt-get install install-info
sudo apt-get install intltool-debian
sudo apt-get install iproute
sudo apt-get install iproute2
sudo apt-get install iptables
sudo apt-get install iputils-arping
sudo apt-get install iputils-ping
sudo apt-get install iputils-tracepath
sudo apt-get install irqbalance
sudo apt-get install isc-dhcp-client
sudo apt-get install isc-dhcp-common
sudo apt-get install iso-codes
sudo apt-get install iw
sudo apt-get install java-common
sudo apt-get install kbd
sudo apt-get install kerneloops-daemon
sudo apt-get install keyboard-configuration
sudo apt-get install klibc-utils
sudo apt-get install kmod
sudo apt-get install krb5-locales
sudo apt-get install language-pack-en
sudo apt-get install language-pack-en-base
sudo apt-get install language-pack-gnome-en
sudo apt-get install language-pack-gnome-en-base
sudo apt-get install language-pack-gnome-pt
sudo apt-get install language-pack-gnome-pt-base
sudo apt-get install language-pack-pt
sudo apt-get install language-pack-pt-base
sudo apt-get install language-selector-common
sudo apt-get install language-selector-gnome
sudo apt-get install laptop-detect
sudo apt-get install less
sudo apt-get install liba52-0.7.4
sudo apt-get install libaa1:amd64
sudo apt-get install libaacs0:amd64
sudo apt-get install libabiword-3.0:amd64
sudo apt-get install libaccountsservice0:amd64
sudo apt-get install libacl1:amd64
sudo apt-get install libaio1:amd64
sudo apt-get install libalgorithm-diff-perl
sudo apt-get install libalgorithm-diff-xs-perl
sudo apt-get install libalgorithm-merge-perl
sudo apt-get install libamd2.3.1:amd64
sudo apt-get install libapparmor-perl
sudo apt-get install libapparmor1:amd64
sudo apt-get install libappindicator1
sudo apt-get install libappindicator3-1
sudo apt-get install libapt-inst1.5:amd64
sudo apt-get install libapt-pkg-perl
sudo apt-get install libapt-pkg4.12:amd64
sudo apt-get install libarchive-extract-perl
sudo apt-get install libarchive-zip-perl
sudo apt-get install libarchive13:amd64
sudo apt-get install libart-2.0-2:amd64
sudo apt-get install libasan0:amd64
sudo apt-get install libasn1-8-heimdal:amd64
sudo apt-get install libasn1-8-heimdal:i386
sudo apt-get install libasound2:amd64
sudo apt-get install libasound2:i386
sudo apt-get install libasound2-data
sudo apt-get install libasound2-plugins:amd64
sudo apt-get install libasound2-plugins:i386
sudo apt-get install libaspell15
sudo apt-get install libasprintf-dev:amd64
sudo apt-get install libasprintf0c2:amd64
sudo apt-get install libass4:amd64
sudo apt-get install libassuan0:amd64
sudo apt-get install libasyncns0:amd64
sudo apt-get install libasyncns0:i386
sudo apt-get install libatasmart4:amd64
sudo apt-get install libatk-bridge2.0-0:amd64
sudo apt-get install libatk1.0-0:amd64
sudo apt-get install libatk1.0-0:i386
sudo apt-get install libatk1.0-data
sudo apt-get install libatkmm-1.6-1:amd64
sudo apt-get install libatomic1:amd64
sudo apt-get install libatspi2.0-0:amd64
sudo apt-get install libattr1:amd64
sudo apt-get install libaudcore3:amd64
sudo apt-get install libaudio2:amd64
sudo apt-get install libaudit-common
sudo apt-get install libaudit1:amd64
sudo apt-get install libauthen-sasl-perl
sudo apt-get install libautodie-perl
sudo apt-get install libav-tools
sudo apt-get install libavahi-client3:amd64
sudo apt-get install libavahi-client3:i386
sudo apt-get install libavahi-common-data:amd64
sudo apt-get install libavahi-common-data:i386
sudo apt-get install libavahi-common3:amd64
sudo apt-get install libavahi-common3:i386
sudo apt-get install libavahi-core7:amd64
sudo apt-get install libavahi-glib1:amd64
sudo apt-get install libavc1394-0:amd64
sudo apt-get install libavcodec54:amd64
sudo apt-get install libavdevice53:amd64
sudo apt-get install libavfilter3:amd64
sudo apt-get install libavformat54:amd64
sudo apt-get install libavresample1:amd64
sudo apt-get install libavutil52:amd64
sudo apt-get install libbabl-0.1-0:amd64
sudo apt-get install libbasicusageenvironment0
sudo apt-get install libbind9-90
sudo apt-get install libbinio1ldbl:amd64
sudo apt-get install libblas3
sudo apt-get install libblkid1:amd64
sudo apt-get install libbluetooth3:amd64
sudo apt-get install libbluray1:amd64
sudo apt-get install libbonobo2-0:amd64
sudo apt-get install libbonobo2-common
sudo apt-get install libbonoboui2-0:amd64
sudo apt-get install libbonoboui2-common
sudo apt-get install libboost-date-time1.54.0:amd64
sudo apt-get install libboost-iostreams1.54.0:amd64
sudo apt-get install libboost-regex1.54.0:amd64
sudo apt-get install libboost-system1.54.0:amd64
sudo apt-get install libbrasero-media3-1
sudo apt-get install libbrlapi0.6:amd64
sudo apt-get install libbs2b0
sudo apt-get install libbsd0:amd64
sudo apt-get install libburn4
sudo apt-get install libbz2-1.0:amd64
sudo apt-get install libc-bin
sudo apt-get install libc-dev-bin
sudo apt-get install libc6:amd64
sudo apt-get install libc6:i386
sudo apt-get install libc6-dbg:amd64
sudo apt-get install libc6-dev:amd64
sudo apt-get install libcaca0:amd64
sudo apt-get install libcaca0:i386
sudo apt-get install libcairo-gobject2:amd64
sudo apt-get install libcairo-perl
sudo apt-get install libcairo2:amd64
sudo apt-get install libcairo2:i386
sudo apt-get install libcairomm-1.0-1:amd64
sudo apt-get install libcamd2.3.1:amd64
sudo apt-get install libcamel-1.2-45
sudo apt-get install libcanberra-gtk3-0:amd64
sudo apt-get install libcanberra-gtk3-module:amd64
sudo apt-get install libcanberra0:amd64
sudo apt-get install libcap-ng0
sudo apt-get install libcap2:amd64
sudo apt-get install libcap2-bin
sudo apt-get install libcapi20-3:amd64
sudo apt-get install libcapi20-3:i386
sudo apt-get install libccolamd2.8.0:amd64
sudo apt-get install libcdaudio1
sudo apt-get install libcddb2
sudo apt-get install libcdio-cdda1
sudo apt-get install libcdio-paranoia1
sudo apt-get install libcdio13
sudo apt-get install libcdparanoia0:amd64
sudo apt-get install libcgmanager0:amd64
sudo apt-get install libcgmanager0:i386
sudo apt-get install libchamplain-0.12-0:amd64
sudo apt-get install libchamplain-gtk-0.12-0:amd64
sudo apt-get install libcheese-gtk23:amd64
sudo apt-get install libcheese7:amd64
sudo apt-get install libcholmod2.1.2:amd64
sudo apt-get install libchromaprint0:amd64
sudo apt-get install libclass-accessor-perl
sudo apt-get install libclone-perl
sudo apt-get install libcloog-isl4:amd64
sudo apt-get install libclucene-contribs1:amd64
sudo apt-get install libclucene-core1:amd64
sudo apt-get install libclutter-1.0-0:amd64
sudo apt-get install libclutter-1.0-common
sudo apt-get install libclutter-gst-2.0-0:amd64
sudo apt-get install libclutter-gtk-1.0-0:amd64
sudo apt-get install libcogl-common
sudo apt-get install libcogl-pango15:amd64
sudo apt-get install libcogl15:amd64
sudo apt-get install libcolamd2.8.0:amd64
sudo apt-get install libcolord1:amd64
sudo apt-get install libcolorhug1:amd64
sudo apt-get install libcomerr2:amd64
sudo apt-get install libcomerr2:i386
sudo apt-get install libcompizconfig0
sudo apt-get install libcrack2:amd64
sudo apt-get install libcroco3:amd64
sudo apt-get install libcrypt-passwdmd5-perl
sudo apt-get install libcrystalhd3:amd64
sudo apt-get install libctemplate2
sudo apt-get install libcue1
sudo apt-get install libcups2:amd64
sudo apt-get install libcups2:i386
sudo apt-get install libcupscgi1:amd64
sudo apt-get install libcupsfilters1:amd64
sudo apt-get install libcupsimage2:amd64
sudo apt-get install libcupsmime1:amd64
sudo apt-get install libcupsppdc1:amd64
sudo apt-get install libcurl3:amd64
sudo apt-get install libcurl3-gnutls:amd64
sudo apt-get install libdaemon0
sudo apt-get install libdatrie1:amd64
sudo apt-get install libdatrie1:i386
sudo apt-get install libdb5.3:amd64
sudo apt-get install libdb5.3:i386
sudo apt-get install libdbd-mysql-perl
sudo apt-get install libdbi-perl
sudo apt-get install libdbus-1-3:amd64
sudo apt-get install libdbus-1-3:i386
sudo apt-get install libdbus-glib-1-2:amd64
sudo apt-get install libdbusmenu-glib4:amd64
sudo apt-get install libdbusmenu-gtk3-4:amd64
sudo apt-get install libdbusmenu-gtk4:amd64
sudo apt-get install libdc1394-22:amd64
sudo apt-get install libdca0:amd64
sudo apt-get install libdconf1:amd64
sudo apt-get install libdebconfclient0:amd64
sudo apt-get install libdecoration0
sudo apt-get install libdee-1.0-4:amd64
sudo apt-get install libdevmapper1.02.1:amd64
sudo apt-get install libdigest-crc-perl
sudo apt-get install libdigest-hmac-perl
sudo apt-get install libdirac-encoder0:amd64
sudo apt-get install libdirectfb-1.2-9:amd64
sudo apt-get install libdjvulibre-text
sudo apt-get install libdjvulibre21:amd64
sudo apt-get install libdns100
sudo apt-get install libdotconf0:amd64
sudo apt-get install libdpkg-perl
sudo apt-get install libdrm-intel1:amd64
sudo apt-get install libdrm-intel1:i386
sudo apt-get install libdrm-nouveau2:amd64
sudo apt-get install libdrm-nouveau2:i386
sudo apt-get install libdrm-radeon1:amd64
sudo apt-get install libdrm-radeon1:i386
sudo apt-get install libdrm2:amd64
sudo apt-get install libdrm2:i386
sudo apt-get install libdv4:amd64
sudo apt-get install libdvbpsi8:amd64
sudo apt-get install libdvdnav4:amd64
sudo apt-get install libdvdread4:amd64
sudo apt-get install libebml4:amd64
sudo apt-get install libebook-contacts-1.2-0
sudo apt-get install libedataserver-1.2-18
sudo apt-get install libedit2:amd64
sudo apt-get install libegl1-mesa:amd64
sudo apt-get install libegl1-mesa-drivers:amd64
sudo apt-get install libelf1:amd64
sudo apt-get install libelf1:i386
sudo apt-get install libelfg0:amd64
sudo apt-get install libemail-valid-perl
sudo apt-get install libenca0:amd64
sudo apt-get install libenchant1c2a:amd64
sudo apt-get install libencode-locale-perl
sudo apt-get install libept1.4.12:amd64
sudo apt-get install liberror-perl
sudo apt-get install libespeak1:amd64
sudo apt-get install libestr0
sudo apt-get install libevdocument3-4
sudo apt-get install libevent-2.0-5:amd64
sudo apt-get install libevview3-3
sudo apt-get install libexif12:amd64
sudo apt-get install libexif12:i386
sudo apt-get install libexo-1-0:amd64
sudo apt-get install libexo-common
sudo apt-get install libexo-helpers
sudo apt-get install libexpat1:amd64
sudo apt-get install libexpat1:i386
sudo apt-get install libexttextcat-2.0-0
sudo apt-get install libexttextcat-data
sudo apt-get install libfaac0:amd64
sudo apt-get install libfaad2:amd64
sudo apt-get install libfakeroot:amd64
sudo apt-get install libfarstream-0.1-0:amd64
sudo apt-get install libffi6:amd64
sudo apt-get install libffi6:i386
sudo apt-get install libfftw3-double3:amd64
sudo apt-get install libfftw3-single3:amd64
sudo apt-get install libfile-basedir-perl
sudo apt-get install libfile-copy-recursive-perl
sudo apt-get install libfile-desktopentry-perl
sudo apt-get install libfile-fcntllock-perl
sudo apt-get install libfile-listing-perl
sudo apt-get install libfile-mimeinfo-perl
sudo apt-get install libflac8:amd64
sudo apt-get install libflac8:i386
sudo apt-get install libflite1:amd64
sudo apt-get install libfltk1.1:amd64
sudo apt-get install libfluidsynth1:amd64
sudo apt-get install libfont-afm-perl
sudo apt-get install libfontconfig1:amd64
sudo apt-get install libfontconfig1:i386
sudo apt-get install libfontembed1:amd64
sudo apt-get install libfontenc1:amd64
sudo apt-get install libframe6:amd64
sudo apt-get install libfreerdp1:amd64
sudo apt-get install libfreetype6:amd64
sudo apt-get install libfreetype6:i386
sudo apt-get install libfribidi0:amd64
sudo apt-get install libfs6:amd64
sudo apt-get install libfuse2:amd64
sudo apt-get install libgail-3-0:amd64
sudo apt-get install libgail18:amd64
sudo apt-get install libgarcon-1-0
sudo apt-get install libgarcon-common
sudo apt-get install libgbm1:amd64
sudo apt-get install libgc1c2:amd64
sudo apt-get install libgcc-4.8-dev:amd64
sudo apt-get install libgcc1:amd64
sudo apt-get install libgcc1:i386
sudo apt-get install libgck-1-0:amd64
sudo apt-get install libgconf-2-4:amd64
sudo apt-get install libgconfmm-2.6-1c2
sudo apt-get install libgcr-3-common
sudo apt-get install libgcr-base-3-1:amd64
sudo apt-get install libgcr-ui-3-1:amd64
sudo apt-get install libgcrypt11:amd64
sudo apt-get install libgcrypt11:i386
sudo apt-get install libgd3:amd64
sudo apt-get install libgd3:i386
sudo apt-get install libgdbm3:amd64
sudo apt-get install libgdk-pixbuf2.0-0:amd64
sudo apt-get install libgdk-pixbuf2.0-0:i386
sudo apt-get install libgdk-pixbuf2.0-common
sudo apt-get install libgdome2-0
sudo apt-get install libgdome2-cpp-smart0c2a
sudo apt-get install libgegl-0.2-0:amd64
sudo apt-get install libgeis1:amd64
sudo apt-get install libgeoclue0:amd64
sudo apt-get install libgeoip1:amd64
sudo apt-get install libgettextpo-dev:amd64
sudo apt-get install libgettextpo0:amd64
sudo apt-get install libgfortran3:amd64
sudo apt-get install libgif4:amd64
sudo apt-get install libgif4:i386
sudo apt-get install libgimp2.0
sudo apt-get install libgirepository-1.0-1
sudo apt-get install libgksu2-0
sudo apt-get install libgl1-mesa-dri:amd64
sudo apt-get install libgl1-mesa-dri:i386
sudo apt-get install libgl1-mesa-glx:amd64
sudo apt-get install libgl1-mesa-glx:i386
sudo apt-get install libglade2-0:amd64
sudo apt-get install libglademm-2.4-1c2a
sudo apt-get install libglamor0:amd64
sudo apt-get install libglapi-mesa:amd64
sudo apt-get install libglapi-mesa:i386
sudo apt-get install libgles2-mesa:amd64
sudo apt-get install libglew1.10:amd64
sudo apt-get install libglib-perl
sudo apt-get install libglib2.0-0:amd64
sudo apt-get install libglib2.0-0:i386
sudo apt-get install libglib2.0-bin
sudo apt-get install libglib2.0-data
sudo apt-get install libglibmm-2.4-1c2a:amd64
sudo apt-get install libglu1-mesa:amd64
sudo apt-get install libglu1-mesa:i386
sudo apt-get install libgme0
sudo apt-get install libgmime-2.6-0:amd64
sudo apt-get install libgmp10:amd64
sudo apt-get install libgnome-bluetooth11
sudo apt-get install libgnome-desktop-3-7
sudo apt-get install libgnome-keyring-common
sudo apt-get install libgnome-keyring0:amd64
sudo apt-get install libgnome-menu-3-0
sudo apt-get install libgnome2-0:amd64
sudo apt-get install libgnome2-bin
sudo apt-get install libgnome2-common
sudo apt-get install libgnomecanvas2-0:amd64
sudo apt-get install libgnomecanvas2-common
sudo apt-get install libgnomeui-0:amd64
sudo apt-get install libgnomeui-common
sudo apt-get install libgnomevfs2-0:amd64
sudo apt-get install libgnomevfs2-common
sudo apt-get install libgnomevfs2-extra:amd64
sudo apt-get install libgnutls-openssl27:amd64
sudo apt-get install libgnutls26:amd64
sudo apt-get install libgnutls26:i386
sudo apt-get install libgnutls28:amd64
sudo apt-get install libgoffice-0.10-10
sudo apt-get install libgoffice-0.10-10-common
sudo apt-get install libgomp1:amd64
sudo apt-get install libgpg-error0:amd64
sudo apt-get install libgpg-error0:i386
sudo apt-get install libgpgme11:amd64
sudo apt-get install libgphoto2-6:amd64
sudo apt-get install libgphoto2-6:i386
sudo apt-get install libgphoto2-l10n
sudo apt-get install libgphoto2-port10:amd64
sudo apt-get install libgphoto2-port10:i386
sudo apt-get install libgpm2:amd64
sudo apt-get install libgpm2:i386
sudo apt-get install libgrail6
sudo apt-get install libgraphite2-3:amd64
sudo apt-get install libgraphite2-3:i386
sudo apt-get install libgrip0
sudo apt-get install libgroupsock1
sudo apt-get install libgs9
sudo apt-get install libgs9-common
sudo apt-get install libgsf-1-114
sudo apt-get install libgsf-1-common
sudo apt-get install libgsl0ldbl
sudo apt-get install libgsm1:amd64
sudo apt-get install libgssapi-krb5-2:amd64
sudo apt-get install libgssapi-krb5-2:i386
sudo apt-get install libgssapi3-heimdal:amd64
sudo apt-get install libgssapi3-heimdal:i386
sudo apt-get install libgssdp-1.0-3
sudo apt-get install libgstreamer-perl
sudo apt-get install libgstreamer-plugins-bad0.10-0:amd64
sudo apt-get install libgstreamer-plugins-bad1.0-0:amd64
sudo apt-get install libgstreamer-plugins-base0.10-0:amd64
sudo apt-get install libgstreamer-plugins-base0.10-0:i386
sudo apt-get install libgstreamer-plugins-base1.0-0:amd64
sudo apt-get install libgstreamer-plugins-good1.0-0:amd64
sudo apt-get install libgstreamer0.10-0:amd64
sudo apt-get install libgstreamer0.10-0:i386
sudo apt-get install libgstreamer1.0-0:amd64
sudo apt-get install libgtk-3-0:amd64
sudo apt-get install libgtk-3-bin
sudo apt-get install libgtk-3-common
sudo apt-get install libgtk2-notify-perl
sudo apt-get install libgtk2-perl
sudo apt-get install libgtk2-trayicon-perl
sudo apt-get install libgtk2.0-0:amd64
sudo apt-get install libgtk2.0-0:i386
sudo apt-get install libgtk2.0-bin
sudo apt-get install libgtk2.0-common
sudo apt-get install libgtkglext1
sudo apt-get install libgtkmathview0c2a
sudo apt-get install libgtkmm-2.4-1c2a:amd64
sudo apt-get install libgtkmm-3.0-1:amd64
sudo apt-get install libgtksourceview2.0-0
sudo apt-get install libgtksourceview2.0-common
sudo apt-get install libgtkspell0
sudo apt-get install libgtop2-7
sudo apt-get install libgtop2-common
sudo apt-get install libgucharmap-2-90-7
sudo apt-get install libgudev-1.0-0:amd64
sudo apt-get install libguess1:amd64
sudo apt-get install libgupnp-1.0-4
sudo apt-get install libgupnp-igd-1.0-4:amd64
sudo apt-get install libgusb2:amd64
sudo apt-get install libgutenprint2
sudo apt-get install libgxps2:amd64
sudo apt-get install libharfbuzz-icu0:amd64
sudo apt-get install libharfbuzz0b:amd64
sudo apt-get install libharfbuzz0b:i386
sudo apt-get install libhcrypto4-heimdal:amd64
sudo apt-get install libhcrypto4-heimdal:i386
sudo apt-get install libhdb9-heimdal:amd64
sudo apt-get install libheimbase1-heimdal:amd64
sudo apt-get install libheimbase1-heimdal:i386
sudo apt-get install libheimntlm0-heimdal:amd64
sudo apt-get install libheimntlm0-heimdal:i386
sudo apt-get install libhogweed2:amd64
sudo apt-get install libhpmud0
sudo apt-get install libhtml-form-perl
sudo apt-get install libhtml-format-perl
sudo apt-get install libhtml-parser-perl
sudo apt-get install libhtml-tagset-perl
sudo apt-get install libhtml-template-perl
sudo apt-get install libhtml-tree-perl
sudo apt-get install libhttp-cookies-perl
sudo apt-get install libhttp-daemon-perl
sudo apt-get install libhttp-date-perl
sudo apt-get install libhttp-message-perl
sudo apt-get install libhttp-negotiate-perl
sudo apt-get install libhunspell-1.3-0:amd64
sudo apt-get install libhx509-5-heimdal:amd64
sudo apt-get install libhx509-5-heimdal:i386
sudo apt-get install libhyphen0
sudo apt-get install libical1
sudo apt-get install libice6:amd64
sudo apt-get install libice6:i386
sudo apt-get install libicu52:amd64
sudo apt-get install libid3tag0
sudo apt-get install libidl-common
sudo apt-get install libidl0:amd64
sudo apt-get install libidn11:amd64
sudo apt-get install libido3-0.1-0:amd64
sudo apt-get install libiec61883-0:amd64
sudo apt-get install libieee1284-3:amd64
sudo apt-get install libieee1284-3:i386
sudo apt-get install libijs-0.35
sudo apt-get install libilmbase6:amd64
sudo apt-get install libimlib2
sudo apt-get install libimobiledevice4:amd64
sudo apt-get install libindicator3-7
sudo apt-get install libindicator7
sudo apt-get install libintl-perl
sudo apt-get install libio-html-perl
sudo apt-get install libio-pty-perl
sudo apt-get install libio-socket-inet6-perl
sudo apt-get install libio-socket-ssl-perl
sudo apt-get install libio-string-perl
sudo apt-get install libipc-run-perl
sudo apt-get install libipc-system-simple-perl
sudo apt-get install libisc95
sudo apt-get install libisccc90
sudo apt-get install libisccfg90
sudo apt-get install libisl10:amd64
sudo apt-get install libiso9660-8
sudo apt-get install libisofs6
sudo apt-get install libitm1:amd64
sudo apt-get install libiw30:amd64
sudo apt-get install libjack-jackd2-0:amd64
sudo apt-get install libjack-jackd2-0:i386
sudo apt-get install libjasper1:amd64
sudo apt-get install libjasper1:i386
sudo apt-get install libjavascriptcoregtk-1.0-0:amd64
sudo apt-get install libjavascriptcoregtk-3.0-0:amd64
sudo apt-get install libjbig0:amd64
sudo apt-get install libjbig0:i386
sudo apt-get install libjbig2dec0
sudo apt-get install libjpeg-turbo8:amd64
sudo apt-get install libjpeg-turbo8:i386
sudo apt-get install libjpeg62:i386
sudo apt-get install libjpeg8:amd64
sudo apt-get install libjpeg8:i386
sudo apt-get install libjson-c2:amd64
sudo apt-get install libjson-c2:i386
sudo apt-get install libjson-glib-1.0-0:amd64
sudo apt-get install libjson-glib-1.0-common
sudo apt-get install libjson0:amd64
sudo apt-get install libjte1
sudo apt-get install libk5crypto3:amd64
sudo apt-get install libk5crypto3:i386
sudo apt-get install libkate1
sudo apt-get install libkdc2-heimdal:amd64
sudo apt-get install libkeybinder0
sudo apt-get install libkeyutils1:amd64
sudo apt-get install libkeyutils1:i386
sudo apt-get install libklibc
sudo apt-get install libkmod2:amd64
sudo apt-get install libkpathsea6
sudo apt-get install libkrb5-26-heimdal:amd64
sudo apt-get install libkrb5-26-heimdal:i386
sudo apt-get install libkrb5-3:amd64
sudo apt-get install libkrb5-3:i386
sudo apt-get install libkrb5support0:amd64
sudo apt-get install libkrb5support0:i386
sudo apt-get install liblangtag-common
sudo apt-get install liblangtag1
sudo apt-get install liblapack3
sudo apt-get install liblcms2-2:amd64
sudo apt-get install liblcms2-2:i386
sudo apt-get install libldap-2.4-2:amd64
sudo apt-get install libldap-2.4-2:i386
sudo apt-get install libldb1:amd64
sudo apt-get install liblightdm-gobject-1-0
sudo apt-get install liblinear-tools
sudo apt-get install liblinear1
sudo apt-get install liblink-grammar4
sudo apt-get install liblircclient0
sudo apt-get install liblist-moreutils-perl
sudo apt-get install liblivemedia23
sudo apt-get install libllvm3.4:amd64
sudo apt-get install libllvm3.4:i386
sudo apt-get install liblocale-gettext-perl
sudo apt-get install liblockfile-bin
sudo apt-get install liblockfile1:amd64
sudo apt-get install liblog-message-simple-perl
sudo apt-get install libloudmouth1-0
sudo apt-get install liblqr-1-0:amd64
sudo apt-get install libltdl-dev:amd64
sudo apt-get install libltdl7:amd64
sudo apt-get install libltdl7:i386
sudo apt-get install liblua5.2-0:amd64
sudo apt-get install liblwp-mediatypes-perl
sudo apt-get install liblwp-protocol-https-perl
sudo apt-get install liblwres90
sudo apt-get install liblzma5:amd64
sudo apt-get install liblzma5:i386
sudo apt-get install liblzo2-2:amd64
sudo apt-get install libmad0:amd64
sudo apt-get install libmagic1:amd64
sudo apt-get install libmagick++5:amd64
sudo apt-get install libmagickcore5:amd64
sudo apt-get install libmagickcore5-extra:amd64
sudo apt-get install libmagickwand5:amd64
sudo apt-get install libmail-sendmail-perl
sudo apt-get install libmailtools-perl
sudo apt-get install libmariadbclient18
sudo apt-get install libmatroska6:amd64
sudo apt-get install libmbim-glib0:amd64
sudo apt-get install libmcrypt4
sudo apt-get install libmeanwhile1
sudo apt-get install libmessaging-menu0
sudo apt-get install libmhash2:amd64
sudo apt-get install libmimic0
sudo apt-get install libminiupnpc8
sudo apt-get install libmjpegutils-2.1-0
sudo apt-get install libmm-glib0:amd64
sudo apt-get install libmms0:amd64
sudo apt-get install libmng2:amd64
sudo apt-get install libmnl0:amd64
sudo apt-get install libmodplug1
sudo apt-get install libmodule-pluggable-perl
sudo apt-get install libmount1:amd64
sudo apt-get install libmowgli-2-0:amd64
sudo apt-get install libmp3lame0:amd64
sudo apt-get install libmpc3:amd64
sudo apt-get install libmpcdec6
sudo apt-get install libmpdec2:amd64
sudo apt-get install libmpeg2-4:amd64
sudo apt-get install libmpeg2encpp-2.1-0
sudo apt-get install libmpfr4:amd64
sudo apt-get install libmpg123-0:amd64
sudo apt-get install libmpg123-0:i386
sudo apt-get install libmplex2-2.1-0
sudo apt-get install libmtdev1:amd64
sudo apt-get install libmtp-common
sudo apt-get install libmtp-runtime
sudo apt-get install libmtp9:amd64
sudo apt-get install libmysqlclient18
sudo apt-get install libmythes-1.2-0
sudo apt-get install libnatpmp1
sudo apt-get install libnautilus-extension1a
sudo apt-get install libncurses5:amd64
sudo apt-get install libncurses5:i386
sudo apt-get install libncursesw5:amd64
sudo apt-get install libncursesw5:i386
sudo apt-get install libneon27-gnutls
sudo apt-get install libnet-dbus-perl
sudo apt-get install libnet-dns-perl
sudo apt-get install libnet-domain-tld-perl
sudo apt-get install libnet-http-perl
sudo apt-get install libnet-ip-perl
sudo apt-get install libnet-libidn-perl
sudo apt-get install libnet-smtp-ssl-perl
sudo apt-get install libnet-ssleay-perl
sudo apt-get install libnetfilter-conntrack3:amd64
sudo apt-get install libnetpbm10
sudo apt-get install libnettle4:amd64
sudo apt-get install libnewt0.52:amd64
sudo apt-get install libnfnetlink0:amd64
sudo apt-get install libnice10:amd64
sudo apt-get install libnih-dbus1:amd64
sudo apt-get install libnih-dbus1:i386
sudo apt-get install libnih1:amd64
sudo apt-get install libnih1:i386
sudo apt-get install libnl-3-200:amd64
sudo apt-get install libnl-genl-3-200:amd64
sudo apt-get install libnl-route-3-200:amd64
sudo apt-get install libnm-glib-vpn1
sudo apt-get install libnm-glib4
sudo apt-get install libnm-gtk-common
sudo apt-get install libnm-gtk0
sudo apt-get install libnm-util2
sudo apt-get install libnotify-bin
sudo apt-get install libnotify4:amd64
sudo apt-get install libnspr4:amd64
sudo apt-get install libnss-mdns:amd64
sudo apt-get install libnss-winbind:amd64
sudo apt-get install libnss3:amd64
sudo apt-get install libnss3-nssdb
sudo apt-get install libntdb1:amd64
sudo apt-get install libntlm0:amd64
sudo apt-get install libnuma1:amd64
sudo apt-get install libodbc1:amd64
sudo apt-get install libofa0
sudo apt-get install libogg0:amd64
sudo apt-get install libogg0:i386
sudo apt-get install liboil0.3:amd64
sudo apt-get install libonig2
sudo apt-get install liboobs-1-5
sudo apt-get install libopenal-data
sudo apt-get install libopenal1:amd64
sudo apt-get install libopenal1:i386
sudo apt-get install libopencore-amrnb0:amd64
sudo apt-get install libopencore-amrwb0:amd64
sudo apt-get install libopencv-calib3d2.4:amd64
sudo apt-get install libopencv-contrib2.4:amd64
sudo apt-get install libopencv-core2.4:amd64
sudo apt-get install libopencv-features2d2.4:amd64
sudo apt-get install libopencv-flann2.4:amd64
sudo apt-get install libopencv-highgui2.4:amd64
sudo apt-get install libopencv-imgproc2.4:amd64
sudo apt-get install libopencv-legacy2.4:amd64
sudo apt-get install libopencv-ml2.4:amd64
sudo apt-get install libopencv-objdetect2.4:amd64
sudo apt-get install libopencv-video2.4:amd64
sudo apt-get install libopenexr6:amd64
sudo apt-get install libopenjpeg2:amd64
sudo apt-get install libopenobex1
sudo apt-get install libopenvg1-mesa:amd64
sudo apt-get install libopus0
sudo apt-get install liborbit-2-0:amd64
sudo apt-get install liborbit2:amd64
sudo apt-get install liborc-0.4-0:amd64
sudo apt-get install liborc-0.4-0:i386
sudo apt-get install libosmesa6:amd64
sudo apt-get install libosmesa6:i386
sudo apt-get install libotr5
sudo apt-get install libots0
sudo apt-get install libp11-kit-gnome-keyring:amd64
sudo apt-get install libp11-kit-gnome-keyring:i386
sudo apt-get install libp11-kit0:amd64
sudo apt-get install libp11-kit0:i386
sudo apt-get install libpackagekit-glib2-16:amd64
sudo apt-get install libpam-cap:amd64
sudo apt-get install libpam-gnome-keyring:amd64
sudo apt-get install libpam-modules:amd64
sudo apt-get install libpam-modules-bin
sudo apt-get install libpam-runtime
sudo apt-get install libpam-systemd:amd64
sudo apt-get install libpam-winbind:amd64
sudo apt-get install libpam0g:amd64
sudo apt-get install libpango-1.0-0:amd64
sudo apt-get install libpango-1.0-0:i386
sudo apt-get install libpango-perl
sudo apt-get install libpango1.0-0:amd64
sudo apt-get install libpangocairo-1.0-0:amd64
sudo apt-get install libpangocairo-1.0-0:i386
sudo apt-get install libpangoft2-1.0-0:amd64
sudo apt-get install libpangoft2-1.0-0:i386
sudo apt-get install libpangomm-1.4-1:amd64
sudo apt-get install libpangox-1.0-0:amd64
sudo apt-get install libpangoxft-1.0-0:amd64
sudo apt-get install libpaper-utils
sudo apt-get install libpaper1:amd64
sudo apt-get install libparse-debianchangelog-perl
sudo apt-get install libparted0debian1:amd64
sudo apt-get install libpcap0.8:amd64
sudo apt-get install libpci3:amd64
sudo apt-get install libpciaccess0:amd64
sudo apt-get install libpciaccess0:i386
sudo apt-get install libpcre3:amd64
sudo apt-get install libpcre3:i386
sudo apt-get install libpcre3-dev:amd64
sudo apt-get install libpcrecpp0:amd64
sudo apt-get install libpcsclite1:amd64
sudo apt-get install libperl5.18
sudo apt-get install libperlio-gzip-perl
sudo apt-get install libpipeline1:amd64
sudo apt-get install libpixman-1-0:amd64
sudo apt-get install libpixman-1-0:i386
sudo apt-get install libplist1:amd64
sudo apt-get install libplymouth2:amd64
sudo apt-get install libpng12-0:amd64
sudo apt-get install libpng12-0:i386
sudo apt-get install libpod-latex-perl
sudo apt-get install libpolkit-agent-1-0:amd64
sudo apt-get install libpolkit-backend-1-0:amd64
sudo apt-get install libpolkit-gobject-1-0:amd64
sudo apt-get install libpoppler-glib8:amd64
sudo apt-get install libpoppler44:amd64
sudo apt-get install libpopt0:amd64
sudo apt-get install libportaudio2:amd64
sudo apt-get install libpostproc52
sudo apt-get install libprocps3:amd64
sudo apt-get install libprotobuf8:amd64
sudo apt-get install libproxy-tools
sudo apt-get install libproxy1:amd64
sudo apt-get install libpulse-mainloop-glib0:amd64
sudo apt-get install libpulse0:amd64
sudo apt-get install libpulse0:i386
sudo apt-get install libpulsedsp:amd64
sudo apt-get install libpurple-bin
sudo apt-get install libpurple0
sudo apt-get install libpwquality-common
sudo apt-get install libpwquality1:amd64
sudo apt-get install libpython-stdlib:amd64
sudo apt-get install libpython2.7:amd64
sudo apt-get install libpython2.7-minimal:amd64
sudo apt-get install libpython2.7-stdlib:amd64
sudo apt-get install libpython3-stdlib:amd64
sudo apt-get install libpython3.4:amd64
sudo apt-get install libpython3.4-minimal:amd64
sudo apt-get install libpython3.4-stdlib:amd64
sudo apt-get install libqdbm14
sudo apt-get install libqmi-glib0:amd64
sudo apt-get install libqpdf13:amd64
sudo apt-get install libqscintilla2-11
sudo apt-get install libqscintilla2-l10n
sudo apt-get install libqt4-dbus:amd64
sudo apt-get install libqt4-declarative:amd64
sudo apt-get install libqt4-designer:amd64
sudo apt-get install libqt4-help:amd64
sudo apt-get install libqt4-network:amd64
sudo apt-get install libqt4-opengl:amd64
sudo apt-get install libqt4-script:amd64
sudo apt-get install libqt4-scripttools:amd64
sudo apt-get install libqt4-sql:amd64
sudo apt-get install libqt4-sql-sqlite:amd64
sudo apt-get install libqt4-svg:amd64
sudo apt-get install libqt4-test:amd64
sudo apt-get install libqt4-xml:amd64
sudo apt-get install libqt4-xmlpatterns:amd64
sudo apt-get install libqt5core5a:amd64
sudo apt-get install libqt5dbus5:amd64
sudo apt-get install libqt5gui5:amd64
sudo apt-get install libqt5multimedia5:amd64
sudo apt-get install libqt5network5:amd64
sudo apt-get install libqt5opengl5:amd64
sudo apt-get install libqt5widgets5:amd64
sudo apt-get install libqtassistantclient4:amd64
sudo apt-get install libqtcore4:amd64
sudo apt-get install libqtdbus4:amd64
sudo apt-get install libqtgui4:amd64
sudo apt-get install libqtwebkit4:amd64
sudo apt-get install libquadmath0:amd64
sudo apt-get install libquvi-scripts
sudo apt-get install libquvi7:amd64
sudo apt-get install libraptor2-0:amd64
sudo apt-get install librarian0
sudo apt-get install librasqal3:amd64
sudo apt-get install libraw1394-11:amd64
sudo apt-get install librdf0:amd64
sudo apt-get install libreadline5:amd64
sudo apt-get install libreadline6:amd64
sudo apt-get install libreoffice-avmedia-backend-gstreamer
sudo apt-get install libreoffice-base-core
sudo apt-get install libreoffice-calc
sudo apt-get install libreoffice-common
sudo apt-get install libreoffice-core
sudo apt-get install libreoffice-draw
sudo apt-get install libreoffice-help-pt
sudo apt-get install libreoffice-help-pt-br
sudo apt-get install libreoffice-impress
sudo apt-get install libreoffice-l10n-pt
sudo apt-get install libreoffice-l10n-pt-br
sudo apt-get install libreoffice-math
sudo apt-get install libreoffice-pdfimport
sudo apt-get install libreoffice-style-crystal
sudo apt-get install libreoffice-style-galaxy
sudo apt-get install libreoffice-style-hicontrast
sudo apt-get install libreoffice-style-human
sudo apt-get install libreoffice-style-oxygen
sudo apt-get install libreoffice-style-sifr
sudo apt-get install libreoffice-style-tango
sudo apt-get install libreoffice-writer
sudo apt-get install libresid-builder0c2a
sudo apt-get install libroken18-heimdal:amd64
sudo apt-get install libroken18-heimdal:i386
sudo apt-get install librpm3
sudo apt-get install librpmbuild3
sudo apt-get install librpmio3
sudo apt-get install librpmsign1
sudo apt-get install librsvg2-2:amd64
sudo apt-get install librsvg2-common:amd64
sudo apt-get install librtmp0:amd64
sudo apt-get install libruby1.9.1
sudo apt-get install libsamplerate0:amd64
sudo apt-get install libsamplerate0:i386
sudo apt-get install libsane:amd64
sudo apt-get install libsane:i386
sudo apt-get install libsane-common
sudo apt-get install libsane-hpaio
sudo apt-get install libsasl2-2:amd64
sudo apt-get install libsasl2-2:i386
sudo apt-get install libsasl2-modules:amd64
sudo apt-get install libsasl2-modules:i386
sudo apt-get install libsasl2-modules-db:amd64
sudo apt-get install libsasl2-modules-db:i386
sudo apt-get install libsbc1:amd64
sudo apt-get install libschroedinger-1.0-0:amd64
sudo apt-get install libsdl-image1.2:amd64
sudo apt-get install libsdl1.2debian:amd64
sudo apt-get install libsdl1.2debian:i386
sudo apt-get install libsecret-1-0:amd64
sudo apt-get install libsecret-common
sudo apt-get install libselinux1:amd64
sudo apt-get install libselinux1:i386
sudo apt-get install libsemanage-common
sudo apt-get install libsemanage1:amd64
sudo apt-get install libsensors4:amd64
sudo apt-get install libsepol1:amd64
sudo apt-get install libsexy2
sudo apt-get install libshout3:amd64
sudo apt-get install libsidplay1
sudo apt-get install libsidplay2
sudo apt-get install libsidplayfp:amd64
sudo apt-get install libsigc++-2.0-0c2a:amd64
sudo apt-get install libsigsegv2:amd64
sudo apt-get install libslang2:amd64
sudo apt-get install libslang2:i386
sudo apt-get install libslv2-9
sudo apt-get install libsm6:amd64
sudo apt-get install libsm6:i386
sudo apt-get install libsmbclient:amd64
sudo apt-get install libsndfile1:amd64
sudo apt-get install libsndfile1:i386
sudo apt-get install libsnmp-base
sudo apt-get install libsnmp30:amd64
sudo apt-get install libsocket6-perl
sudo apt-get install libsonic0:amd64
sudo apt-get install libsoundtouch0:amd64
sudo apt-get install libsoup-gnome2.4-1:amd64
sudo apt-get install libsoup2.4-1:amd64
sudo apt-get install libsource-highlight-common
sudo apt-get install libsource-highlight4
sudo apt-get install libsoxr0:amd64
sudo apt-get install libspandsp2
sudo apt-get install libspectre1:amd64
sudo apt-get install libspeechd2:amd64
sudo apt-get install libspeex1:amd64
sudo apt-get install libspeexdsp1:amd64
sudo apt-get install libspeexdsp1:i386
sudo apt-get install libspice-server1:amd64
sudo apt-get install libsqlite0
sudo apt-get install libsqlite3-0:amd64
sudo apt-get install libsqlite3-0:i386
sudo apt-get install libsrtp0
sudo apt-get install libss2:amd64
sudo apt-get install libssh2-1:amd64
sudo apt-get install libssl-dev:amd64
sudo apt-get install libssl-doc
sudo apt-get install libssl1.0.0:amd64
sudo apt-get install libssl1.0.0:i386
sudo apt-get install libstartup-notification0:amd64
sudo apt-get install libstdc++-4.8-dev:amd64
sudo apt-get install libstdc++6:amd64
sudo apt-get install libstdc++6:i386
sudo apt-get install libsub-identify-perl
sudo apt-get install libsub-name-perl
sudo apt-get install libswscale2:amd64
sudo apt-get install libsys-hostname-long-perl
sudo apt-get install libsystemd-daemon0:amd64
sudo apt-get install libsystemd-login0:amd64
sudo apt-get install libt1-5
sudo apt-get install libtag1-vanilla:amd64
sudo apt-get install libtag1c2a:amd64
sudo apt-get install libtagc0:amd64
sudo apt-get install libtalloc2:amd64
sudo apt-get install libtar0
sudo apt-get install libtasn1-6:amd64
sudo apt-get install libtasn1-6:i386
sudo apt-get install libtbb2
sudo apt-get install libtcl8.5:amd64
sudo apt-get install libtcl8.6:amd64
sudo apt-get install libtdb1:amd64
sudo apt-get install libtelepathy-glib0:amd64
sudo apt-get install libterm-ui-perl
sudo apt-get install libtevent0:amd64
sudo apt-get install libtext-charwidth-perl
sudo apt-get install libtext-iconv-perl
sudo apt-get install libtext-levenshtein-perl
sudo apt-get install libtext-soundex-perl
sudo apt-get install libtext-wrapi18n-perl
sudo apt-get install libthai-data
sudo apt-get install libthai0:amd64
sudo apt-get install libthai0:i386
sudo apt-get install libtheora0:amd64
sudo apt-get install libthunarx-2-0
sudo apt-get install libtidy-0.99-0
sudo apt-get install libtie-ixhash-perl
sudo apt-get install libtiff5:amd64
sudo apt-get install libtiff5:i386
sudo apt-get install libtimedate-perl
sudo apt-get install libtinfo5:amd64
sudo apt-get install libtinfo5:i386
sudo apt-get install libtinyxml2.6.2:amd64
sudo apt-get install libtk8.6:amd64
sudo apt-get install libtool
sudo apt-get install libtotem-plparser18
sudo apt-get install libts-0.0-0:amd64
sudo apt-get install libtsan0:amd64
sudo apt-get install libtumbler-1-0
sudo apt-get install libtwolame0
sudo apt-get install libtxc-dxtn-s2tc0:amd64
sudo apt-get install libtxc-dxtn-s2tc0:i386
sudo apt-get install libudev1:amd64
sudo apt-get install libudev1:i386
sudo apt-get install libudisks2-0:amd64
sudo apt-get install libumfpack5.6.2:amd64
sudo apt-get install libunique-1.0-0
sudo apt-get install libunique-3.0-0
sudo apt-get install libunistring0:amd64
sudo apt-get install libunity-protocol-private0:amd64
sudo apt-get install libunity-scopes-json-def-desktop
sudo apt-get install libunity9:amd64
sudo apt-get install libupnp6
sudo apt-get install libupower-glib1:amd64
sudo apt-get install liburi-perl
sudo apt-get install liburl-dispatcher1:amd64
sudo apt-get install libusageenvironment1
sudo apt-get install libusb-0.1-4:amd64
sudo apt-get install libusb-1.0-0:amd64
sudo apt-get install libusb-1.0-0:i386
sudo apt-get install libusbmuxd2
sudo apt-get install libuser1
sudo apt-get install libustr-1.0-1:amd64
sudo apt-get install libutempter0
sudo apt-get install libuuid-perl
sudo apt-get install libuuid1:amd64
sudo apt-get install libuuid1:i386
sudo apt-get install libv4l-0:amd64
sudo apt-get install libv4l-0:i386
sudo apt-get install libv4lconvert0:amd64
sudo apt-get install libv4lconvert0:i386
sudo apt-get install libva-x11-1:amd64
sudo apt-get install libva1:amd64
sudo apt-get install libvcdinfo0
sudo apt-get install libvdpau1:amd64
sudo apt-get install libvisual-0.4-0:amd64
sudo apt-get install libvisual-0.4-plugins:amd64
sudo apt-get install libvlc5
sudo apt-get install libvlccore7
sudo apt-get install libvo-aacenc0:amd64
sudo apt-get install libvo-amrwbenc0:amd64
sudo apt-get install libvorbis0a:amd64
sudo apt-get install libvorbis0a:i386
sudo apt-get install libvorbisenc2:amd64
sudo apt-get install libvorbisenc2:i386
sudo apt-get install libvorbisfile3:amd64
sudo apt-get install libvpx1:amd64
sudo apt-get install libvpx1:i386
sudo apt-get install libvte-2.90-9
sudo apt-get install libvte-2.90-common
sudo apt-get install libvte-common
sudo apt-get install libvte9
sudo apt-get install libwavpack1:amd64
sudo apt-get install libwayland-client0:amd64
sudo apt-get install libwayland-cursor0:amd64
sudo apt-get install libwayland-egl1-mesa:amd64
sudo apt-get install libwayland-server0:amd64
sudo apt-get install libwbclient0:amd64
sudo apt-get install libwebkitgtk-1.0-0:amd64
sudo apt-get install libwebkitgtk-1.0-common
sudo apt-get install libwebkitgtk-3.0-0:amd64
sudo apt-get install libwebkitgtk-3.0-common
sudo apt-get install libwebp5:amd64
sudo apt-get install libwebpmux1:amd64
sudo apt-get install libwhoopsie0
sudo apt-get install libwildmidi-config
sudo apt-get install libwildmidi1:amd64
sudo apt-get install libwind0-heimdal:amd64
sudo apt-get install libwind0-heimdal:i386
sudo apt-get install libwmf-bin
sudo apt-get install libwmf0.2-7:amd64
sudo apt-get install libwnck-3-0:amd64
sudo apt-get install libwnck-3-common
sudo apt-get install libwnck-common
sudo apt-get install libwnck22
sudo apt-get install libwpd-0.9-9
sudo apt-get install libwpg-0.2-2
sudo apt-get install libwps-0.2-2
sudo apt-get install libwrap0:amd64
sudo apt-get install libwrap0:i386
sudo apt-get install libwv-1.2-4:amd64
sudo apt-get install libwww-perl
sudo apt-get install libwww-robotrules-perl
sudo apt-get install libwxbase2.8-0:amd64
sudo apt-get install libwxgtk2.8-0:amd64
sudo apt-get install libx11-6:amd64
sudo apt-get install libx11-6:i386
sudo apt-get install libx11-data
sudo apt-get install libx11-xcb1:amd64
sudo apt-get install libx11-xcb1:i386
sudo apt-get install libx264-142:amd64
sudo apt-get install libx86-1:amd64
sudo apt-get install libxapian22
sudo apt-get install libxatracker2:amd64
sudo apt-get install libxau6:amd64
sudo apt-get install libxau6:i386
sudo apt-get install libxaw7:amd64
sudo apt-get install libxcb-composite0:amd64
sudo apt-get install libxcb-dri2-0:amd64
sudo apt-get install libxcb-dri2-0:i386
sudo apt-get install libxcb-dri3-0:amd64
sudo apt-get install libxcb-dri3-0:i386
sudo apt-get install libxcb-glx0:amd64
sudo apt-get install libxcb-glx0:i386
sudo apt-get install libxcb-icccm4:amd64
sudo apt-get install libxcb-image0:amd64
sudo apt-get install libxcb-keysyms1:amd64
sudo apt-get install libxcb-present0:amd64
sudo apt-get install libxcb-present0:i386
sudo apt-get install libxcb-randr0:amd64
sudo apt-get install libxcb-render-util0:amd64
sudo apt-get install libxcb-render0:amd64
sudo apt-get install libxcb-render0:i386
sudo apt-get install libxcb-shape0:amd64
sudo apt-get install libxcb-shm0:amd64
sudo apt-get install libxcb-shm0:i386
sudo apt-get install libxcb-sync1:amd64
sudo apt-get install libxcb-sync1:i386
sudo apt-get install libxcb-util0:amd64
sudo apt-get install libxcb-xfixes0:amd64
sudo apt-get install libxcb-xkb1:amd64
sudo apt-get install libxcb-xv0:amd64
sudo apt-get install libxcb1:amd64
sudo apt-get install libxcb1:i386
sudo apt-get install libxcomposite1:amd64
sudo apt-get install libxcomposite1:i386
sudo apt-get install libxcursor1:amd64
sudo apt-get install libxcursor1:i386
sudo apt-get install libxdamage1:amd64
sudo apt-get install libxdamage1:i386
sudo apt-get install libxdmcp6:amd64
sudo apt-get install libxdmcp6:i386
sudo apt-get install libxext6:amd64
sudo apt-get install libxext6:i386
sudo apt-get install libxfce4ui-1-0
sudo apt-get install libxfce4ui-2-0
sudo apt-get install libxfce4ui-common
sudo apt-get install libxfce4ui-utils
sudo apt-get install libxfce4util-bin
sudo apt-get install libxfce4util-common
sudo apt-get install libxfce4util6
sudo apt-get install libxfcegui4-4
sudo apt-get install libxfconf-0-2
sudo apt-get install libxfixes3:amd64
sudo apt-get install libxfixes3:i386
sudo apt-get install libxfont1:amd64
sudo apt-get install libxft2:amd64
sudo apt-get install libxi6:amd64
sudo apt-get install libxi6:i386
sudo apt-get install libxinerama1:amd64
sudo apt-get install libxinerama1:i386
sudo apt-get install libxkbcommon-x11-0:amd64
sudo apt-get install libxkbcommon0:amd64
sudo apt-get install libxkbfile1:amd64
sudo apt-get install libxklavier16
sudo apt-get install libxml-parser-perl
sudo apt-get install libxml-twig-perl
sudo apt-get install libxml-xpathengine-perl
sudo apt-get install libxml2:amd64
sudo apt-get install libxml2:i386
sudo apt-get install libxmu6:amd64
sudo apt-get install libxmuu1:amd64
sudo apt-get install libxp6:amd64
sudo apt-get install libxpm4:amd64
sudo apt-get install libxpm4:i386
sudo apt-get install libxrandr2:amd64
sudo apt-get install libxrandr2:i386
sudo apt-get install libxrender1:amd64
sudo apt-get install libxrender1:i386
sudo apt-get install libxres1:amd64
sudo apt-get install libxshmfence1:amd64
sudo apt-get install libxshmfence1:i386
sudo apt-get install libxslt1.1:amd64
sudo apt-get install libxslt1.1:i386
sudo apt-get install libxss1:amd64
sudo apt-get install libxt6:amd64
sudo apt-get install libxt6:i386
sudo apt-get install libxtables10
sudo apt-get install libxtst6:amd64
sudo apt-get install libxtst6:i386
sudo apt-get install libxv1:amd64
sudo apt-get install libxvidcore4:amd64
sudo apt-get install libxvmc1:amd64
sudo apt-get install libxxf86dga1:amd64
sudo apt-get install libxxf86vm1:amd64
sudo apt-get install libxxf86vm1:i386
sudo apt-get install libyajl2:amd64
sudo apt-get install libyaml-0-2:amd64
sudo apt-get install libyaml-tiny-perl
sudo apt-get install libyelp0
sudo apt-get install libzbar0
sudo apt-get install libzephyr4:amd64
sudo apt-get install libzip2
sudo apt-get install libzvbi-common
sudo apt-get install libzvbi0:amd64
sudo apt-get install light-locker
sudo apt-get install light-locker-settings
sudo apt-get install lightdm
sudo apt-get install lightdm-gtk-greeter
sudo apt-get install link-grammar-dictionaries-en
sudo apt-get install links2
sudo apt-get install lintian
sudo apt-get install linux-firmware
sudo apt-get install linux-headers-3.13.0-24
sudo apt-get install linux-headers-3.13.0-24-generic
sudo apt-get install linux-headers-3.13.0-44
sudo apt-get install linux-headers-3.13.0-44-generic
sudo apt-get install linux-headers-3.13.0-45
sudo apt-get install linux-headers-3.13.0-45-generic
sudo apt-get install linux-headers-3.13.0-46
sudo apt-get install linux-headers-3.13.0-46-generic
sudo apt-get install linux-headers-3.13.0-47
sudo apt-get install linux-headers-3.13.0-47-generic
sudo apt-get install linux-headers-3.13.0-48
sudo apt-get install linux-headers-3.13.0-48-generic
sudo apt-get install linux-headers-3.13.0-49
sudo apt-get install linux-headers-3.13.0-49-generic
sudo apt-get install linux-headers-generic
sudo apt-get install linux-image-3.13.0-24-generic
sudo apt-get install linux-image-extra-3.13.0-24-generic
sudo apt-get install linux-libc-dev:amd64
sudo apt-get install linux-sound-base
sudo apt-get install lm-sensors
sudo apt-get install locales
sudo apt-get install lockfile-progs
sudo apt-get install login
sudo apt-get install logrotate
sudo apt-get install lp-solve
sudo apt-get install lsb-base
sudo apt-get install lsb-release
sudo apt-get install lshw
sudo apt-get install lsof
sudo apt-get install ltrace
sudo apt-get install m4
sudo apt-get install make
sudo apt-get install makedev
sudo apt-get install man-db
sudo apt-get install manpages
sudo apt-get install manpages-dev
sudo apt-get install mariadb-client-5.5
sudo apt-get install mariadb-client-core-5.5
sudo apt-get install mariadb-common
sudo apt-get install mariadb-server
sudo apt-get install mariadb-server-5.5
sudo apt-get install mariadb-server-core-5.5
sudo apt-get install mawk
sudo apt-get install memtest86+
sudo apt-get install menu
sudo apt-get install menulibre
sudo apt-get install meocloud-gui
sudo apt-get install mesa-utils
sudo apt-get install mime-support
sudo apt-get install mlocate
sudo apt-get install mobile-broadband-provider-info
sudo apt-get install modemmanager
sudo apt-get install module-init-tools
sudo apt-get install mount
sudo apt-get install mountall
sudo apt-get install mousepad
sudo apt-get install mplayer2
sudo apt-get install mscompress
sudo apt-get install mtools
sudo apt-get install mtp-tools
sudo apt-get install mtpfs
sudo apt-get install mtr-tiny
sudo apt-get install mugshot
sudo apt-get install multiarch-support
sudo apt-get install mysql-common
sudo apt-get install mysql-workbench-community
sudo apt-get install nano
sudo apt-get install nautilus-data
sudo apt-get install ncurses-base
sudo apt-get install ncurses-bin
sudo apt-get install net-tools
sudo apt-get install netbase
sudo apt-get install netcat-openbsd
sudo apt-get install netpbm
sudo apt-get install network-manager
sudo apt-get install network-manager-gnome
sudo apt-get install network-manager-pptp
sudo apt-get install network-manager-pptp-gnome
sudo apt-get install nmap
sudo apt-get install nodejs
sudo apt-get install ntfs-3g
sudo apt-get install ntpdate
sudo apt-get install obex-data-server
sudo apt-get install ocl-icd-libopencl1:amd64
sudo apt-get install ocl-icd-libopencl1:i386
sudo apt-get install odbcinst
sudo apt-get install odbcinst1debian2:amd64
sudo apt-get install onboard
sudo apt-get install onboard-data
sudo apt-get install oneconf
sudo apt-get install oneconf-common
sudo apt-get install openprinting-ppds
sudo apt-get install openssh-client
sudo apt-get install openssl
sudo apt-get install oracle-java7-installer
sudo apt-get install oracle-java7-set-default
sudo apt-get install oracle-jdk7-installer
sudo apt-get install os-prober
sudo apt-get install oxideqt-codecs-extra:amd64
sudo apt-get install p11-kit
sudo apt-get install p11-kit-modules:amd64
sudo apt-get install p11-kit-modules:i386
sudo apt-get install p7zip
sudo apt-get install p7zip-full
sudo apt-get install parole
sudo apt-get install parted
sudo apt-get install passwd
sudo apt-get install pastebinit
sudo apt-get install patch
sudo apt-get install patchutils
sudo apt-get install pavucontrol
sudo apt-get install pciutils
sudo apt-get install pcmciautils
sudo apt-get install perl
sudo apt-get install perl-base
sudo apt-get install perl-modules
sudo apt-get install perlmagick
sudo apt-get install php-doc
sudo apt-get install php-pear
sudo apt-get install php5-cli
sudo apt-get install php5-common
sudo apt-get install php5-curl
sudo apt-get install php5-dev
sudo apt-get install php5-gd
sudo apt-get install php5-imagick
sudo apt-get install php5-json
sudo apt-get install php5-mcrypt
sudo apt-get install php5-mysql
sudo apt-get install php5-readline
sudo apt-get install php5-sqlite
sudo apt-get install pidgin
sudo apt-get install pidgin-data
sudo apt-get install pidgin-libnotify
sudo apt-get install pidgin-otr
sudo apt-get install pkg-config
sudo apt-get install pkg-php-tools
sudo apt-get install plymouth
sudo apt-get install plymouth-label
sudo apt-get install plymouth-theme-ubuntu-text
sudo apt-get install plymouth-theme-xubuntu-logo
sudo apt-get install plymouth-theme-xubuntu-text
sudo apt-get install pm-utils
sudo apt-get install po-debconf
sudo apt-get install policykit-1
sudo apt-get install policykit-1-gnome
sudo apt-get install policykit-desktop-privileges
sudo apt-get install poppler-data
sudo apt-get install poppler-utils
sudo apt-get install popularity-contest
sudo apt-get install powermgmt-base
sudo apt-get install ppp
sudo apt-get install pppconfig
sudo apt-get install pppoeconf
sudo apt-get install pptp-linux
sudo apt-get install preload
sudo apt-get install printer-driver-c2esp
sudo apt-get install printer-driver-foo2zjs
sudo apt-get install printer-driver-foo2zjs-common
sudo apt-get install printer-driver-gutenprint
sudo apt-get install printer-driver-hpcups
sudo apt-get install printer-driver-min12xxw
sudo apt-get install printer-driver-pnm2ppa
sudo apt-get install printer-driver-postscript-hp
sudo apt-get install printer-driver-ptouch
sudo apt-get install printer-driver-pxljr
sudo apt-get install printer-driver-sag-gdi
sudo apt-get install printer-driver-splix
sudo apt-get install procps
sudo apt-get install psmisc
sudo apt-get install pulseaudio
sudo apt-get install pulseaudio-module-x11
sudo apt-get install pulseaudio-utils
sudo apt-get install python
sudo apt-get install python-apt
sudo apt-get install python-apt-common
sudo apt-get install python-aptdaemon
sudo apt-get install python-aptdaemon.gtk3widgets
sudo apt-get install python-cairo
sudo apt-get install python-chardet
sudo apt-get install python-commandnotfound
sudo apt-get install python-compizconfig
sudo apt-get install python-crypto
sudo apt-get install python-cups
sudo apt-get install python-cupshelpers
sudo apt-get install python-dbus
sudo apt-get install python-dbus-dev
sudo apt-get install python-debian
sudo apt-get install python-debtagshw
sudo apt-get install python-defer
sudo apt-get install python-dirspec
sudo apt-get install python-dnspython
sudo apt-get install python-gconf
sudo apt-get install python-gdbm
sudo apt-get install python-gi
sudo apt-get install python-gi-cairo
sudo apt-get install python-gnome2
sudo apt-get install python-gnomekeyring
sudo apt-get install python-gobject
sudo apt-get install python-gobject-2
sudo apt-get install python-gtk2
sudo apt-get install python-httplib2
sudo apt-get install python-imaging
sudo apt-get install python-kaa-base
sudo apt-get install python-kaa-metadata
sudo apt-get install python-keybinder
sudo apt-get install python-ldb
sudo apt-get install python-libxml2
sudo apt-get install python-lxml
sudo apt-get install python-mako
sudo apt-get install python-markupsafe
sudo apt-get install python-minimal
sudo apt-get install python-nautilus
sudo apt-get install python-netifaces
sudo apt-get install python-notify
sudo apt-get install python-ntdb
sudo apt-get install python-numpy
sudo apt-get install python-oauthlib
sudo apt-get install python-oneconf
sudo apt-get install python-openssl
sudo apt-get install python-pam
sudo apt-get install python-paramiko
sudo apt-get install python-pexpect
sudo apt-get install python-pil
sudo apt-get install python-piston-mini-client
sudo apt-get install python-pkg-resources
sudo apt-get install python-psutil
sudo apt-get install python-pycurl
sudo apt-get install python-pyorbit
sudo apt-get install python-qt4
sudo apt-get install python-qt4-dbus
sudo apt-get install python-renderpm
sudo apt-get install python-reportlab
sudo apt-get install python-reportlab-accel
sudo apt-get install python-requests
sudo apt-get install python-samba
sudo apt-get install python-serial
sudo apt-get install python-setproctitle
sudo apt-get install python-sip
sudo apt-get install python-six
sudo apt-get install python-smbc
sudo apt-get install python-sqlite
sudo apt-get install python-support
sudo apt-get install python-talloc
sudo apt-get install python-tdb
sudo apt-get install python-tk
sudo apt-get install python-twisted-bin
sudo apt-get install python-twisted-core
sudo apt-get install python-twisted-web
sudo apt-get install python-ubuntu-sso-client
sudo apt-get install python-urllib3
sudo apt-get install python-urwid
sudo apt-get install python-vte
sudo apt-get install python-xapian
sudo apt-get install python-xdg
sudo apt-get install python-zope.interface
sudo apt-get install python2.7
sudo apt-get install python2.7-minimal
sudo apt-get install python3
sudo apt-get install python3-apport
sudo apt-get install python3-apt
sudo apt-get install python3-aptdaemon
sudo apt-get install python3-aptdaemon.gtk3widgets
sudo apt-get install python3-aptdaemon.pkcompat
sudo apt-get install python3-cairo
sudo apt-get install python3-chardet
sudo apt-get install python3-commandnotfound
sudo apt-get install python3-crypto
sudo apt-get install python3-dbus
sudo apt-get install python3-debian
sudo apt-get install python3-defer
sudo apt-get install python3-distupgrade
sudo apt-get install python3-gdbm:amd64
sudo apt-get install python3-gi
sudo apt-get install python3-gi-cairo
sudo apt-get install python3-httplib2
sudo apt-get install python3-minimal
sudo apt-get install python3-oauthlib
sudo apt-get install python3-oneconf
sudo apt-get install python3-pexpect
sudo apt-get install python3-piston-mini-client
sudo apt-get install python3-pkg-resources
sudo apt-get install python3-problem-report
sudo apt-get install python3-psutil
sudo apt-get install python3-pycurl
sudo apt-get install python3-six
sudo apt-get install python3-software-properties
sudo apt-get install python3-uno
sudo apt-get install python3-update-manager
sudo apt-get install python3-xdg
sudo apt-get install python3-xkit
sudo apt-get install python3.4
sudo apt-get install python3.4-minimal
sudo apt-get install qdbus
sudo apt-get install qpdf
sudo apt-get install qtchooser
sudo apt-get install qtcore4-l10n
sudo apt-get install rar
sudo apt-get install rarian-compat
sudo apt-get install readline-common
sudo apt-get install resolvconf
sudo apt-get install rfkill
sudo apt-get install ristretto
sudo apt-get install rlwrap
sudo apt-get install rpm
sudo apt-get install rpm-common
sudo apt-get install rpm2cpio
sudo apt-get install rsync
sudo apt-get install rsyslog
sudo apt-get install rtkit
sudo apt-get install rtmpdump
sudo apt-get install ruby
sudo apt-get install ruby1.9.1
sudo apt-get install samba
sudo apt-get install samba-common
sudo apt-get install samba-common-bin
sudo apt-get install samba-dsdb-modules
sudo apt-get install samba-libs:amd64
sudo apt-get install samba-vfs-modules
sudo apt-get install sane-utils
sudo apt-get install sed
sudo apt-get install sensible-utils
sudo apt-get install sessioninstaller
sudo apt-get install sgml-base
sudo apt-get install sgml-data
sudo apt-get install shared-mime-info
sudo apt-get install shimmer-themes
sudo apt-get install shtool
sudo apt-get install simple-scan
sudo apt-get install smartgit
sudo apt-get install smartmontools
sudo apt-get install smbclient
sudo apt-get install software-center
sudo apt-get install software-center-aptdaemon-plugins
sudo apt-get install software-properties-common
sudo apt-get install software-properties-gtk
sudo apt-get install sound-theme-freedesktop
sudo apt-get install source-highlight
sudo apt-get install speech-dispatcher
sudo apt-get install speech-dispatcher-audio-plugins:amd64
sudo apt-get install speedometer
sudo apt-get install sqldeveloper
sudo apt-get install sqlite
sudo apt-get install sqlite3
sudo apt-get install sqliteman
sudo apt-get install sqliteman-doc
sudo apt-get install ssl-cert
sudo apt-get install steam
sudo apt-get install strace
sudo apt-get install subdownloader
sudo apt-get install sublime-text-installer
sudo apt-get install sudo
sudo apt-get install synaptic
sudo apt-get install synergy
sudo apt-get install syslinux
sudo apt-get install syslinux-common
sudo apt-get install syslinux-legacy
sudo apt-get install syslinux-themes-debian
sudo apt-get install syslinux-themes-debian-wheezy
sudo apt-get install system-config-printer-common
sudo apt-get install system-config-printer-gnome
sudo apt-get install system-config-printer-udev
sudo apt-get install system-tools-backends
sudo apt-get install systemd-services
sudo apt-get install systemd-shim
sudo apt-get install sysv-rc
sudo apt-get install sysvinit-utils
sudo apt-get install t1utils
sudo apt-get install tar
sudo apt-get install tcl
sudo apt-get install tcl8.5
sudo apt-get install tcl8.6
sudo apt-get install tcpd
sudo apt-get install tcpdump
sudo apt-get install tcptrack
sudo apt-get install tdb-tools
sudo apt-get install teamviewer
sudo apt-get install telnet
sudo apt-get install terminator
sudo apt-get install thunar
sudo apt-get install thunar-archive-plugin
sudo apt-get install thunar-data
sudo apt-get install thunar-dropbox-plugin:amd64
sudo apt-get install thunar-media-tags-plugin
sudo apt-get install thunar-volman
sudo apt-get install thunderbird
sudo apt-get install thunderbird-locale-en
sudo apt-get install thunderbird-locale-en-gb
sudo apt-get install thunderbird-locale-en-us
sudo apt-get install thunderbird-locale-pt
sudo apt-get install thunderbird-locale-pt-br
sudo apt-get install thunderbird-locale-pt-pt
sudo apt-get install time
sudo apt-get install tk
sudo apt-get install tk8.6
sudo apt-get install toshset
sudo apt-get install transfig
sudo apt-get install transmission-common
sudo apt-get install transmission-gtk
sudo apt-get install tsconf
sudo apt-get install ttf-dejavu-core
sudo apt-get install ttf-indic-fonts-core
sudo apt-get install ttf-mscorefonts-installer
sudo apt-get install ttf-punjabi-fonts
sudo apt-get install ttf-ubuntu-font-family
sudo apt-get install ttf-wqy-microhei
sudo apt-get install tumbler
sudo apt-get install tumbler-common
sudo apt-get install tzdata
sudo apt-get install ubuntu-drivers-common
sudo apt-get install ubuntu-extras-keyring
sudo apt-get install ubuntu-keyring
sudo apt-get install ubuntu-minimal
sudo apt-get install ubuntu-release-upgrader-core
sudo apt-get install ubuntu-release-upgrader-gtk
sudo apt-get install ubuntu-restricted-addons
sudo apt-get install ubuntu-sso-client
sudo apt-get install ubuntu-standard
sudo apt-get install ubuntu-tweak
sudo apt-get install ucf
sudo apt-get install udev
sudo apt-get install udisks2
sudo apt-get install ufw
sudo apt-get install unattended-upgrades
sudo apt-get install unetbootin
sudo apt-get install unetbootin-translations
sudo apt-get install unixodbc
sudo apt-get install uno-libs3
sudo apt-get install unrar
sudo apt-get install unzip
sudo apt-get install update-inetd
sudo apt-get install update-manager
sudo apt-get install update-manager-core
sudo apt-get install update-notifier
sudo apt-get install update-notifier-common
sudo apt-get install upower
sudo apt-get install upstart
sudo apt-get install ure
sudo apt-get install ureadahead
sudo apt-get install usb-creator-common
sudo apt-get install usb-creator-gtk
sudo apt-get install usb-modeswitch
sudo apt-get install usb-modeswitch-data
sudo apt-get install usbmuxd
sudo apt-get install usbutils
sudo apt-get install usermode
sudo apt-get install util-linux
sudo apt-get install uuid-runtime
sudo apt-get install vbaexpress
sudo apt-get install vbetool
sudo apt-get install vim-common
sudo apt-get install vim-gnome
sudo apt-get install vim-gui-common
sudo apt-get install vim-runtime
sudo apt-get install vim-tiny
sudo apt-get install virtualbox-4.3
sudo apt-get install visualboyadvance
sudo apt-get install vlc
sudo apt-get install vlc-data
sudo apt-get install vlc-nox
sudo apt-get install vlc-plugin-notify
sudo apt-get install vlc-plugin-pulse
sudo apt-get install w3m
sudo apt-get install w3m-img
sudo apt-get install wamerican
sudo apt-get install wbrazilian
sudo apt-get install wbritish
sudo apt-get install wget
sudo apt-get install whiptail
sudo apt-get install whois
sudo apt-get install whoopsie
sudo apt-get install winbind
sudo apt-get install wine
sudo apt-get install wine-gecko2.21:amd64
sudo apt-get install wine-gecko2.21:i386
sudo apt-get install wine-mono0.0.8
sudo apt-get install wine1.6
sudo apt-get install wine1.6-amd64
sudo apt-get install wine1.6-i386
sudo apt-get install winetricks
sudo apt-get install wireless-regdb
sudo apt-get install wireless-tools
sudo apt-get install wodim
sudo apt-get install wpasupplicant
sudo apt-get install wportuguese
sudo apt-get install x11-apps
sudo apt-get install x11-common
sudo apt-get install x11-session-utils
sudo apt-get install x11-utils
sudo apt-get install x11-xfs-utils
sudo apt-get install x11-xkb-utils
sudo apt-get install x11-xserver-utils
sudo apt-get install xauth
sudo apt-get install xbitmaps
sudo apt-get install xbrlapi
sudo apt-get install xchat
sudo apt-get install xchat-common
sudo apt-get install xchat-indicator
sudo apt-get install xcursor-themes
sudo apt-get install xdg-user-dirs
sudo apt-get install xdg-user-dirs-gtk
sudo apt-get install xdg-utils
sudo apt-get install xfburn
sudo apt-get install xfce4-appfinder
sudo apt-get install xfce4-cpugraph-plugin
sudo apt-get install xfce4-dict
sudo apt-get install xfce4-indicator-plugin
sudo apt-get install xfce4-mailwatch-plugin
sudo apt-get install xfce4-netload-plugin
sudo apt-get install xfce4-notes
sudo apt-get install xfce4-notes-plugin
sudo apt-get install xfce4-notifyd
sudo apt-get install xfce4-panel
sudo apt-get install xfce4-places-plugin
sudo apt-get install xfce4-power-manager
sudo apt-get install xfce4-power-manager-data
sudo apt-get install xfce4-quicklauncher-plugin
sudo apt-get install xfce4-screenshooter
sudo apt-get install xfce4-session
sudo apt-get install xfce4-settings
sudo apt-get install xfce4-systemload-plugin
sudo apt-get install xfce4-taskmanager
sudo apt-get install xfce4-terminal
sudo apt-get install xfce4-verve-plugin
sudo apt-get install xfce4-volumed
sudo apt-get install xfce4-weather-plugin
sudo apt-get install xfce4-whiskermenu-plugin
sudo apt-get install xfce4-xkb-plugin
sudo apt-get install xfconf
sudo apt-get install xfdesktop4
sudo apt-get install xfdesktop4-data
sudo apt-get install xfonts-base
sudo apt-get install xfonts-encodings
sudo apt-get install xfonts-mathml
sudo apt-get install xfonts-scalable
sudo apt-get install xfonts-utils
sudo apt-get install xfwm4
sudo apt-get install xinit
sudo apt-get install xinput
sudo apt-get install xkb-data
sudo apt-get install xml-core
sudo apt-get install xorg
sudo apt-get install xorg-docs-core
sudo apt-get install xserver-common
sudo apt-get install xserver-xorg
sudo apt-get install xserver-xorg-core
sudo apt-get install xserver-xorg-input-all
sudo apt-get install xserver-xorg-input-evdev
sudo apt-get install xserver-xorg-input-mouse
sudo apt-get install xserver-xorg-input-synaptics
sudo apt-get install xserver-xorg-input-vmmouse
sudo apt-get install xserver-xorg-input-wacom
sudo apt-get install xserver-xorg-video-all
sudo apt-get install xserver-xorg-video-ati
sudo apt-get install xserver-xorg-video-cirrus
sudo apt-get install xserver-xorg-video-fbdev
sudo apt-get install xserver-xorg-video-glamoregl
sudo apt-get install xserver-xorg-video-intel
sudo apt-get install xserver-xorg-video-mach64
sudo apt-get install xserver-xorg-video-mga
sudo apt-get install xserver-xorg-video-modesetting
sudo apt-get install xserver-xorg-video-neomagic
sudo apt-get install xserver-xorg-video-nouveau
sudo apt-get install xserver-xorg-video-openchrome
sudo apt-get install xserver-xorg-video-qxl
sudo apt-get install xserver-xorg-video-r128
sudo apt-get install xserver-xorg-video-radeon
sudo apt-get install xserver-xorg-video-s3
sudo apt-get install xserver-xorg-video-savage
sudo apt-get install xserver-xorg-video-siliconmotion
sudo apt-get install xserver-xorg-video-sis
sudo apt-get install xserver-xorg-video-sisusb
sudo apt-get install xserver-xorg-video-tdfx
sudo apt-get install xserver-xorg-video-trident
sudo apt-get install xserver-xorg-video-vesa
sudo apt-get install xserver-xorg-video-vmware
sudo apt-get install xterm
sudo apt-get install xubuntu-artwork
sudo apt-get install xubuntu-community-wallpapers
sudo apt-get install xubuntu-default-settings
sudo apt-get install xubuntu-desktop
sudo apt-get install xubuntu-docs
sudo apt-get install xubuntu-icon-theme
sudo apt-get install xubuntu-restricted-addons
sudo apt-get install xubuntu-restricted-extras
sudo apt-get install xubuntu-wallpapers
sudo apt-get install xul-ext-ubufox
sudo apt-get install xz-utils
sudo apt-get install yelp
sudo apt-get install yelp-xsl
sudo apt-get install youtube-dl
sudo apt-get install zenity
sudo apt-get install zenity-common
sudo apt-get install zip
sudo apt-get install zlib1g:amd64
sudo apt-get install zlib1g:i386
sudo apt-get install zlib1g-dev:amd64
sudo apt-get install zram-config
sudo apt-get install zsnes
