sudo apt-get install -y --force-yes adduser
sudo apt-get install -y --force-yes agave
sudo apt-get install -y --force-yes aircrack-ng
sudo apt-get install -y --force-yes alien
sudo apt-get install -y --force-yes alsa-base
sudo apt-get install -y --force-yes alsa-utils
sudo apt-get install -y --force-yes arj
sudo apt-get install -y --force-yes atom
sudo apt-get install -y --force-yes audacious
sudo apt-get install -y --force-yes audacious-plugins
sudo apt-get install -y --force-yes autoconf
sudo apt-get install -y --force-yes automake
sudo apt-get install -y --force-yes baobab
sudo apt-get install -y --force-yes bc
sudo apt-get install -y --force-yes brackets
sudo apt-get install -y --force-yes brasero
sudo apt-get install -y --force-yes brasero-cdrkit
sudo apt-get install -y --force-yes brasero-common
sudo apt-get install -y --force-yes build-essential
sudo apt-get install -y --force-yes bum
sudo apt-get install -y --force-yes bzip2
sudo apt-get install -y --force-yes ca-certificates
sudo apt-get install -y --force-yes cdparanoia
sudo apt-get install -y --force-yes cdtool
sudo apt-get install -y --force-yes cheese
sudo apt-get install -y --force-yes copy
sudo apt-get install -y --force-yes cpp
sudo apt-get install -y --force-yes curl
sudo apt-get install -y --force-yes dialog
sudo apt-get install -y --force-yes dkms
sudo apt-get install -y --force-yes dpkg-repack
sudo apt-get install -y --force-yes dropbox
sudo apt-get install -y --force-yes easymp3gain-data
sudo apt-get install -y --force-yes easymp3gain-gtk
sudo apt-get install -y --force-yes easytag
sudo apt-get install -y --force-yes ed
sudo apt-get install -y --force-yes eject
sudo apt-get install -y --force-yes file-roller
sudo apt-get install -y --force-yes filezilla
sudo apt-get install -y --force-yes firefox
sudo apt-get install -y --force-yes firefox-locale-pt
sudo apt-get install -y --force-yes flac
sudo apt-get install -y --force-yes flashplugin-installer
sudo apt-get install -y --force-yes g++
sudo apt-get install -y --force-yes gawk
sudo apt-get install -y --force-yes gcc
sudo apt-get install -y --force-yes gdebi
sudo apt-get install -y --force-yes gdisk
sudo apt-get install -y --force-yes gigolo
sudo apt-get install -y --force-yes gimp
sudo apt-get install -y --force-yes git
sudo apt-get install -y --force-yes git-flow
sudo apt-get install -y --force-yes git-gui
sudo apt-get install -y --force-yes git-man
sudo apt-get install -y --force-yes gitk
sudo apt-get install -y --force-yes gkrellm
sudo apt-get install -y --force-yes gksu
sudo apt-get install -y --force-yes gksudo
sudo apt-get install -y --force-yes gnome-disk-utility
sudo apt-get install -y --force-yes gnome-nettool
sudo apt-get install -y --force-yes gnome-sudoku
sudo apt-get install -y --force-yes gnome-system-log
sudo apt-get install -y --force-yes gnome-system-monitor
sudo apt-get install -y --force-yes gnome-system-tools
sudo apt-get install -y --force-yes gnome-user-guide
sudo apt-get install -y --force-yes gnomine
sudo apt-get install -y --force-yes google-chrome-stable
sudo apt-get install -y --force-yes google-talkplugin
sudo apt-get install -y --force-yes gpart
sudo apt-get install -y --force-yes gparted
sudo apt-get install -y --force-yes grdesktop
sudo apt-get install -y --force-yes grep
sudo apt-get install -y --force-yes gshutdown
sudo apt-get install -y --force-yes gufw
sudo apt-get install -y --force-yes gzip
sudo apt-get install -y --force-yes hddtemp
sudo apt-get install -y --force-yes hdparm
sudo apt-get install -y --force-yes htop
sudo apt-get install -y --force-yes i2c-tools
sudo apt-get install -y --force-yes iftop
sudo apt-get install -y --force-yes ifupdown
sudo apt-get install -y --force-yes imagemagick
sudo apt-get install -y --force-yes indicator-keylock
sudo apt-get install -y --force-yes indicator-sysmonitor
sudo apt-get install -y --force-yes indicator-virtual-box
sudo apt-get install -y --force-yes inkscape
sudo apt-get install -y --force-yes iproute
sudo apt-get install -y --force-yes iproute2
sudo apt-get install -y --force-yes iptables
sudo apt-get install -y --force-yes jupiter
sudo apt-get install -y --force-yes keyboard-configuration
sudo apt-get install -y --force-yes lame
sudo apt-get install -y --force-yes laptop-detect
sudo apt-get install -y --force-yes less
sudo apt-get install -y --force-yes libaio1
sudo apt-get install -y --force-yes libreoffice-base-core
sudo apt-get install -y --force-yes libreoffice-calc
sudo apt-get install -y --force-yes libreoffice-draw
sudo apt-get install -y --force-yes libreoffice-help-pt-br
sudo apt-get install -y --force-yes libreoffice-impress
sudo apt-get install -y --force-yes libreoffice-l10n-pt-br
sudo apt-get install -y --force-yes libreoffice-math
sudo apt-get install -y --force-yes libreoffice-pdfimport
sudo apt-get install -y --force-yes libreoffice-writer
sudo apt-get install -y --force-yes lightdm
sudo apt-get install -y --force-yes lightdm-gtk-greeter
sudo apt-get install -y --force-yes lightdm-gtk-greeter-settings
sudo apt-get install -y --force-yes links2
sudo apt-get install -y --force-yes lm-sensors
sudo apt-get install -y --force-yes lshw
sudo apt-get install -y --force-yes lsof
sudo apt-get install -y --force-yes ltrace
sudo apt-get install -y --force-yes lzip
sudo apt-get install -y --force-yes lzma
sudo apt-get install -y --force-yes lzop
sudo apt-get install -y --force-yes m4
sudo apt-get install -y --force-yes make
sudo apt-get install -y --force-yes makedev
sudo apt-get install -y --force-yes mariadb-client-5.5
sudo apt-get install -y --force-yes mariadb-server-5.5
sudo apt-get install -y --force-yes mawk
sudo apt-get install -y --force-yes mc
sudo apt-get install -y --force-yes megasync
sudo apt-get install -y --force-yes meld
sudo apt-get install -y --force-yes meocloud-gui
sudo apt-get install -y --force-yes mercurial
sudo apt-get install -y --force-yes mergelog
sudo apt-get install -y --force-yes mousepad
sudo apt-get install -y --force-yes mp3gain
sudo apt-get install -y --force-yes mpg321
sudo apt-get install -y --force-yes mysql-workbench-community
sudo apt-get install -y --force-yes nano
sudo apt-get install -y --force-yes nmap
sudo apt-get install -y --force-yes nodejs
sudo apt-get install -y --force-yes ntfs-3g
sudo apt-get install -y --force-yes ntfs-config
sudo apt-get install -y --force-yes ntp
sudo apt-get install -y --force-yes openssh-client
sudo apt-get install -y --force-yes openssh-server
sudo apt-get install -y --force-yes openssl
sudo apt-get install -y --force-yes openvpn
sudo apt-get install -y --force-yes oracle-java7-installer
sudo apt-get install -y --force-yes oracle-java7-set-default
sudo apt-get install -y --force-yes oracle-jdk7-installer
sudo apt-get install -y --force-yes p7zip
sudo apt-get install -y --force-yes p7zip-full
sudo apt-get install -y --force-yes parole
sudo apt-get install -y --force-yes parted
sudo apt-get install -y --force-yes perl
sudo apt-get install -y --force-yes php-db
sudo apt-get install -y --force-yes php-doc
sudo apt-get install -y --force-yes php-pear
sudo apt-get install -y --force-yes php5-cli
sudo apt-get install -y --force-yes php5-curl
sudo apt-get install -y --force-yes php5-dev
sudo apt-get install -y --force-yes php5-gd
sudo apt-get install -y --force-yes php5-imagick
sudo apt-get install -y --force-yes php5-json
sudo apt-get install -y --force-yes php5-mcrypt
sudo apt-get install -y --force-yes php5-mysql
sudo apt-get install -y --force-yes php5-pgsql
sudo apt-get install -y --force-yes php5-readline
sudo apt-get install -y --force-yes php5-sqlite
sudo apt-get install -y --force-yes pidgin
sudo apt-get install -y --force-yes pomodoro-indicator
sudo apt-get install -y --force-yes preload
sudo apt-get install -y --force-yes psensor
sudo apt-get install -y --force-yes python
sudo apt-get install -y --force-yes rar
sudo apt-get install -y --force-yes ripperx
sudo apt-get install -y --force-yes rlwrap
sudo apt-get install -y --force-yes smartgit
sudo apt-get install -y --force-yes speedometer
sudo apt-get install -y --force-yes spotify-client
sudo apt-get install -y --force-yes sqldeveloper
sudo apt-get install -y --force-yes sqlite
sudo apt-get install -y --force-yes sqlite3
sudo apt-get install -y --force-yes sqliteman
sudo apt-get install -y --force-yes sqliteman-doc
sudo apt-get install -y --force-yes sqlmap
sudo apt-get install -y --force-yes steam
sudo apt-get install -y --force-yes subdownloader
sudo apt-get install -y --force-yes sublime-text-installer
sudo apt-get install -y --force-yes sudo
sudo apt-get install -y --force-yes synaptic
sudo apt-get install -y --force-yes synergy
sudo apt-get install -y --force-yes tar
sudo apt-get install -y --force-yes tcpdump
sudo apt-get install -y --force-yes tcptrack
sudo apt-get install -y --force-yes teamviewer
sudo apt-get install -y --force-yes terminator
sudo apt-get install -y --force-yes thunar-dropbox-plugin
sudo apt-get install -y --force-yes traceroute
sudo apt-get install -y --force-yes transmission
sudo apt-get install -y --force-yes udisks2
sudo apt-get install -y --force-yes ufw
sudo apt-get install -y --force-yes unrar
sudo apt-get install -y --force-yes unzip
sudo apt-get install -y --force-yes usb-creator
sudo apt-get install -y --force-yes virtualbox-5.0
sudo apt-get install -y --force-yes visualboyadvance
sudo apt-get install -y --force-yes vlc
sudo apt-get install -y --force-yes wget
sudo apt-get install -y --force-yes wine
sudo apt-get install -y --force-yes winetricks
sudo apt-get install -y --force-yes xchat
sudo apt-get install -y --force-yes xinput
sudo apt-get install -y --force-yes xrdp
sudo apt-get install -y --force-yes xubuntu-wallpapers
sudo apt-get install -y --force-yes youtube-dl
sudo apt-get install -y --force-yes youtube-dlg
sudo apt-get install -y --force-yes zip
sudo apt-get install -y --force-yes zram-config
sudo apt-get install -y --force-yes zsnes
