export ORACLE_BASE=/opt/oracle
export ORACLE_HOME=$ORACLE_BASE/instantclient
export TNS_ADMIN=$ORACLE_HOME/network/admin

#export NLS_LANG=`$ORACLE_HOME/bin/nls_lang.sh`
export NLS_LANG="BRAZILIAN PORTUGUESE_BRAZIL.UTF8"
export NLS_CHARACTERSET="UTF8"
export NLS_NCHAR_CHARACTERSET="AL32UTF8"
export NLS_DATE_FORMAT="DD/MM/YYYY HH24:MI:SS"


export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$ORACLE_HOME/lib
export PATH=$PATH:$ORACLE_HOME
