sudo apt-get -f -y purge libgl1-mesa-dri-lts-quantal
sudo apt-get -f -y purge libgl1-mesa-glx-lts-quantal
sudo apt-get -f -y purge libglapi-mesa-lts-quantal
sudo apt-get -f -y purge libxatracker1-lts-quantal
sudo apt-get -f -y purge linux-generic-lts-quantal
sudo apt-get -f -y purge linux-headers-generic-lts-quantal
sudo apt-get -f -y purge linux-image-generic-lts-quantal
sudo apt-get -f -y purge x11-xserver-utils-lts-quantal
sudo apt-get -f -y purge xserver-common-lts-quantal
sudo apt-get -f -y purge xserver-xorg-core-lts-quantal
sudo apt-get -f -y purge xserver-xorg-lts-quantal
sudo apt-get -f -y purge xserver-xorg-video-intel-lts-quantal
sudo apt-get -f -y purge xserver-xorg-video-openchrome-lts-quantal
sudo apt-get -f -y purge xserver-xorg-video-vmware-lts-quantal
