sudo apt-get install accountsservice
sudo apt-get install acl
sudo apt-get install acpi-support
sudo apt-get install acpid
sudo apt-get install activity-log-manager-common
sudo apt-get install activity-log-manager-control-center
sudo apt-get install adduser
sudo apt-get install adium-theme-ubuntu
sudo apt-get install aisleriot
sudo apt-get install alsa-base
sudo apt-get install alsa-utils
sudo apt-get install anacron
sudo apt-get install apg
sudo apt-get install app-install-data
sudo apt-get install app-install-data-partner
sudo apt-get install apparmor
sudo apt-get install appmenu-gtk
sudo apt-get install appmenu-gtk3
sudo apt-get install appmenu-qt
sudo apt-get install apport
sudo apt-get install apport-gtk
sudo apt-get install apport-symptoms
sudo apt-get install apt
sudo apt-get install apt-transport-https
sudo apt-get install apt-utils
sudo apt-get install apt-xapian-index
sudo apt-get install aptdaemon
sudo apt-get install aptdaemon-data
sudo apt-get install apturl
sudo apt-get install apturl-common
sudo apt-get install aspell
sudo apt-get install aspell-en
sudo apt-get install at
sudo apt-get install at-spi2-core
sudo apt-get install avahi-autoipd
sudo apt-get install avahi-daemon
sudo apt-get install avahi-utils
sudo apt-get install bamfdaemon
sudo apt-get install baobab
sudo apt-get install base-files
sudo apt-get install base-passwd
sudo apt-get install bash
sudo apt-get install bash-completion
sudo apt-get install bc
sudo apt-get install bind9-host
sudo apt-get install binutils
sudo apt-get install bluez
sudo apt-get install bluez-alsa
sudo apt-get install bluez-cups
sudo apt-get install bluez-gstreamer
sudo apt-get install branding-ubuntu
sudo apt-get install brasero
sudo apt-get install brasero-cdrkit
sudo apt-get install brasero-common
sudo apt-get install brltty
sudo apt-get install bsdmainutils
sudo apt-get install bsdutils
sudo apt-get install busybox-initramfs
sudo apt-get install busybox-static
sudo apt-get install bzip2
sudo apt-get install ca-certificates
sudo apt-get install checkbox
sudo apt-get install checkbox-qt
sudo apt-get install cmap-adobe-japan2
sudo apt-get install colord
sudo apt-get install command-not-found
sudo apt-get install command-not-found-data
sudo apt-get install compiz
sudo apt-get install compiz-core
sudo apt-get install compiz-gnome
sudo apt-get install compiz-plugins-default
sudo apt-get install compiz-plugins-main-default
sudo apt-get install compizconfig-backend-gconf
sudo apt-get install console-setup
sudo apt-get install consolekit
sudo apt-get install coreutils
sudo apt-get install cpio
sudo apt-get install cpp
sudo apt-get install cpp-4.6
sudo apt-get install crda
sudo apt-get install cron
sudo apt-get install cryptsetup-bin
sudo apt-get install cups
sudo apt-get install cups-bsd
sudo apt-get install cups-client
sudo apt-get install cups-common
sudo apt-get install cups-filters
sudo apt-get install cups-ppdc
sudo apt-get install dash
sudo apt-get install dbus
sudo apt-get install dbus-x11
sudo apt-get install dc
sudo apt-get install dconf-gsettings-backend
sudo apt-get install dconf-service
sudo apt-get install debconf
sudo apt-get install debconf-i18n
sudo apt-get install debianutils
sudo apt-get install deja-dup
sudo apt-get install desktop-file-utils
sudo apt-get install dictionaries-common
sudo apt-get install diffutils
sudo apt-get install dmidecode
sudo apt-get install dmsetup
sudo apt-get install dmz-cursor-theme
sudo apt-get install dnsmasq-base
sudo apt-get install dnsutils
sudo apt-get install doc-base
sudo apt-get install dosfstools
sudo apt-get install dpkg
sudo apt-get install duplicity
sudo apt-get install dvd+rw-tools
sudo apt-get install e2fslibs
sudo apt-get install e2fsprogs
sudo apt-get install ed
sudo apt-get install eject
sudo apt-get install empathy
sudo apt-get install empathy-common
sudo apt-get install enchant
sudo apt-get install eog
sudo apt-get install espeak
sudo apt-get install espeak-data
sudo apt-get install evince
sudo apt-get install evince-common
sudo apt-get install evolution-data-server
sudo apt-get install evolution-data-server-common
sudo apt-get install example-content
sudo apt-get install file
sudo apt-get install file-roller
sudo apt-get install findutils
sudo apt-get install firefox
sudo apt-get install firefox-globalmenu
sudo apt-get install firefox-gnome-support
sudo apt-get install firefox-locale-en
sudo apt-get install folks-common
sudo apt-get install fontconfig
sudo apt-get install fontconfig-config
sudo apt-get install fonts-kacst
sudo apt-get install fonts-kacst-one
sudo apt-get install fonts-khmeros-core
sudo apt-get install fonts-lao
sudo apt-get install fonts-liberation
sudo apt-get install fonts-nanum
sudo apt-get install fonts-opensymbol
sudo apt-get install fonts-takao-pgothic
sudo apt-get install fonts-thai-tlwg
sudo apt-get install fonts-tlwg-garuda
sudo apt-get install fonts-tlwg-kinnari
sudo apt-get install fonts-tlwg-loma
sudo apt-get install fonts-tlwg-mono
sudo apt-get install fonts-tlwg-norasi
sudo apt-get install fonts-tlwg-purisa
sudo apt-get install fonts-tlwg-sawasdee
sudo apt-get install fonts-tlwg-typewriter
sudo apt-get install fonts-tlwg-typist
sudo apt-get install fonts-tlwg-typo
sudo apt-get install fonts-tlwg-umpush
sudo apt-get install fonts-tlwg-waree
sudo apt-get install foomatic-db-compressed-ppds
sudo apt-get install foomatic-db-engine
sudo apt-get install foomatic-filters
sudo apt-get install friendly-recovery
sudo apt-get install ftp
sudo apt-get install fuse
sudo apt-get install gcalctool
sudo apt-get install gcc
sudo apt-get install gcc-4.6
sudo apt-get install gcc-4.6-base
sudo apt-get install gconf-service
sudo apt-get install gconf-service-backend
sudo apt-get install gconf2
sudo apt-get install gconf2-common
sudo apt-get install gdb
sudo apt-get install gedit
sudo apt-get install gedit-common
sudo apt-get install genisoimage
sudo apt-get install geoclue
sudo apt-get install geoclue-ubuntu-geoip
sudo apt-get install geoip-database
sudo apt-get install gettext-base
sudo apt-get install ghostscript
sudo apt-get install ghostscript-cups
sudo apt-get install ghostscript-x
sudo apt-get install ginn
sudo apt-get install gir1.2-appindicator3-0.1
sudo apt-get install gir1.2-atk-1.0
sudo apt-get install gir1.2-atspi-2.0
sudo apt-get install gir1.2-dbusmenu-glib-0.4
sudo apt-get install gir1.2-dbusmenu-gtk-0.4
sudo apt-get install gir1.2-dee-1.0
sudo apt-get install gir1.2-freedesktop
sudo apt-get install gir1.2-gdkpixbuf-2.0
sudo apt-get install gir1.2-glib-2.0
sudo apt-get install gir1.2-gmenu-3.0
sudo apt-get install gir1.2-gnomebluetooth-1.0
sudo apt-get install gir1.2-gnomekeyring-1.0
sudo apt-get install gir1.2-gst-plugins-base-0.10
sudo apt-get install gir1.2-gstreamer-0.10
sudo apt-get install gir1.2-gtk-2.0
sudo apt-get install gir1.2-gtk-3.0
sudo apt-get install gir1.2-gtksource-3.0
sudo apt-get install gir1.2-gudev-1.0
sudo apt-get install gir1.2-indicate-0.7
sudo apt-get install gir1.2-javascriptcoregtk-3.0
sudo apt-get install gir1.2-launchpad-integration-3.0
sudo apt-get install gir1.2-notify-0.7
sudo apt-get install gir1.2-pango-1.0
sudo apt-get install gir1.2-peas-1.0
sudo apt-get install gir1.2-rb-3.0
sudo apt-get install gir1.2-soup-2.4
sudo apt-get install gir1.2-totem-1.0
sudo apt-get install gir1.2-totem-plparser-1.0
sudo apt-get install gir1.2-ubuntuoneui-3.0
sudo apt-get install gir1.2-unity-5.0
sudo apt-get install gir1.2-vte-2.90
sudo apt-get install gir1.2-webkit-3.0
sudo apt-get install gir1.2-wnck-3.0
sudo apt-get install gksu
sudo apt-get install glib-networking
sudo apt-get install glib-networking-common
sudo apt-get install glib-networking-services
sudo apt-get install gnome-accessibility-themes
sudo apt-get install gnome-bluetooth
sudo apt-get install gnome-control-center
sudo apt-get install gnome-control-center-data
sudo apt-get install gnome-desktop3-data
sudo apt-get install gnome-disk-utility
sudo apt-get install gnome-font-viewer
sudo apt-get install gnome-games-data
sudo apt-get install gnome-icon-theme
sudo apt-get install gnome-icon-theme-symbolic
sudo apt-get install gnome-keyring
sudo apt-get install gnome-media
sudo apt-get install gnome-menus
sudo apt-get install gnome-nettool
sudo apt-get install gnome-online-accounts
sudo apt-get install gnome-orca
sudo apt-get install gnome-power-manager
sudo apt-get install gnome-screensaver
sudo apt-get install gnome-screenshot
sudo apt-get install gnome-session
sudo apt-get install gnome-session-bin
sudo apt-get install gnome-session-canberra
sudo apt-get install gnome-session-common
sudo apt-get install gnome-settings-daemon
sudo apt-get install gnome-sudoku
sudo apt-get install gnome-system-log
sudo apt-get install gnome-system-monitor
sudo apt-get install gnome-terminal
sudo apt-get install gnome-terminal-data
sudo apt-get install gnome-user-guide
sudo apt-get install gnome-user-share
sudo apt-get install gnomine
sudo apt-get install gnupg
sudo apt-get install gpgv
sudo apt-get install grep
sudo apt-get install groff-base
sudo apt-get install growisofs
sudo apt-get install grub-common
sudo apt-get install grub-gfxpayload-lists
sudo apt-get install grub-pc
sudo apt-get install grub-pc-bin
sudo apt-get install grub2-common
sudo apt-get install gs-cjk-resource
sudo apt-get install gsettings-desktop-schemas
sudo apt-get install gsfonts
sudo apt-get install gstreamer0.10-alsa
sudo apt-get install gstreamer0.10-gconf
sudo apt-get install gstreamer0.10-nice
sudo apt-get install gstreamer0.10-plugins-base
sudo apt-get install gstreamer0.10-plugins-base-apps
sudo apt-get install gstreamer0.10-plugins-good
sudo apt-get install gstreamer0.10-pulseaudio
sudo apt-get install gstreamer0.10-tools
sudo apt-get install gstreamer0.10-x
sudo apt-get install gtk2-engines
sudo apt-get install gtk2-engines-murrine
sudo apt-get install gtk3-engines-unico
sudo apt-get install gucharmap
sudo apt-get install guile-1.8-libs
sudo apt-get install gvfs
sudo apt-get install gvfs-backends
sudo apt-get install gvfs-bin
sudo apt-get install gvfs-common
sudo apt-get install gvfs-daemons
sudo apt-get install gvfs-fuse
sudo apt-get install gvfs-libs
sudo apt-get install gwibber
sudo apt-get install gwibber-service
sudo apt-get install gwibber-service-facebook
sudo apt-get install gwibber-service-identica
sudo apt-get install gwibber-service-twitter
sudo apt-get install gzip
sudo apt-get install hdparm
sudo apt-get install hicolor-icon-theme
sudo apt-get install hostname
sudo apt-get install hplip
sudo apt-get install hplip-data
sudo apt-get install humanity-icon-theme
sudo apt-get install hunspell-en-us
sudo apt-get install hwdata
sudo apt-get install ibus
sudo apt-get install ibus-gtk
sudo apt-get install ibus-gtk3
sudo apt-get install ibus-pinyin
sudo apt-get install ibus-pinyin-db-android
sudo apt-get install ibus-table
sudo apt-get install ifupdown
sudo apt-get install im-switch
sudo apt-get install indicator-application
sudo apt-get install indicator-appmenu
sudo apt-get install indicator-datetime
sudo apt-get install indicator-messages
sudo apt-get install indicator-power
sudo apt-get install indicator-printers
sudo apt-get install indicator-session
sudo apt-get install indicator-sound
sudo apt-get install indicator-status-provider-mc5
sudo apt-get install info
sudo apt-get install initramfs-tools
sudo apt-get install initramfs-tools-bin
sudo apt-get install initscripts
sudo apt-get install inputattach
sudo apt-get install insserv
sudo apt-get install install-info
sudo apt-get install intel-gpu-tools
sudo apt-get install iproute
sudo apt-get install iptables
sudo apt-get install iputils-arping
sudo apt-get install iputils-ping
sudo apt-get install iputils-tracepath
sudo apt-get install irqbalance
sudo apt-get install isc-dhcp-client
sudo apt-get install isc-dhcp-common
sudo apt-get install iso-codes
sudo apt-get install iw
sudo apt-get install jockey-common
sudo apt-get install jockey-gtk
sudo apt-get install kbd
sudo apt-get install kerneloops-daemon
sudo apt-get install keyboard-configuration
sudo apt-get install klibc-utils
sudo apt-get install krb5-locales
sudo apt-get install landscape-client-ui-install
sudo apt-get install language-pack-en
sudo apt-get install language-pack-en-base
sudo apt-get install language-pack-gnome-en
sudo apt-get install language-pack-gnome-en-base
sudo apt-get install language-selector-common
sudo apt-get install language-selector-gnome
sudo apt-get install laptop-detect
sudo apt-get install launchpad-integration
sudo apt-get install less
sudo apt-get install libaa1
sudo apt-get install libaccountsservice0
sudo apt-get install libacl1
sudo apt-get install libappindicator1
sudo apt-get install libappindicator3-1
sudo apt-get install libapt-inst1.4
sudo apt-get install libapt-pkg4.12
sudo apt-get install libarchive12
sudo apt-get install libart-2.0-2
sudo apt-get install libasn1-8-heimdal
sudo apt-get install libasound2
sudo apt-get install libasound2-plugins
sudo apt-get install libaspell15
sudo apt-get install libasyncns0
sudo apt-get install libatasmart4
sudo apt-get install libatk-adaptor
sudo apt-get install libatk-adaptor-schemas
sudo apt-get install libatk1.0-0
sudo apt-get install libatk1.0-data
sudo apt-get install libatkmm-1.6-1
sudo apt-get install libatspi2.0-0
sudo apt-get install libattr1
sudo apt-get install libaudio2
sudo apt-get install libavahi-client3
sudo apt-get install libavahi-common-data
sudo apt-get install libavahi-common3
sudo apt-get install libavahi-core7
sudo apt-get install libavahi-glib1
sudo apt-get install libavahi-gobject0
sudo apt-get install libavahi-ui-gtk3-0
sudo apt-get install libavc1394-0
sudo apt-get install libbamf0
sudo apt-get install libbamf3-0
sudo apt-get install libbind9-80
sudo apt-get install libblkid1
sudo apt-get install libbluetooth3
sudo apt-get install libboost-serialization1.46.1
sudo apt-get install libbrasero-media3-1
sudo apt-get install libbrlapi0.5
sudo apt-get install libbsd0
sudo apt-get install libburn4
sudo apt-get install libbz2-1.0
sudo apt-get install libc-bin
sudo apt-get install libc-dev-bin
sudo apt-get install libc6
sudo apt-get install libc6-dev
sudo apt-get install libcaca0
sudo apt-get install libcairo-gobject2
sudo apt-get install libcairo-perl
sudo apt-get install libcairo2
sudo apt-get install libcairomm-1.0-1
sudo apt-get install libcamel-1.2-29
sudo apt-get install libcanberra-gtk-module
sudo apt-get install libcanberra-gtk0
sudo apt-get install libcanberra-gtk3-0
sudo apt-get install libcanberra-gtk3-module
sudo apt-get install libcanberra-pulse
sudo apt-get install libcanberra0
sudo apt-get install libcap-ng0
sudo apt-get install libcap2
sudo apt-get install libcap2-bin
sudo apt-get install libcdio-cdda1
sudo apt-get install libcdio-paranoia1
sudo apt-get install libcdio13
sudo apt-get install libcdparanoia0
sudo apt-get install libck-connector0
sudo apt-get install libclass-isa-perl
sudo apt-get install libcmis-0.2-0
sudo apt-get install libcolord1
sudo apt-get install libcomerr2
sudo apt-get install libcompizconfig0
sudo apt-get install libcroco3
sudo apt-get install libcrypt-passwdmd5-perl
sudo apt-get install libcryptsetup4
sudo apt-get install libcups2
sudo apt-get install libcupscgi1
sudo apt-get install libcupsdriver1
sudo apt-get install libcupsfilters1
sudo apt-get install libcupsimage2
sudo apt-get install libcupsmime1
sudo apt-get install libcupsppdc1
sudo apt-get install libcurl3
sudo apt-get install libcurl3-gnutls
sudo apt-get install libcurl3-nss
sudo apt-get install libdaemon0
sudo apt-get install libdatrie1
sudo apt-get install libdb5.1
sudo apt-get install libdbus-1-3
sudo apt-get install libdbus-glib-1-2
sudo apt-get install libdbusmenu-glib4
sudo apt-get install libdbusmenu-gtk3-4
sudo apt-get install libdbusmenu-gtk4
sudo apt-get install libdbusmenu-qt2
sudo apt-get install libdconf-dbus-1-0
sudo apt-get install libdconf-qt0
sudo apt-get install libdconf0
sudo apt-get install libdecoration0
sudo apt-get install libdee-1.0-4
sudo apt-get install libdevmapper-event1.02.1
sudo apt-get install libdevmapper1.02.1
sudo apt-get install libdiscid0
sudo apt-get install libdjvulibre-text
sudo apt-get install libdjvulibre21
sudo apt-get install libdmapsharing-3.0-2
sudo apt-get install libdns81
sudo apt-get install libdotconf1.0
sudo apt-get install libdrm-intel1
sudo apt-get install libdrm-nouveau1a
sudo apt-get install libdrm-nouveau2
sudo apt-get install libdrm-radeon1
sudo apt-get install libdrm2
sudo apt-get install libdv4
sudo apt-get install libebackend-1.2-1
sudo apt-get install libebook-1.2-12
sudo apt-get install libecal-1.2-10
sudo apt-get install libedata-book-1.2-11
sudo apt-get install libedata-cal-1.2-13
sudo apt-get install libedataserver-1.2-15
sudo apt-get install libedataserverui-3.0-1
sudo apt-get install libedit2
sudo apt-get install libelf1
sudo apt-get install libenchant1c2a
sudo apt-get install libespeak1
sudo apt-get install libevent-2.0-5
sudo apt-get install libevince3-3
sudo apt-get install libexempi3
sudo apt-get install libexif12
sudo apt-get install libexiv2-11
sudo apt-get install libexpat1
sudo apt-get install libexttextcat-data
sudo apt-get install libexttextcat0
sudo apt-get install libfarstream-0.1-0
sudo apt-get install libffi6
sudo apt-get install libfile-basedir-perl
sudo apt-get install libfile-copy-recursive-perl
sudo apt-get install libfile-desktopentry-perl
sudo apt-get install libfile-mimeinfo-perl
sudo apt-get install libflac8
sudo apt-get install libfolks-eds25
sudo apt-get install libfolks-telepathy25
sudo apt-get install libfolks25
sudo apt-get install libfontconfig1
sudo apt-get install libfontenc1
sudo apt-get install libframe6
sudo apt-get install libfreerdp-plugins-standard
sudo apt-get install libfreerdp1
sudo apt-get install libfreetype6
sudo apt-get install libfribidi0
sudo apt-get install libfs6
sudo apt-get install libfuse2
sudo apt-get install libgail-3-0
sudo apt-get install libgail-common
sudo apt-get install libgail18
sudo apt-get install libgcc1
sudo apt-get install libgck-1-0
sudo apt-get install libgconf-2-4
sudo apt-get install libgconf2-4
sudo apt-get install libgcr-3-1
sudo apt-get install libgcr-3-common
sudo apt-get install libgcrypt11
sudo apt-get install libgd2-xpm
sudo apt-get install libgdata-common
sudo apt-get install libgdata13
sudo apt-get install libgdbm3
sudo apt-get install libgdk-pixbuf2.0-0
sudo apt-get install libgdk-pixbuf2.0-common
sudo apt-get install libgdu-gtk0
sudo apt-get install libgdu0
sudo apt-get install libgee2
sudo apt-get install libgeis1
sudo apt-get install libgeoclue0
sudo apt-get install libgeoip1
sudo apt-get install libgexiv2-1
sudo apt-get install libgirepository-1.0-1
sudo apt-get install libgksu2-0
sudo apt-get install libgl1-mesa-dri-lts-quantal
sudo apt-get install libgl1-mesa-glx-lts-quantal
sudo apt-get install libglapi-mesa-lts-quantal
sudo apt-get install libglew1.6
sudo apt-get install libglewmx1.6
sudo apt-get install libglib-perl
sudo apt-get install libglib2.0-0
sudo apt-get install libglib2.0-bin
sudo apt-get install libglib2.0-data
sudo apt-get install libglibmm-2.4-1c2a
sudo apt-get install libglu1-mesa
sudo apt-get install libgmime-2.6-0
sudo apt-get install libgmp10
sudo apt-get install libgnome-bluetooth8
sudo apt-get install libgnome-control-center1
sudo apt-get install libgnome-desktop-3-2
sudo apt-get install libgnome-keyring-common
sudo apt-get install libgnome-keyring0
sudo apt-get install libgnome-media-profiles-3.0-0
sudo apt-get install libgnome-menu-3-0
sudo apt-get install libgnome-menu2
sudo apt-get install libgnome2-common
sudo apt-get install libgnomekbd-common
sudo apt-get install libgnomekbd7
sudo apt-get install libgnutls26
sudo apt-get install libgoa-1.0-0
sudo apt-get install libgoa-1.0-common
sudo apt-get install libgomp1
sudo apt-get install libgpg-error0
sudo apt-get install libgpgme11
sudo apt-get install libgphoto2-2
sudo apt-get install libgphoto2-l10n
sudo apt-get install libgphoto2-port0
sudo apt-get install libgpm2
sudo apt-get install libgpod-common
sudo apt-get install libgpod4
sudo apt-get install libgrail5
sudo apt-get install libgrip0
sudo apt-get install libgs9
sudo apt-get install libgs9-common
sudo apt-get install libgssapi-krb5-2
sudo apt-get install libgssapi3-heimdal
sudo apt-get install libgssdp-1.0-3
sudo apt-get install libgstreamer-plugins-base0.10-0
sudo apt-get install libgstreamer0.10-0
sudo apt-get install libgtk-3-0
sudo apt-get install libgtk-3-bin
sudo apt-get install libgtk-3-common
sudo apt-get install libgtk2-perl
sudo apt-get install libgtk2.0-0
sudo apt-get install libgtk2.0-bin
sudo apt-get install libgtk2.0-common
sudo apt-get install libgtkmm-3.0-1
sudo apt-get install libgtksourceview-3.0-0
sudo apt-get install libgtksourceview-3.0-common
sudo apt-get install libgtkspell-3-0
sudo apt-get install libgtop2-7
sudo apt-get install libgtop2-common
sudo apt-get install libgucharmap-2-90-7
sudo apt-get install libgudev-1.0-0
sudo apt-get install libgupnp-1.0-4
sudo apt-get install libgupnp-igd-1.0-4
sudo apt-get install libgutenprint2
sudo apt-get install libgweather-3-0
sudo apt-get install libgweather-common
sudo apt-get install libgwibber-gtk2
sudo apt-get install libgwibber2
sudo apt-get install libhcrypto4-heimdal
sudo apt-get install libheimbase1-heimdal
sudo apt-get install libheimntlm0-heimdal
sudo apt-get install libhpmud0
sudo apt-get install libhunspell-1.3-0
sudo apt-get install libhx509-5-heimdal
sudo apt-get install libhyphen0
sudo apt-get install libibus-1.0-0
sudo apt-get install libical0
sudo apt-get install libice6
sudo apt-get install libicu48
sudo apt-get install libidn11
sudo apt-get install libido3-0.1-0
sudo apt-get install libiec61883-0
sudo apt-get install libieee1284-3
sudo apt-get install libijs-0.35
sudo apt-get install libimobiledevice2
sudo apt-get install libindicate-gtk3
sudo apt-get install libindicate5
sudo apt-get install libindicator-messages-status-provider1
sudo apt-get install libindicator3-7
sudo apt-get install libindicator7
sudo apt-get install libisc83
sudo apt-get install libisccc80
sudo apt-get install libisccfg82
sudo apt-get install libisofs6
sudo apt-get install libiw30
sudo apt-get install libjack-jackd2-0
sudo apt-get install libjasper1
sudo apt-get install libjavascriptcoregtk-3.0-0
sudo apt-get install libjbig2dec0
sudo apt-get install libjpeg-turbo8
sudo apt-get install libjpeg8
sudo apt-get install libjs-jquery
sudo apt-get install libjson-glib-1.0-0
sudo apt-get install libjson0
sudo apt-get install libjte1
sudo apt-get install libk5crypto3
sudo apt-get install libkeyutils1
sudo apt-get install libklibc
sudo apt-get install libkpathsea5
sudo apt-get install libkrb5-26-heimdal
sudo apt-get install libkrb5-3
sudo apt-get install libkrb5support0
sudo apt-get install liblaunchpad-integration-3.0-1
sudo apt-get install liblaunchpad-integration-common
sudo apt-get install liblcms1
sudo apt-get install liblcms2-2
sudo apt-get install libldap-2.4-2
sudo apt-get install liblightdm-gobject-1-0
sudo apt-get install liblircclient0
sudo apt-get install libllvm3.1
sudo apt-get install liblocale-gettext-perl
sudo apt-get install liblockfile-bin
sudo apt-get install liblockfile1
sudo apt-get install liblouis-data
sudo apt-get install liblouis2
sudo apt-get install libltdl7
sudo apt-get install liblua5.1-0
sudo apt-get install liblvm2app2.2
sudo apt-get install liblwres80
sudo apt-get install liblzma5
sudo apt-get install libmagic1
sudo apt-get install libmeanwhile1
sudo apt-get install libmetacity-private0
sudo apt-get install libmhash2
sudo apt-get install libminiupnpc8
sudo apt-get install libmission-control-plugins0
sudo apt-get install libmng1
sudo apt-get install libmount1
sudo apt-get install libmpc2
sudo apt-get install libmpfr4
sudo apt-get install libmtdev1
sudo apt-get install libmtp-common
sudo apt-get install libmtp-runtime
sudo apt-get install libmtp9
sudo apt-get install libmusicbrainz3-6
sudo apt-get install libmythes-1.2-0
sudo apt-get install libnautilus-extension1a
sudo apt-get install libncurses5
sudo apt-get install libncursesw5
sudo apt-get install libneon27-gnutls
sudo apt-get install libnetfilter-conntrack3
sudo apt-get install libnettle4
sudo apt-get install libnewt0.52
sudo apt-get install libnfnetlink0
sudo apt-get install libnice10
sudo apt-get install libnih-dbus1
sudo apt-get install libnih1
sudo apt-get install libnl-3-200
sudo apt-get install libnl-genl-3-200
sudo apt-get install libnl-route-3-200
sudo apt-get install libnm-glib-vpn1
sudo apt-get install libnm-glib4
sudo apt-get install libnm-gtk-common
sudo apt-get install libnm-gtk0
sudo apt-get install libnm-util2
sudo apt-get install libnotify-bin
sudo apt-get install libnotify4
sudo apt-get install libnspr4
sudo apt-get install libnss-mdns
sudo apt-get install libnss3
sudo apt-get install libnux-2.0-0
sudo apt-get install libnux-2.0-common
sudo apt-get install liboauth0
sudo apt-get install libogg0
sudo apt-get install libopencc1
sudo apt-get install libopenobex1
sudo apt-get install liborc-0.4-0
sudo apt-get install liboverlay-scrollbar-0.2-0
sudo apt-get install liboverlay-scrollbar3-0.2-0
sudo apt-get install libp11-kit0
sudo apt-get install libpackagekit-glib2-14
sudo apt-get install libpam-cap
sudo apt-get install libpam-ck-connector
sudo apt-get install libpam-gnome-keyring
sudo apt-get install libpam-modules
sudo apt-get install libpam-modules-bin
sudo apt-get install libpam-runtime
sudo apt-get install libpam0g
sudo apt-get install libpango-perl
sudo apt-get install libpango1.0-0
sudo apt-get install libpangomm-1.4-1
sudo apt-get install libpaper-utils
sudo apt-get install libpaper1
sudo apt-get install libparted0debian1
sudo apt-get install libpcap0.8
sudo apt-get install libpci3
sudo apt-get install libpciaccess0
sudo apt-get install libpcre3
sudo apt-get install libpcsclite1
sudo apt-get install libpeas-1.0-0
sudo apt-get install libpeas-common
sudo apt-get install libperl5.14
sudo apt-get install libpipeline1
sudo apt-get install libpixman-1-0
sudo apt-get install libplist1
sudo apt-get install libplymouth2
sudo apt-get install libpng12-0
sudo apt-get install libpolkit-agent-1-0
sudo apt-get install libpolkit-backend-1-0
sudo apt-get install libpolkit-gobject-1-0
sudo apt-get install libpoppler-glib8
sudo apt-get install libpoppler19
sudo apt-get install libpopt0
sudo apt-get install libportaudio2
sudo apt-get install libprotobuf7
sudo apt-get install libprotoc7
sudo apt-get install libproxy1
sudo apt-get install libproxy1-plugin-gsettings
sudo apt-get install libproxy1-plugin-networkmanager
sudo apt-get install libpth20
sudo apt-get install libpulse-mainloop-glib0
sudo apt-get install libpulse0
sudo apt-get install libpulsedsp
sudo apt-get install libpurple-bin
sudo apt-get install libpurple0
sudo apt-get install libpython2.7
sudo apt-get install libqt4-dbus
sudo apt-get install libqt4-declarative
sudo apt-get install libqt4-network
sudo apt-get install libqt4-opengl
sudo apt-get install libqt4-script
sudo apt-get install libqt4-sql
sudo apt-get install libqt4-sql-sqlite
sudo apt-get install libqt4-svg
sudo apt-get install libqt4-xml
sudo apt-get install libqt4-xmlpatterns
sudo apt-get install libqtbamf1
sudo apt-get install libqtcore4
sudo apt-get install libqtdee2
sudo apt-get install libqtgconf1
sudo apt-get install libqtgui4
sudo apt-get install libquadmath0
sudo apt-get install libquvi-scripts
sudo apt-get install libquvi7
sudo apt-get install libraptor2-0
sudo apt-get install librasqal3
sudo apt-get install libraw1394-11
sudo apt-get install libraw5
sudo apt-get install librdf0
sudo apt-get install libreadline6
sudo apt-get install libreoffice-base-core
sudo apt-get install libreoffice-calc
sudo apt-get install libreoffice-common
sudo apt-get install libreoffice-core
sudo apt-get install libreoffice-draw
sudo apt-get install libreoffice-emailmerge
sudo apt-get install libreoffice-gnome
sudo apt-get install libreoffice-gtk
sudo apt-get install libreoffice-help-en-us
sudo apt-get install libreoffice-impress
sudo apt-get install libreoffice-math
sudo apt-get install libreoffice-style-human
sudo apt-get install libreoffice-style-tango
sudo apt-get install libreoffice-writer
sudo apt-get install librest-0.7-0
sudo apt-get install librhythmbox-core5
sudo apt-get install libroken18-heimdal
sudo apt-get install librsvg2-2
sudo apt-get install librsvg2-common
sudo apt-get install librsync1
sudo apt-get install librtmp0
sudo apt-get install libsamplerate0
sudo apt-get install libsane
sudo apt-get install libsane-common
sudo apt-get install libsane-hpaio
sudo apt-get install libsasl2-2
sudo apt-get install libsasl2-modules
sudo apt-get install libsdl1.2debian
sudo apt-get install libselinux1
sudo apt-get install libsensors4
sudo apt-get install libsgutils2-2
sudo apt-get install libshout3
sudo apt-get install libsigc++-2.0-0c2a
sudo apt-get install libslang2
sudo apt-get install libslp1
sudo apt-get install libsm6
sudo apt-get install libsmbclient
sudo apt-get install libsndfile1
sudo apt-get install libsnmp-base
sudo apt-get install libsnmp15
sudo apt-get install libsonic0
sudo apt-get install libsoup-gnome2.4-1
sudo apt-get install libsoup2.4-1
sudo apt-get install libspectre1
sudo apt-get install libspeechd2
sudo apt-get install libspeex1
sudo apt-get install libspeexdsp1
sudo apt-get install libsqlite3-0
sudo apt-get install libss2
sudo apt-get install libssh-4
sudo apt-get install libssl1.0.0
sudo apt-get install libstartup-notification0
sudo apt-get install libstdc++6
sudo apt-get install libswitch-perl
sudo apt-get install libsyncdaemon-1.0-1
sudo apt-get install libsysfs2
sudo apt-get install libt1-5
sudo apt-get install libtag1-vanilla
sudo apt-get install libtag1c2a
sudo apt-get install libtalloc2
sudo apt-get install libtasn1-3
sudo apt-get install libtdb1
sudo apt-get install libtelepathy-farstream2
sudo apt-get install libtelepathy-glib0
sudo apt-get install libtelepathy-logger2
sudo apt-get install libtext-charwidth-perl
sudo apt-get install libtext-iconv-perl
sudo apt-get install libtext-wrapi18n-perl
sudo apt-get install libthai-data
sudo apt-get install libthai0
sudo apt-get install libtheora0
sudo apt-get install libtiff4
sudo apt-get install libtimezonemap1
sudo apt-get install libtinfo5
sudo apt-get install libtotem-plparser17
sudo apt-get install libtotem0
sudo apt-get install libubuntuoneui-3.0-1
sudo apt-get install libudev0
sudo apt-get install libunique-3.0-0
sudo apt-get install libunity-2d-private0
sudo apt-get install libunity-core-5.0-5
sudo apt-get install libunity-misc4
sudo apt-get install libunity9
sudo apt-get install libupower-glib1
sudo apt-get install libusb-0.1-4
sudo apt-get install libusb-1.0-0
sudo apt-get install libusbmuxd1
sudo apt-get install libutempter0
sudo apt-get install libuuid-perl
sudo apt-get install libuuid1
sudo apt-get install libv4l-0
sudo apt-get install libv4lconvert0
sudo apt-get install libvisual-0.4-0
sudo apt-get install libvisual-0.4-plugins
sudo apt-get install libvncserver0
sudo apt-get install libvorbis0a
sudo apt-get install libvorbisenc2
sudo apt-get install libvorbisfile3
sudo apt-get install libvte-2.90-9
sudo apt-get install libvte-2.90-common
sudo apt-get install libwacom-common
sudo apt-get install libwacom2
sudo apt-get install libwavpack1
sudo apt-get install libwbclient0
sudo apt-get install libwebkitgtk-3.0-0
sudo apt-get install libwebkitgtk-3.0-common
sudo apt-get install libwind0-heimdal
sudo apt-get install libwmf0.2-7
sudo apt-get install libwmf0.2-7-gtk
sudo apt-get install libwnck-3-0
sudo apt-get install libwnck-3-common
sudo apt-get install libwnck-common
sudo apt-get install libwnck22
sudo apt-get install libwpd-0.9-9
sudo apt-get install libwpg-0.2-2
sudo apt-get install libwps-0.2-2
sudo apt-get install libwrap0
sudo apt-get install libx11-6
sudo apt-get install libx11-data
sudo apt-get install libx11-xcb1
sudo apt-get install libx86-1
sudo apt-get install libxapian22
sudo apt-get install libxatracker1-lts-quantal
sudo apt-get install libxau6
sudo apt-get install libxaw7
sudo apt-get install libxcb-dri2-0
sudo apt-get install libxcb-glx0
sudo apt-get install libxcb-render0
sudo apt-get install libxcb-shape0
sudo apt-get install libxcb-shm0
sudo apt-get install libxcb-util0
sudo apt-get install libxcb1
sudo apt-get install libxcomposite1
sudo apt-get install libxcursor1
sudo apt-get install libxdamage1
sudo apt-get install libxdmcp6
sudo apt-get install libxext6
sudo apt-get install libxfixes3
sudo apt-get install libxfont1
sudo apt-get install libxft2
sudo apt-get install libxi6
sudo apt-get install libxinerama1
sudo apt-get install libxkbfile1
sudo apt-get install libxklavier16
sudo apt-get install libxml2
sudo apt-get install libxmu6
sudo apt-get install libxmuu1
sudo apt-get install libxp6
sudo apt-get install libxpm4
sudo apt-get install libxrandr-ltsq2
sudo apt-get install libxrandr2
sudo apt-get install libxrender1
sudo apt-get install libxres1
sudo apt-get install libxslt1.1
sudo apt-get install libxt6
sudo apt-get install libxtst6
sudo apt-get install libxv1
sudo apt-get install libxvmc1
sudo apt-get install libxxf86dga1
sudo apt-get install libxxf86vm1
sudo apt-get install libyajl1
sudo apt-get install libyaml-tiny-perl
sudo apt-get install libyelp0
sudo apt-get install libzeitgeist-1.0-1
sudo apt-get install libzephyr4
sudo apt-get install light-themes
sudo apt-get install lightdm
sudo apt-get install linux-firmware
sudo apt-get install linux-generic-lts-quantal
sudo apt-get install linux-headers-3.5.0-23
sudo apt-get install linux-headers-3.5.0-23-generic
sudo apt-get install linux-headers-generic-lts-quantal
sudo apt-get install linux-image-3.5.0-23-generic
sudo apt-get install linux-image-generic-lts-quantal
sudo apt-get install linux-libc-dev
sudo apt-get install linux-sound-base
sudo apt-get install locales
sudo apt-get install lockfile-progs
sudo apt-get install login
sudo apt-get install logrotate
sudo apt-get install lsb-base
sudo apt-get install lsb-release
sudo apt-get install lshw
sudo apt-get install lsof
sudo apt-get install ltrace
sudo apt-get install mahjongg
sudo apt-get install make
sudo apt-get install makedev
sudo apt-get install man-db
sudo apt-get install manpages
sudo apt-get install manpages-dev
sudo apt-get install mawk
sudo apt-get install media-player-info
sudo apt-get install memtest86+
sudo apt-get install metacity
sudo apt-get install metacity-common
sudo apt-get install mime-support
sudo apt-get install mlocate
sudo apt-get install mobile-broadband-provider-info
sudo apt-get install modemmanager
sudo apt-get install module-init-tools
sudo apt-get install mount
sudo apt-get install mountall
sudo apt-get install mousetweaks
sudo apt-get install mscompress
sudo apt-get install mtools
sudo apt-get install mtr-tiny
sudo apt-get install multiarch-support
sudo apt-get install nano
sudo apt-get install nautilus
sudo apt-get install nautilus-data
sudo apt-get install nautilus-sendto
sudo apt-get install nautilus-sendto-empathy
sudo apt-get install nautilus-share
sudo apt-get install ncurses-base
sudo apt-get install ncurses-bin
sudo apt-get install net-tools
sudo apt-get install netbase
sudo apt-get install netcat-openbsd
sudo apt-get install network-manager
sudo apt-get install network-manager-gnome
sudo apt-get install network-manager-pptp
sudo apt-get install network-manager-pptp-gnome
sudo apt-get install notify-osd
sudo apt-get install notify-osd-icons
sudo apt-get install ntfs-3g
sudo apt-get install ntpdate
sudo apt-get install nux-tools
sudo apt-get install nvidia-common
sudo apt-get install obex-data-server
sudo apt-get install obexd-client
sudo apt-get install onboard
sudo apt-get install oneconf
sudo apt-get install openprinting-ppds
sudo apt-get install openssh-client
sudo apt-get install openssl
sudo apt-get install os-prober
sudo apt-get install overlay-scrollbar
sudo apt-get install parted
sudo apt-get install passwd
sudo apt-get install patch
sudo apt-get install pciutils
sudo apt-get install pcmciautils
sudo apt-get install perl
sudo apt-get install perl-base
sudo apt-get install perl-modules
sudo apt-get install pkg-config
sudo apt-get install plymouth
sudo apt-get install plymouth-label
sudo apt-get install plymouth-theme-ubuntu-logo
sudo apt-get install plymouth-theme-ubuntu-text
sudo apt-get install pm-utils
sudo apt-get install policykit-1
sudo apt-get install policykit-1-gnome
sudo apt-get install policykit-desktop-privileges
sudo apt-get install poppler-utils
sudo apt-get install popularity-contest
sudo apt-get install powermgmt-base
sudo apt-get install ppp
sudo apt-get install pppconfig
sudo apt-get install pppoeconf
sudo apt-get install pptp-linux
sudo apt-get install printer-driver-c2esp
sudo apt-get install printer-driver-foo2zjs
sudo apt-get install printer-driver-gutenprint
sudo apt-get install printer-driver-hpcups
sudo apt-get install printer-driver-hpijs
sudo apt-get install printer-driver-min12xxw
sudo apt-get install printer-driver-pnm2ppa
sudo apt-get install printer-driver-postscript-hp
sudo apt-get install printer-driver-ptouch
sudo apt-get install printer-driver-pxljr
sudo apt-get install printer-driver-sag-gdi
sudo apt-get install printer-driver-splix
sudo apt-get install procps
sudo apt-get install protobuf-compiler
sudo apt-get install psmisc
sudo apt-get install pulseaudio
sudo apt-get install pulseaudio-module-bluetooth
sudo apt-get install pulseaudio-module-gconf
sudo apt-get install pulseaudio-module-x11
sudo apt-get install pulseaudio-utils
sudo apt-get install python
sudo apt-get install python-appindicator
sudo apt-get install python-apport
sudo apt-get install python-apt
sudo apt-get install python-apt-common
sudo apt-get install python-aptdaemon
sudo apt-get install python-aptdaemon.gtk3widgets
sudo apt-get install python-aptdaemon.pkcompat
sudo apt-get install python-brlapi
sudo apt-get install python-cairo
sudo apt-get install python-chardet
sudo apt-get install python-configglue
sudo apt-get install python-crypto
sudo apt-get install python-cups
sudo apt-get install python-cupshelpers
sudo apt-get install python-dateutil
sudo apt-get install python-dbus
sudo apt-get install python-dbus-dev
sudo apt-get install python-debian
sudo apt-get install python-debtagshw
sudo apt-get install python-defer
sudo apt-get install python-dirspec
sudo apt-get install python-egenix-mxdatetime
sudo apt-get install python-egenix-mxtools
sudo apt-get install python-gconf
sudo apt-get install python-gdbm
sudo apt-get install python-gi
sudo apt-get install python-gi-cairo
sudo apt-get install python-gnomekeyring
sudo apt-get install python-gnupginterface
sudo apt-get install python-gobject
sudo apt-get install python-gobject-2
sudo apt-get install python-gst0.10
sudo apt-get install python-gtk2
sudo apt-get install python-httplib2
sudo apt-get install python-ibus
sudo apt-get install python-imaging
sudo apt-get install python-keyring
sudo apt-get install python-launchpadlib
sudo apt-get install python-lazr.restfulclient
sudo apt-get install python-lazr.uri
sudo apt-get install python-libproxy
sudo apt-get install python-libxml2
sudo apt-get install python-louis
sudo apt-get install python-mako
sudo apt-get install python-markupsafe
sudo apt-get install python-minimal
sudo apt-get install python-notify
sudo apt-get install python-oauth
sudo apt-get install python-openssl
sudo apt-get install python-packagekit
sudo apt-get install python-pam
sudo apt-get install python-pexpect
sudo apt-get install python-piston-mini-client
sudo apt-get install python-pkg-resources
sudo apt-get install python-problem-report
sudo apt-get install python-protobuf
sudo apt-get install python-pyatspi2
sudo apt-get install python-pycurl
sudo apt-get install python-pyinotify
sudo apt-get install python-renderpm
sudo apt-get install python-reportlab
sudo apt-get install python-reportlab-accel
sudo apt-get install python-serial
sudo apt-get install python-simplejson
sudo apt-get install python-smbc
sudo apt-get install python-software-properties
sudo apt-get install python-speechd
sudo apt-get install python-twisted-bin
sudo apt-get install python-twisted-core
sudo apt-get install python-twisted-names
sudo apt-get install python-twisted-web
sudo apt-get install python-ubuntu-sso-client
sudo apt-get install python-ubuntuone-client
sudo apt-get install python-ubuntuone-control-panel
sudo apt-get install python-ubuntuone-storageprotocol
sudo apt-get install python-uno
sudo apt-get install python-virtkey
sudo apt-get install python-wadllib
sudo apt-get install python-xapian
sudo apt-get install python-xdg
sudo apt-get install python-xkit
sudo apt-get install python-zeitgeist
sudo apt-get install python-zope.interface
sudo apt-get install python2.7
sudo apt-get install python2.7-minimal
sudo apt-get install qdbus
sudo apt-get install qt-at-spi
sudo apt-get install radeontool
sudo apt-get install readline-common
sudo apt-get install remmina
sudo apt-get install remmina-common
sudo apt-get install remmina-plugin-rdp
sudo apt-get install remmina-plugin-vnc
sudo apt-get install resolvconf
sudo apt-get install rfkill
sudo apt-get install rhythmbox
sudo apt-get install rhythmbox-data
sudo apt-get install rhythmbox-mozilla
sudo apt-get install rhythmbox-plugin-cdrecorder
sudo apt-get install rhythmbox-plugin-magnatune
sudo apt-get install rhythmbox-plugin-zeitgeist
sudo apt-get install rhythmbox-plugins
sudo apt-get install rhythmbox-ubuntuone
sudo apt-get install rsync
sudo apt-get install rsyslog
sudo apt-get install rtkit
sudo apt-get install samba-common
sudo apt-get install samba-common-bin
sudo apt-get install sane-utils
sudo apt-get install seahorse
sudo apt-get install sed
sudo apt-get install sensible-utils
sudo apt-get install sessioninstaller
sudo apt-get install sgml-base
sudo apt-get install shared-mime-info
sudo apt-get install shotwell
sudo apt-get install simple-scan
sudo apt-get install smbclient
sudo apt-get install sni-qt
sudo apt-get install software-center
sudo apt-get install software-center-aptdaemon-plugins
sudo apt-get install software-properties-common
sudo apt-get install software-properties-gtk
sudo apt-get install sound-theme-freedesktop
sudo apt-get install speech-dispatcher
sudo apt-get install ssh-askpass-gnome
sudo apt-get install ssl-cert
sudo apt-get install strace
sudo apt-get install sudo
sudo apt-get install syslinux
sudo apt-get install syslinux-common
sudo apt-get install syslinux-legacy
sudo apt-get install system-config-printer-common
sudo apt-get install system-config-printer-gnome
sudo apt-get install system-config-printer-udev
sudo apt-get install sysv-rc
sudo apt-get install sysvinit-utils
sudo apt-get install tar
sudo apt-get install tcpd
sudo apt-get install tcpdump
sudo apt-get install telepathy-gabble
sudo apt-get install telepathy-haze
sudo apt-get install telepathy-idle
sudo apt-get install telepathy-indicator
sudo apt-get install telepathy-logger
sudo apt-get install telepathy-mission-control-5
sudo apt-get install telepathy-salut
sudo apt-get install telnet
sudo apt-get install thunderbird
sudo apt-get install thunderbird-globalmenu
sudo apt-get install thunderbird-gnome-support
sudo apt-get install time
sudo apt-get install toshset
sudo apt-get install totem
sudo apt-get install totem-common
sudo apt-get install totem-mozilla
sudo apt-get install totem-plugins
sudo apt-get install transmission-common
sudo apt-get install transmission-gtk
sudo apt-get install ttf-dejavu-core
sudo apt-get install ttf-freefont
sudo apt-get install ttf-indic-fonts-core
sudo apt-get install ttf-punjabi-fonts
sudo apt-get install ttf-ubuntu-font-family
sudo apt-get install ttf-wqy-microhei
sudo apt-get install tzdata
sudo apt-get install ubuntu-artwork
sudo apt-get install ubuntu-desktop
sudo apt-get install ubuntu-docs
sudo apt-get install ubuntu-extras-keyring
sudo apt-get install ubuntu-keyring
sudo apt-get install ubuntu-minimal
sudo apt-get install ubuntu-mono
sudo apt-get install ubuntu-sounds
sudo apt-get install ubuntu-sso-client
sudo apt-get install ubuntu-sso-client-gtk
sudo apt-get install ubuntu-standard
sudo apt-get install ubuntu-system-service
sudo apt-get install ubuntu-wallpapers
sudo apt-get install ubuntu-wallpapers-precise
sudo apt-get install ubuntuone-client
sudo apt-get install ubuntuone-client-gnome
sudo apt-get install ubuntuone-control-panel
sudo apt-get install ubuntuone-couch
sudo apt-get install ubuntuone-installer
sudo apt-get install ucf
sudo apt-get install udev
sudo apt-get install udisks
sudo apt-get install ufw
sudo apt-get install unattended-upgrades
sudo apt-get install unity
sudo apt-get install unity-2d
sudo apt-get install unity-2d-common
sudo apt-get install unity-2d-panel
sudo apt-get install unity-2d-shell
sudo apt-get install unity-2d-spread
sudo apt-get install unity-asset-pool
sudo apt-get install unity-common
sudo apt-get install unity-greeter
sudo apt-get install unity-lens-applications
sudo apt-get install unity-lens-files
sudo apt-get install unity-lens-music
sudo apt-get install unity-lens-video
sudo apt-get install unity-scope-musicstores
sudo apt-get install unity-scope-video-remote
sudo apt-get install unity-services
sudo apt-get install uno-libs3
sudo apt-get install unzip
sudo apt-get install update-inetd
sudo apt-get install update-manager
sudo apt-get install update-manager-core
sudo apt-get install update-notifier
sudo apt-get install update-notifier-common
sudo apt-get install upower
sudo apt-get install upstart
sudo apt-get install ure
sudo apt-get install ureadahead
sudo apt-get install usb-creator-common
sudo apt-get install usb-creator-gtk
sudo apt-get install usb-modeswitch
sudo apt-get install usb-modeswitch-data
sudo apt-get install usbmuxd
sudo apt-get install usbutils
sudo apt-get install util-linux
sudo apt-get install uuid-runtime
sudo apt-get install vbetool
sudo apt-get install vim-common
sudo apt-get install vim-tiny
sudo apt-get install vino
sudo apt-get install wamerican
sudo apt-get install wget
sudo apt-get install whiptail
sudo apt-get install whois
sudo apt-get install whoopsie
sudo apt-get install wireless-regdb
sudo apt-get install wireless-tools
sudo apt-get install wodim
sudo apt-get install wpasupplicant
sudo apt-get install x11-apps
sudo apt-get install x11-common
sudo apt-get install x11-session-utils
sudo apt-get install x11-utils
sudo apt-get install x11-xfs-utils
sudo apt-get install x11-xkb-utils
sudo apt-get install x11-xserver-utils
sudo apt-get install x11-xserver-utils-lts-quantal
sudo apt-get install xauth
sudo apt-get install xbitmaps
sudo apt-get install xcursor-themes
sudo apt-get install xdg-user-dirs
sudo apt-get install xdg-user-dirs-gtk
sudo apt-get install xdg-utils
sudo apt-get install xdiagnose
sudo apt-get install xfonts-base
sudo apt-get install xfonts-encodings
sudo apt-get install xfonts-mathml
sudo apt-get install xfonts-scalable
sudo apt-get install xfonts-utils
sudo apt-get install xinit
sudo apt-get install xinput
sudo apt-get install xkb-data
sudo apt-get install xml-core
sudo apt-get install xorg
sudo apt-get install xorg-docs-core
sudo apt-get install xserver-common
sudo apt-get install xserver-common-lts-quantal
sudo apt-get install xserver-xorg-core-lts-quantal
sudo apt-get install xserver-xorg-input-all-lts-quantal
sudo apt-get install xserver-xorg-input-evdev-lts-quantal
sudo apt-get install xserver-xorg-input-mouse-lts-quantal
sudo apt-get install xserver-xorg-input-synaptics-lts-quantal
sudo apt-get install xserver-xorg-input-vmmouse-lts-quantal
sudo apt-get install xserver-xorg-input-wacom-lts-quantal
sudo apt-get install xserver-xorg-lts-quantal
sudo apt-get install xserver-xorg-video-all-lts-quantal
sudo apt-get install xserver-xorg-video-ati-lts-quantal
sudo apt-get install xserver-xorg-video-cirrus-lts-quantal
sudo apt-get install xserver-xorg-video-fbdev-lts-quantal
sudo apt-get install xserver-xorg-video-intel-lts-quantal
sudo apt-get install xserver-xorg-video-mach64-lts-quantal
sudo apt-get install xserver-xorg-video-mga-lts-quantal
sudo apt-get install xserver-xorg-video-modesetting-lts-quantal
sudo apt-get install xserver-xorg-video-neomagic-lts-quantal
sudo apt-get install xserver-xorg-video-nouveau-lts-quantal
sudo apt-get install xserver-xorg-video-openchrome-lts-quantal
sudo apt-get install xserver-xorg-video-r128-lts-quantal
sudo apt-get install xserver-xorg-video-radeon-lts-quantal
sudo apt-get install xserver-xorg-video-s3-lts-quantal
sudo apt-get install xserver-xorg-video-savage-lts-quantal
sudo apt-get install xserver-xorg-video-siliconmotion-lts-quantal
sudo apt-get install xserver-xorg-video-sis-lts-quantal
sudo apt-get install xserver-xorg-video-sisusb-lts-quantal
sudo apt-get install xserver-xorg-video-tdfx-lts-quantal
sudo apt-get install xserver-xorg-video-trident-lts-quantal
sudo apt-get install xserver-xorg-video-vesa-lts-quantal
sudo apt-get install xserver-xorg-video-vmware-lts-quantal
sudo apt-get install xterm
sudo apt-get install xul-ext-ubufox
sudo apt-get install xz-lzma
sudo apt-get install xz-utils
sudo apt-get install yelp
sudo apt-get install yelp-xsl
sudo apt-get install zeitgeist
sudo apt-get install zeitgeist-core
sudo apt-get install zeitgeist-datahub
sudo apt-get install zenity
sudo apt-get install zenity-common
sudo apt-get install zip
sudo apt-get install zlib1g
