sudo apt-get install -y accountsservice
sudo apt-get install -y acl
sudo apt-get install -y acpi-support
sudo apt-get install -y acpid
sudo apt-get install -y activity-log-manager-common
sudo apt-get install -y activity-log-manager-control-center
sudo apt-get install -y adduser
sudo apt-get install -y adium-theme-ubuntu
sudo apt-get install -y aisleriot
sudo apt-get install -y alsa-base
sudo apt-get install -y alsa-utils
sudo apt-get install -y anacron
sudo apt-get install -y apg
sudo apt-get install -y app-install-data
sudo apt-get install -y app-install-data-partner
sudo apt-get install -y apparmor
sudo apt-get install -y appmenu-gtk
sudo apt-get install -y appmenu-gtk3
sudo apt-get install -y appmenu-qt
sudo apt-get install -y apport
sudo apt-get install -y apport-gtk
sudo apt-get install -y apport-symptoms
sudo apt-get install -y apt
sudo apt-get install -y apt-transport-https
sudo apt-get install -y apt-utils
sudo apt-get install -y apt-xapian-index
sudo apt-get install -y aptdaemon
sudo apt-get install -y aptdaemon-data
sudo apt-get install -y apturl
sudo apt-get install -y apturl-common
sudo apt-get install -y aspell
sudo apt-get install -y aspell-en
sudo apt-get install -y at
sudo apt-get install -y at-spi2-core
sudo apt-get install -y avahi-autoipd
sudo apt-get install -y avahi-daemon
sudo apt-get install -y avahi-utils
sudo apt-get install -y bamfdaemon
sudo apt-get install -y baobab
sudo apt-get install -y base-files
sudo apt-get install -y base-passwd
sudo apt-get install -y bash
sudo apt-get install -y bash-completion
sudo apt-get install -y bc
sudo apt-get install -y bind9-host
sudo apt-get install -y binutils
sudo apt-get install -y bluez
sudo apt-get install -y bluez-alsa
sudo apt-get install -y bluez-cups
sudo apt-get install -y bluez-gstreamer
sudo apt-get install -y branding-ubuntu
sudo apt-get install -y brasero
sudo apt-get install -y brasero-cdrkit
sudo apt-get install -y brasero-common
sudo apt-get install -y brltty
sudo apt-get install -y bsdmainutils
sudo apt-get install -y bsdutils
sudo apt-get install -y busybox-initramfs
sudo apt-get install -y busybox-static
sudo apt-get install -y bzip2
sudo apt-get install -y ca-certificates
sudo apt-get install -y checkbox
sudo apt-get install -y checkbox-qt
sudo apt-get install -y cmap-adobe-japan2
sudo apt-get install -y colord
sudo apt-get install -y command-not-found
sudo apt-get install -y command-not-found-data
sudo apt-get install -y compiz
sudo apt-get install -y compiz-core
sudo apt-get install -y compiz-gnome
sudo apt-get install -y compiz-plugins-default
sudo apt-get install -y compiz-plugins-main-default
sudo apt-get install -y compizconfig-backend-gconf
sudo apt-get install -y console-setup
sudo apt-get install -y consolekit
sudo apt-get install -y coreutils
sudo apt-get install -y cpio
sudo apt-get install -y cpp
sudo apt-get install -y cpp-4.6
sudo apt-get install -y crda
sudo apt-get install -y cron
sudo apt-get install -y cryptsetup-bin
sudo apt-get install -y cups
sudo apt-get install -y cups-bsd
sudo apt-get install -y cups-client
sudo apt-get install -y cups-common
sudo apt-get install -y cups-filters
sudo apt-get install -y cups-ppdc
sudo apt-get install -y dash
sudo apt-get install -y dbus
sudo apt-get install -y dbus-x11
sudo apt-get install -y dc
sudo apt-get install -y dconf-gsettings-backend
sudo apt-get install -y dconf-service
sudo apt-get install -y debconf
sudo apt-get install -y debconf-i18n
sudo apt-get install -y debianutils
sudo apt-get install -y deja-dup
sudo apt-get install -y desktop-file-utils
sudo apt-get install -y dictionaries-common
sudo apt-get install -y diffutils
sudo apt-get install -y dmidecode
sudo apt-get install -y dmsetup
sudo apt-get install -y dmz-cursor-theme
sudo apt-get install -y dnsmasq-base
sudo apt-get install -y dnsutils
sudo apt-get install -y doc-base
sudo apt-get install -y dosfstools
sudo apt-get install -y dpkg
sudo apt-get install -y duplicity
sudo apt-get install -y dvd+rw-tools
sudo apt-get install -y e2fslibs
sudo apt-get install -y e2fsprogs
sudo apt-get install -y ed
sudo apt-get install -y eject
sudo apt-get install -y empathy
sudo apt-get install -y empathy-common
sudo apt-get install -y enchant
sudo apt-get install -y eog
sudo apt-get install -y espeak
sudo apt-get install -y espeak-data
sudo apt-get install -y evince
sudo apt-get install -y evince-common
sudo apt-get install -y evolution-data-server
sudo apt-get install -y evolution-data-server-common
sudo apt-get install -y example-content
sudo apt-get install -y file
sudo apt-get install -y file-roller
sudo apt-get install -y findutils
sudo apt-get install -y firefox
sudo apt-get install -y firefox-globalmenu
sudo apt-get install -y firefox-gnome-support
sudo apt-get install -y firefox-locale-en
sudo apt-get install -y folks-common
sudo apt-get install -y fontconfig
sudo apt-get install -y fontconfig-config
sudo apt-get install -y fonts-kacst
sudo apt-get install -y fonts-kacst-one
sudo apt-get install -y fonts-khmeros-core
sudo apt-get install -y fonts-lao
sudo apt-get install -y fonts-liberation
sudo apt-get install -y fonts-nanum
sudo apt-get install -y fonts-opensymbol
sudo apt-get install -y fonts-takao-pgothic
sudo apt-get install -y fonts-thai-tlwg
sudo apt-get install -y fonts-tlwg-garuda
sudo apt-get install -y fonts-tlwg-kinnari
sudo apt-get install -y fonts-tlwg-loma
sudo apt-get install -y fonts-tlwg-mono
sudo apt-get install -y fonts-tlwg-norasi
sudo apt-get install -y fonts-tlwg-purisa
sudo apt-get install -y fonts-tlwg-sawasdee
sudo apt-get install -y fonts-tlwg-typewriter
sudo apt-get install -y fonts-tlwg-typist
sudo apt-get install -y fonts-tlwg-typo
sudo apt-get install -y fonts-tlwg-umpush
sudo apt-get install -y fonts-tlwg-waree
sudo apt-get install -y foomatic-db-compressed-ppds
sudo apt-get install -y foomatic-db-engine
sudo apt-get install -y foomatic-filters
sudo apt-get install -y friendly-recovery
sudo apt-get install -y ftp
sudo apt-get install -y fuse
sudo apt-get install -y gcalctool
sudo apt-get install -y gcc
sudo apt-get install -y gcc-4.6
sudo apt-get install -y gcc-4.6-base
sudo apt-get install -y gconf-service
sudo apt-get install -y gconf-service-backend
sudo apt-get install -y gconf2
sudo apt-get install -y gconf2-common
sudo apt-get install -y gdb
sudo apt-get install -y gedit
sudo apt-get install -y gedit-common
sudo apt-get install -y genisoimage
sudo apt-get install -y geoclue
sudo apt-get install -y geoclue-ubuntu-geoip
sudo apt-get install -y geoip-database
sudo apt-get install -y gettext-base
sudo apt-get install -y ghostscript
sudo apt-get install -y ghostscript-cups
sudo apt-get install -y ghostscript-x
sudo apt-get install -y ginn
sudo apt-get install -y gir1.2-appindicator3-0.1
sudo apt-get install -y gir1.2-atk-1.0
sudo apt-get install -y gir1.2-atspi-2.0
sudo apt-get install -y gir1.2-dbusmenu-glib-0.4
sudo apt-get install -y gir1.2-dbusmenu-gtk-0.4
sudo apt-get install -y gir1.2-dee-1.0
sudo apt-get install -y gir1.2-freedesktop
sudo apt-get install -y gir1.2-gdkpixbuf-2.0
sudo apt-get install -y gir1.2-glib-2.0
sudo apt-get install -y gir1.2-gmenu-3.0
sudo apt-get install -y gir1.2-gnomebluetooth-1.0
sudo apt-get install -y gir1.2-gnomekeyring-1.0
sudo apt-get install -y gir1.2-gst-plugins-base-0.10
sudo apt-get install -y gir1.2-gstreamer-0.10
sudo apt-get install -y gir1.2-gtk-2.0
sudo apt-get install -y gir1.2-gtk-3.0
sudo apt-get install -y gir1.2-gtksource-3.0
sudo apt-get install -y gir1.2-gudev-1.0
sudo apt-get install -y gir1.2-indicate-0.7
sudo apt-get install -y gir1.2-javascriptcoregtk-3.0
sudo apt-get install -y gir1.2-launchpad-integration-3.0
sudo apt-get install -y gir1.2-notify-0.7
sudo apt-get install -y gir1.2-pango-1.0
sudo apt-get install -y gir1.2-peas-1.0
sudo apt-get install -y gir1.2-rb-3.0
sudo apt-get install -y gir1.2-soup-2.4
sudo apt-get install -y gir1.2-totem-1.0
sudo apt-get install -y gir1.2-totem-plparser-1.0
sudo apt-get install -y gir1.2-ubuntuoneui-3.0
sudo apt-get install -y gir1.2-unity-5.0
sudo apt-get install -y gir1.2-vte-2.90
sudo apt-get install -y gir1.2-webkit-3.0
sudo apt-get install -y gir1.2-wnck-3.0
sudo apt-get install -y gksu
sudo apt-get install -y glib-networking
sudo apt-get install -y glib-networking-common
sudo apt-get install -y glib-networking-services
sudo apt-get install -y gnome-accessibility-themes
sudo apt-get install -y gnome-bluetooth
sudo apt-get install -y gnome-control-center
sudo apt-get install -y gnome-control-center-data
sudo apt-get install -y gnome-desktop3-data
sudo apt-get install -y gnome-disk-utility
sudo apt-get install -y gnome-font-viewer
sudo apt-get install -y gnome-games-data
sudo apt-get install -y gnome-icon-theme
sudo apt-get install -y gnome-icon-theme-symbolic
sudo apt-get install -y gnome-keyring
sudo apt-get install -y gnome-media
sudo apt-get install -y gnome-menus
sudo apt-get install -y gnome-nettool
sudo apt-get install -y gnome-online-accounts
sudo apt-get install -y gnome-orca
sudo apt-get install -y gnome-power-manager
sudo apt-get install -y gnome-screensaver
sudo apt-get install -y gnome-screenshot
sudo apt-get install -y gnome-session
sudo apt-get install -y gnome-session-bin
sudo apt-get install -y gnome-session-canberra
sudo apt-get install -y gnome-session-common
sudo apt-get install -y gnome-settings-daemon
sudo apt-get install -y gnome-sudoku
sudo apt-get install -y gnome-system-log
sudo apt-get install -y gnome-system-monitor
sudo apt-get install -y gnome-terminal
sudo apt-get install -y gnome-terminal-data
sudo apt-get install -y gnome-user-guide
sudo apt-get install -y gnome-user-share
sudo apt-get install -y gnomine
sudo apt-get install -y gnupg
sudo apt-get install -y gpgv
sudo apt-get install -y grep
sudo apt-get install -y groff-base
sudo apt-get install -y growisofs
sudo apt-get install -y grub-common
sudo apt-get install -y grub-gfxpayload-lists
sudo apt-get install -y grub-pc
sudo apt-get install -y grub-pc-bin
sudo apt-get install -y grub2-common
sudo apt-get install -y gs-cjk-resource
sudo apt-get install -y gsettings-desktop-schemas
sudo apt-get install -y gsfonts
sudo apt-get install -y gstreamer0.10-alsa
sudo apt-get install -y gstreamer0.10-gconf
sudo apt-get install -y gstreamer0.10-nice
sudo apt-get install -y gstreamer0.10-plugins-base
sudo apt-get install -y gstreamer0.10-plugins-base-apps
sudo apt-get install -y gstreamer0.10-plugins-good
sudo apt-get install -y gstreamer0.10-pulseaudio
sudo apt-get install -y gstreamer0.10-tools
sudo apt-get install -y gstreamer0.10-x
sudo apt-get install -y gtk2-engines
sudo apt-get install -y gtk2-engines-murrine
sudo apt-get install -y gtk3-engines-unico
sudo apt-get install -y gucharmap
sudo apt-get install -y guile-1.8-libs
sudo apt-get install -y gvfs
sudo apt-get install -y gvfs-backends
sudo apt-get install -y gvfs-bin
sudo apt-get install -y gvfs-common
sudo apt-get install -y gvfs-daemons
sudo apt-get install -y gvfs-fuse
sudo apt-get install -y gvfs-libs
sudo apt-get install -y gwibber
sudo apt-get install -y gwibber-service
sudo apt-get install -y gwibber-service-facebook
sudo apt-get install -y gwibber-service-identica
sudo apt-get install -y gwibber-service-twitter
sudo apt-get install -y gzip
sudo apt-get install -y hdparm
sudo apt-get install -y hicolor-icon-theme
sudo apt-get install -y hostname
sudo apt-get install -y hplip
sudo apt-get install -y hplip-data
sudo apt-get install -y humanity-icon-theme
sudo apt-get install -y hunspell-en-us
sudo apt-get install -y hwdata
sudo apt-get install -y ibus
sudo apt-get install -y ibus-gtk
sudo apt-get install -y ibus-gtk3
sudo apt-get install -y ibus-pinyin
sudo apt-get install -y ibus-pinyin-db-android
sudo apt-get install -y ibus-table
sudo apt-get install -y ifupdown
sudo apt-get install -y im-switch
sudo apt-get install -y indicator-application
sudo apt-get install -y indicator-appmenu
sudo apt-get install -y indicator-datetime
sudo apt-get install -y indicator-messages
sudo apt-get install -y indicator-power
sudo apt-get install -y indicator-printers
sudo apt-get install -y indicator-session
sudo apt-get install -y indicator-sound
sudo apt-get install -y indicator-status-provider-mc5
sudo apt-get install -y info
sudo apt-get install -y initramfs-tools
sudo apt-get install -y initramfs-tools-bin
sudo apt-get install -y initscripts
sudo apt-get install -y inputattach
sudo apt-get install -y insserv
sudo apt-get install -y install-info
sudo apt-get install -y intel-gpu-tools
sudo apt-get install -y iproute
sudo apt-get install -y iptables
sudo apt-get install -y iputils-arping
sudo apt-get install -y iputils-ping
sudo apt-get install -y iputils-tracepath
sudo apt-get install -y irqbalance
sudo apt-get install -y isc-dhcp-client
sudo apt-get install -y isc-dhcp-common
sudo apt-get install -y iso-codes
sudo apt-get install -y iw
sudo apt-get install -y jockey-common
sudo apt-get install -y jockey-gtk
sudo apt-get install -y kbd
sudo apt-get install -y kerneloops-daemon
sudo apt-get install -y keyboard-configuration
sudo apt-get install -y klibc-utils
sudo apt-get install -y krb5-locales
sudo apt-get install -y landscape-client-ui-install
sudo apt-get install -y language-pack-en
sudo apt-get install -y language-pack-en-base
sudo apt-get install -y language-pack-gnome-en
sudo apt-get install -y language-pack-gnome-en-base
sudo apt-get install -y language-selector-common
sudo apt-get install -y language-selector-gnome
sudo apt-get install -y laptop-detect
sudo apt-get install -y launchpad-integration
sudo apt-get install -y less
sudo apt-get install -y libaa1
sudo apt-get install -y libaccountsservice0
sudo apt-get install -y libacl1
sudo apt-get install -y libappindicator1
sudo apt-get install -y libappindicator3-1
sudo apt-get install -y libapt-inst1.4
sudo apt-get install -y libapt-pkg4.12
sudo apt-get install -y libarchive12
sudo apt-get install -y libart-2.0-2
sudo apt-get install -y libasn1-8-heimdal
sudo apt-get install -y libasound2
sudo apt-get install -y libasound2-plugins
sudo apt-get install -y libaspell15
sudo apt-get install -y libasyncns0
sudo apt-get install -y libatasmart4
sudo apt-get install -y libatk-adaptor
sudo apt-get install -y libatk-adaptor-schemas
sudo apt-get install -y libatk1.0-0
sudo apt-get install -y libatk1.0-data
sudo apt-get install -y libatkmm-1.6-1
sudo apt-get install -y libatspi2.0-0
sudo apt-get install -y libattr1
sudo apt-get install -y libaudio2
sudo apt-get install -y libavahi-client3
sudo apt-get install -y libavahi-common-data
sudo apt-get install -y libavahi-common3
sudo apt-get install -y libavahi-core7
sudo apt-get install -y libavahi-glib1
sudo apt-get install -y libavahi-gobject0
sudo apt-get install -y libavahi-ui-gtk3-0
sudo apt-get install -y libavc1394-0
sudo apt-get install -y libbamf0
sudo apt-get install -y libbamf3-0
sudo apt-get install -y libbind9-80
sudo apt-get install -y libblkid1
sudo apt-get install -y libbluetooth3
sudo apt-get install -y libboost-serialization1.46.1
sudo apt-get install -y libbrasero-media3-1
sudo apt-get install -y libbrlapi0.5
sudo apt-get install -y libbsd0
sudo apt-get install -y libburn4
sudo apt-get install -y libbz2-1.0
sudo apt-get install -y libc-bin
sudo apt-get install -y libc-dev-bin
sudo apt-get install -y libc6
sudo apt-get install -y libc6-dev
sudo apt-get install -y libcaca0
sudo apt-get install -y libcairo-gobject2
sudo apt-get install -y libcairo-perl
sudo apt-get install -y libcairo2
sudo apt-get install -y libcairomm-1.0-1
sudo apt-get install -y libcamel-1.2-29
sudo apt-get install -y libcanberra-gtk-module
sudo apt-get install -y libcanberra-gtk0
sudo apt-get install -y libcanberra-gtk3-0
sudo apt-get install -y libcanberra-gtk3-module
sudo apt-get install -y libcanberra-pulse
sudo apt-get install -y libcanberra0
sudo apt-get install -y libcap-ng0
sudo apt-get install -y libcap2
sudo apt-get install -y libcap2-bin
sudo apt-get install -y libcdio-cdda1
sudo apt-get install -y libcdio-paranoia1
sudo apt-get install -y libcdio13
sudo apt-get install -y libcdparanoia0
sudo apt-get install -y libck-connector0
sudo apt-get install -y libclass-isa-perl
sudo apt-get install -y libcmis-0.2-0
sudo apt-get install -y libcolord1
sudo apt-get install -y libcomerr2
sudo apt-get install -y libcompizconfig0
sudo apt-get install -y libcroco3
sudo apt-get install -y libcrypt-passwdmd5-perl
sudo apt-get install -y libcryptsetup4
sudo apt-get install -y libcups2
sudo apt-get install -y libcupscgi1
sudo apt-get install -y libcupsdriver1
sudo apt-get install -y libcupsfilters1
sudo apt-get install -y libcupsimage2
sudo apt-get install -y libcupsmime1
sudo apt-get install -y libcupsppdc1
sudo apt-get install -y libcurl3
sudo apt-get install -y libcurl3-gnutls
sudo apt-get install -y libcurl3-nss
sudo apt-get install -y libdaemon0
sudo apt-get install -y libdatrie1
sudo apt-get install -y libdb5.1
sudo apt-get install -y libdbus-1-3
sudo apt-get install -y libdbus-glib-1-2
sudo apt-get install -y libdbusmenu-glib4
sudo apt-get install -y libdbusmenu-gtk3-4
sudo apt-get install -y libdbusmenu-gtk4
sudo apt-get install -y libdbusmenu-qt2
sudo apt-get install -y libdconf-dbus-1-0
sudo apt-get install -y libdconf-qt0
sudo apt-get install -y libdconf0
sudo apt-get install -y libdecoration0
sudo apt-get install -y libdee-1.0-4
sudo apt-get install -y libdevmapper-event1.02.1
sudo apt-get install -y libdevmapper1.02.1
sudo apt-get install -y libdiscid0
sudo apt-get install -y libdjvulibre-text
sudo apt-get install -y libdjvulibre21
sudo apt-get install -y libdmapsharing-3.0-2
sudo apt-get install -y libdns81
sudo apt-get install -y libdotconf1.0
sudo apt-get install -y libdrm-intel1
sudo apt-get install -y libdrm-nouveau1a
sudo apt-get install -y libdrm-nouveau2
sudo apt-get install -y libdrm-radeon1
sudo apt-get install -y libdrm2
sudo apt-get install -y libdv4
sudo apt-get install -y libebackend-1.2-1
sudo apt-get install -y libebook-1.2-12
sudo apt-get install -y libecal-1.2-10
sudo apt-get install -y libedata-book-1.2-11
sudo apt-get install -y libedata-cal-1.2-13
sudo apt-get install -y libedataserver-1.2-15
sudo apt-get install -y libedataserverui-3.0-1
sudo apt-get install -y libedit2
sudo apt-get install -y libelf1
sudo apt-get install -y libenchant1c2a
sudo apt-get install -y libespeak1
sudo apt-get install -y libevent-2.0-5
sudo apt-get install -y libevince3-3
sudo apt-get install -y libexempi3
sudo apt-get install -y libexif12
sudo apt-get install -y libexiv2-11
sudo apt-get install -y libexpat1
sudo apt-get install -y libexttextcat-data
sudo apt-get install -y libexttextcat0
sudo apt-get install -y libfarstream-0.1-0
sudo apt-get install -y libffi6
sudo apt-get install -y libfile-basedir-perl
sudo apt-get install -y libfile-copy-recursive-perl
sudo apt-get install -y libfile-desktopentry-perl
sudo apt-get install -y libfile-mimeinfo-perl
sudo apt-get install -y libflac8
sudo apt-get install -y libfolks-eds25
sudo apt-get install -y libfolks-telepathy25
sudo apt-get install -y libfolks25
sudo apt-get install -y libfontconfig1
sudo apt-get install -y libfontenc1
sudo apt-get install -y libframe6
sudo apt-get install -y libfreerdp-plugins-standard
sudo apt-get install -y libfreerdp1
sudo apt-get install -y libfreetype6
sudo apt-get install -y libfribidi0
sudo apt-get install -y libfs6
sudo apt-get install -y libfuse2
sudo apt-get install -y libgail-3-0
sudo apt-get install -y libgail-common
sudo apt-get install -y libgail18
sudo apt-get install -y libgcc1
sudo apt-get install -y libgck-1-0
sudo apt-get install -y libgconf-2-4
sudo apt-get install -y libgconf2-4
sudo apt-get install -y libgcr-3-1
sudo apt-get install -y libgcr-3-common
sudo apt-get install -y libgcrypt11
sudo apt-get install -y libgd2-xpm
sudo apt-get install -y libgdata-common
sudo apt-get install -y libgdata13
sudo apt-get install -y libgdbm3
sudo apt-get install -y libgdk-pixbuf2.0-0
sudo apt-get install -y libgdk-pixbuf2.0-common
sudo apt-get install -y libgdu-gtk0
sudo apt-get install -y libgdu0
sudo apt-get install -y libgee2
sudo apt-get install -y libgeis1
sudo apt-get install -y libgeoclue0
sudo apt-get install -y libgeoip1
sudo apt-get install -y libgexiv2-1
sudo apt-get install -y libgirepository-1.0-1
sudo apt-get install -y libgksu2-0
sudo apt-get install -y libgl1-mesa-dri-lts-precise
sudo apt-get install -y libgl1-mesa-glx-lts-precise
sudo apt-get install -y libglapi-mesa-lts-precise
sudo apt-get install -y libglew1.6
sudo apt-get install -y libglewmx1.6
sudo apt-get install -y libglib-perl
sudo apt-get install -y libglib2.0-0
sudo apt-get install -y libglib2.0-bin
sudo apt-get install -y libglib2.0-data
sudo apt-get install -y libglibmm-2.4-1c2a
sudo apt-get install -y libglu1-mesa
sudo apt-get install -y libgmime-2.6-0
sudo apt-get install -y libgmp10
sudo apt-get install -y libgnome-bluetooth8
sudo apt-get install -y libgnome-control-center1
sudo apt-get install -y libgnome-desktop-3-2
sudo apt-get install -y libgnome-keyring-common
sudo apt-get install -y libgnome-keyring0
sudo apt-get install -y libgnome-media-profiles-3.0-0
sudo apt-get install -y libgnome-menu-3-0
sudo apt-get install -y libgnome-menu2
sudo apt-get install -y libgnome2-common
sudo apt-get install -y libgnomekbd-common
sudo apt-get install -y libgnomekbd7
sudo apt-get install -y libgnutls26
sudo apt-get install -y libgoa-1.0-0
sudo apt-get install -y libgoa-1.0-common
sudo apt-get install -y libgomp1
sudo apt-get install -y libgpg-error0
sudo apt-get install -y libgpgme11
sudo apt-get install -y libgphoto2-2
sudo apt-get install -y libgphoto2-l10n
sudo apt-get install -y libgphoto2-port0
sudo apt-get install -y libgpm2
sudo apt-get install -y libgpod-common
sudo apt-get install -y libgpod4
sudo apt-get install -y libgrail5
sudo apt-get install -y libgrip0
sudo apt-get install -y libgs9
sudo apt-get install -y libgs9-common
sudo apt-get install -y libgssapi-krb5-2
sudo apt-get install -y libgssapi3-heimdal
sudo apt-get install -y libgssdp-1.0-3
sudo apt-get install -y libgstreamer-plugins-base0.10-0
sudo apt-get install -y libgstreamer0.10-0
sudo apt-get install -y libgtk-3-0
sudo apt-get install -y libgtk-3-bin
sudo apt-get install -y libgtk-3-common
sudo apt-get install -y libgtk2-perl
sudo apt-get install -y libgtk2.0-0
sudo apt-get install -y libgtk2.0-bin
sudo apt-get install -y libgtk2.0-common
sudo apt-get install -y libgtkmm-3.0-1
sudo apt-get install -y libgtksourceview-3.0-0
sudo apt-get install -y libgtksourceview-3.0-common
sudo apt-get install -y libgtkspell-3-0
sudo apt-get install -y libgtop2-7
sudo apt-get install -y libgtop2-common
sudo apt-get install -y libgucharmap-2-90-7
sudo apt-get install -y libgudev-1.0-0
sudo apt-get install -y libgupnp-1.0-4
sudo apt-get install -y libgupnp-igd-1.0-4
sudo apt-get install -y libgutenprint2
sudo apt-get install -y libgweather-3-0
sudo apt-get install -y libgweather-common
sudo apt-get install -y libgwibber-gtk2
sudo apt-get install -y libgwibber2
sudo apt-get install -y libhcrypto4-heimdal
sudo apt-get install -y libheimbase1-heimdal
sudo apt-get install -y libheimntlm0-heimdal
sudo apt-get install -y libhpmud0
sudo apt-get install -y libhunspell-1.3-0
sudo apt-get install -y libhx509-5-heimdal
sudo apt-get install -y libhyphen0
sudo apt-get install -y libibus-1.0-0
sudo apt-get install -y libical0
sudo apt-get install -y libice6
sudo apt-get install -y libicu48
sudo apt-get install -y libidn11
sudo apt-get install -y libido3-0.1-0
sudo apt-get install -y libiec61883-0
sudo apt-get install -y libieee1284-3
sudo apt-get install -y libijs-0.35
sudo apt-get install -y libimobiledevice2
sudo apt-get install -y libindicate-gtk3
sudo apt-get install -y libindicate5
sudo apt-get install -y libindicator-messages-status-provider1
sudo apt-get install -y libindicator3-7
sudo apt-get install -y libindicator7
sudo apt-get install -y libisc83
sudo apt-get install -y libisccc80
sudo apt-get install -y libisccfg82
sudo apt-get install -y libisofs6
sudo apt-get install -y libiw30
sudo apt-get install -y libjack-jackd2-0
sudo apt-get install -y libjasper1
sudo apt-get install -y libjavascriptcoregtk-3.0-0
sudo apt-get install -y libjbig2dec0
sudo apt-get install -y libjpeg-turbo8
sudo apt-get install -y libjpeg8
sudo apt-get install -y libjs-jquery
sudo apt-get install -y libjson-glib-1.0-0
sudo apt-get install -y libjson0
sudo apt-get install -y libjte1
sudo apt-get install -y libk5crypto3
sudo apt-get install -y libkeyutils1
sudo apt-get install -y libklibc
sudo apt-get install -y libkpathsea5
sudo apt-get install -y libkrb5-26-heimdal
sudo apt-get install -y libkrb5-3
sudo apt-get install -y libkrb5support0
sudo apt-get install -y liblaunchpad-integration-3.0-1
sudo apt-get install -y liblaunchpad-integration-common
sudo apt-get install -y liblcms1
sudo apt-get install -y liblcms2-2
sudo apt-get install -y libldap-2.4-2
sudo apt-get install -y liblightdm-gobject-1-0
sudo apt-get install -y liblircclient0
sudo apt-get install -y libllvm3.1
sudo apt-get install -y liblocale-gettext-perl
sudo apt-get install -y liblockfile-bin
sudo apt-get install -y liblockfile1
sudo apt-get install -y liblouis-data
sudo apt-get install -y liblouis2
sudo apt-get install -y libltdl7
sudo apt-get install -y liblua5.1-0
sudo apt-get install -y liblvm2app2.2
sudo apt-get install -y liblwres80
sudo apt-get install -y liblzma5
sudo apt-get install -y libmagic1
sudo apt-get install -y libmeanwhile1
sudo apt-get install -y libmetacity-private0
sudo apt-get install -y libmhash2
sudo apt-get install -y libminiupnpc8
sudo apt-get install -y libmission-control-plugins0
sudo apt-get install -y libmng1
sudo apt-get install -y libmount1
sudo apt-get install -y libmpc2
sudo apt-get install -y libmpfr4
sudo apt-get install -y libmtdev1
sudo apt-get install -y libmtp-common
sudo apt-get install -y libmtp-runtime
sudo apt-get install -y libmtp9
sudo apt-get install -y libmusicbrainz3-6
sudo apt-get install -y libmythes-1.2-0
sudo apt-get install -y libnautilus-extension1a
sudo apt-get install -y libncurses5
sudo apt-get install -y libncursesw5
sudo apt-get install -y libneon27-gnutls
sudo apt-get install -y libnetfilter-conntrack3
sudo apt-get install -y libnettle4
sudo apt-get install -y libnewt0.52
sudo apt-get install -y libnfnetlink0
sudo apt-get install -y libnice10
sudo apt-get install -y libnih-dbus1
sudo apt-get install -y libnih1
sudo apt-get install -y libnl-3-200
sudo apt-get install -y libnl-genl-3-200
sudo apt-get install -y libnl-route-3-200
sudo apt-get install -y libnm-glib-vpn1
sudo apt-get install -y libnm-glib4
sudo apt-get install -y libnm-gtk-common
sudo apt-get install -y libnm-gtk0
sudo apt-get install -y libnm-util2
sudo apt-get install -y libnotify-bin
sudo apt-get install -y libnotify4
sudo apt-get install -y libnspr4
sudo apt-get install -y libnss-mdns
sudo apt-get install -y libnss3
sudo apt-get install -y libnux-2.0-0
sudo apt-get install -y libnux-2.0-common
sudo apt-get install -y liboauth0
sudo apt-get install -y libogg0
sudo apt-get install -y libopencc1
sudo apt-get install -y libopenobex1
sudo apt-get install -y liborc-0.4-0
sudo apt-get install -y liboverlay-scrollbar-0.2-0
sudo apt-get install -y liboverlay-scrollbar3-0.2-0
sudo apt-get install -y libp11-kit0
sudo apt-get install -y libpackagekit-glib2-14
sudo apt-get install -y libpam-cap
sudo apt-get install -y libpam-ck-connector
sudo apt-get install -y libpam-gnome-keyring
sudo apt-get install -y libpam-modules
sudo apt-get install -y libpam-modules-bin
sudo apt-get install -y libpam-runtime
sudo apt-get install -y libpam0g
sudo apt-get install -y libpango-perl
sudo apt-get install -y libpango1.0-0
sudo apt-get install -y libpangomm-1.4-1
sudo apt-get install -y libpaper-utils
sudo apt-get install -y libpaper1
sudo apt-get install -y libparted0debian1
sudo apt-get install -y libpcap0.8
sudo apt-get install -y libpci3
sudo apt-get install -y libpciaccess0
sudo apt-get install -y libpcre3
sudo apt-get install -y libpcsclite1
sudo apt-get install -y libpeas-1.0-0
sudo apt-get install -y libpeas-common
sudo apt-get install -y libperl5.14
sudo apt-get install -y libpipeline1
sudo apt-get install -y libpixman-1-0
sudo apt-get install -y libplist1
sudo apt-get install -y libplymouth2
sudo apt-get install -y libpng12-0
sudo apt-get install -y libpolkit-agent-1-0
sudo apt-get install -y libpolkit-backend-1-0
sudo apt-get install -y libpolkit-gobject-1-0
sudo apt-get install -y libpoppler-glib8
sudo apt-get install -y libpoppler19
sudo apt-get install -y libpopt0
sudo apt-get install -y libportaudio2
sudo apt-get install -y libprotobuf7
sudo apt-get install -y libprotoc7
sudo apt-get install -y libproxy1
sudo apt-get install -y libproxy1-plugin-gsettings
sudo apt-get install -y libproxy1-plugin-networkmanager
sudo apt-get install -y libpth20
sudo apt-get install -y libpulse-mainloop-glib0
sudo apt-get install -y libpulse0
sudo apt-get install -y libpulsedsp
sudo apt-get install -y libpurple-bin
sudo apt-get install -y libpurple0
sudo apt-get install -y libpython2.7
sudo apt-get install -y libqt4-dbus
sudo apt-get install -y libqt4-declarative
sudo apt-get install -y libqt4-network
sudo apt-get install -y libqt4-opengl
sudo apt-get install -y libqt4-script
sudo apt-get install -y libqt4-sql
sudo apt-get install -y libqt4-sql-sqlite
sudo apt-get install -y libqt4-svg
sudo apt-get install -y libqt4-xml
sudo apt-get install -y libqt4-xmlpatterns
sudo apt-get install -y libqtbamf1
sudo apt-get install -y libqtcore4
sudo apt-get install -y libqtdee2
sudo apt-get install -y libqtgconf1
sudo apt-get install -y libqtgui4
sudo apt-get install -y libquadmath0
sudo apt-get install -y libquvi-scripts
sudo apt-get install -y libquvi7
sudo apt-get install -y libraptor2-0
sudo apt-get install -y librasqal3
sudo apt-get install -y libraw1394-11
sudo apt-get install -y libraw5
sudo apt-get install -y librdf0
sudo apt-get install -y libreadline6
sudo apt-get install -y libreoffice-base-core
sudo apt-get install -y libreoffice-calc
sudo apt-get install -y libreoffice-common
sudo apt-get install -y libreoffice-core
sudo apt-get install -y libreoffice-draw
sudo apt-get install -y libreoffice-emailmerge
sudo apt-get install -y libreoffice-gnome
sudo apt-get install -y libreoffice-gtk
sudo apt-get install -y libreoffice-help-en-us
sudo apt-get install -y libreoffice-impress
sudo apt-get install -y libreoffice-math
sudo apt-get install -y libreoffice-style-human
sudo apt-get install -y libreoffice-style-tango
sudo apt-get install -y libreoffice-writer
sudo apt-get install -y librest-0.7-0
sudo apt-get install -y librhythmbox-core5
sudo apt-get install -y libroken18-heimdal
sudo apt-get install -y librsvg2-2
sudo apt-get install -y librsvg2-common
sudo apt-get install -y librsync1
sudo apt-get install -y librtmp0
sudo apt-get install -y libsamplerate0
sudo apt-get install -y libsane
sudo apt-get install -y libsane-common
sudo apt-get install -y libsane-hpaio
sudo apt-get install -y libsasl2-2
sudo apt-get install -y libsasl2-modules
sudo apt-get install -y libsdl1.2debian
sudo apt-get install -y libselinux1
sudo apt-get install -y libsensors4
sudo apt-get install -y libsgutils2-2
sudo apt-get install -y libshout3
sudo apt-get install -y libsigc++-2.0-0c2a
sudo apt-get install -y libslang2
sudo apt-get install -y libslp1
sudo apt-get install -y libsm6
sudo apt-get install -y libsmbclient
sudo apt-get install -y libsndfile1
sudo apt-get install -y libsnmp-base
sudo apt-get install -y libsnmp15
sudo apt-get install -y libsonic0
sudo apt-get install -y libsoup-gnome2.4-1
sudo apt-get install -y libsoup2.4-1
sudo apt-get install -y libspectre1
sudo apt-get install -y libspeechd2
sudo apt-get install -y libspeex1
sudo apt-get install -y libspeexdsp1
sudo apt-get install -y libsqlite3-0
sudo apt-get install -y libss2
sudo apt-get install -y libssh-4
sudo apt-get install -y libssl1.0.0
sudo apt-get install -y libstartup-notification0
sudo apt-get install -y libstdc++6
sudo apt-get install -y libswitch-perl
sudo apt-get install -y libsyncdaemon-1.0-1
sudo apt-get install -y libsysfs2
sudo apt-get install -y libt1-5
sudo apt-get install -y libtag1-vanilla
sudo apt-get install -y libtag1c2a
sudo apt-get install -y libtalloc2
sudo apt-get install -y libtasn1-3
sudo apt-get install -y libtdb1
sudo apt-get install -y libtelepathy-farstream2
sudo apt-get install -y libtelepathy-glib0
sudo apt-get install -y libtelepathy-logger2
sudo apt-get install -y libtext-charwidth-perl
sudo apt-get install -y libtext-iconv-perl
sudo apt-get install -y libtext-wrapi18n-perl
sudo apt-get install -y libthai-data
sudo apt-get install -y libthai0
sudo apt-get install -y libtheora0
sudo apt-get install -y libtiff4
sudo apt-get install -y libtimezonemap1
sudo apt-get install -y libtinfo5
sudo apt-get install -y libtotem-plparser17
sudo apt-get install -y libtotem0
sudo apt-get install -y libubuntuoneui-3.0-1
sudo apt-get install -y libudev0
sudo apt-get install -y libunique-3.0-0
sudo apt-get install -y libunity-2d-private0
sudo apt-get install -y libunity-core-5.0-5
sudo apt-get install -y libunity-misc4
sudo apt-get install -y libunity9
sudo apt-get install -y libupower-glib1
sudo apt-get install -y libusb-0.1-4
sudo apt-get install -y libusb-1.0-0
sudo apt-get install -y libusbmuxd1
sudo apt-get install -y libutempter0
sudo apt-get install -y libuuid-perl
sudo apt-get install -y libuuid1
sudo apt-get install -y libv4l-0
sudo apt-get install -y libv4lconvert0
sudo apt-get install -y libvisual-0.4-0
sudo apt-get install -y libvisual-0.4-plugins
sudo apt-get install -y libvncserver0
sudo apt-get install -y libvorbis0a
sudo apt-get install -y libvorbisenc2
sudo apt-get install -y libvorbisfile3
sudo apt-get install -y libvte-2.90-9
sudo apt-get install -y libvte-2.90-common
sudo apt-get install -y libwacom-common
sudo apt-get install -y libwacom2
sudo apt-get install -y libwavpack1
sudo apt-get install -y libwbclient0
sudo apt-get install -y libwebkitgtk-3.0-0
sudo apt-get install -y libwebkitgtk-3.0-common
sudo apt-get install -y libwind0-heimdal
sudo apt-get install -y libwmf0.2-7
sudo apt-get install -y libwmf0.2-7-gtk
sudo apt-get install -y libwnck-3-0
sudo apt-get install -y libwnck-3-common
sudo apt-get install -y libwnck-common
sudo apt-get install -y libwnck22
sudo apt-get install -y libwpd-0.9-9
sudo apt-get install -y libwpg-0.2-2
sudo apt-get install -y libwps-0.2-2
sudo apt-get install -y libwrap0
sudo apt-get install -y libx11-6
sudo apt-get install -y libx11-data
sudo apt-get install -y libx11-xcb1
sudo apt-get install -y libx86-1
sudo apt-get install -y libxapian22
sudo apt-get install -y libxatracker1-lts-precise
sudo apt-get install -y libxau6
sudo apt-get install -y libxaw7
sudo apt-get install -y libxcb-dri2-0
sudo apt-get install -y libxcb-glx0
sudo apt-get install -y libxcb-render0
sudo apt-get install -y libxcb-shape0
sudo apt-get install -y libxcb-shm0
sudo apt-get install -y libxcb-util0
sudo apt-get install -y libxcb1
sudo apt-get install -y libxcomposite1
sudo apt-get install -y libxcursor1
sudo apt-get install -y libxdamage1
sudo apt-get install -y libxdmcp6
sudo apt-get install -y libxext6
sudo apt-get install -y libxfixes3
sudo apt-get install -y libxfont1
sudo apt-get install -y libxft2
sudo apt-get install -y libxi6
sudo apt-get install -y libxinerama1
sudo apt-get install -y libxkbfile1
sudo apt-get install -y libxklavier16
sudo apt-get install -y libxml2
sudo apt-get install -y libxmu6
sudo apt-get install -y libxmuu1
sudo apt-get install -y libxp6
sudo apt-get install -y libxpm4
sudo apt-get install -y libxrandr-ltsq2
sudo apt-get install -y libxrandr2
sudo apt-get install -y libxrender1
sudo apt-get install -y libxres1
sudo apt-get install -y libxslt1.1
sudo apt-get install -y libxt6
sudo apt-get install -y libxtst6
sudo apt-get install -y libxv1
sudo apt-get install -y libxvmc1
sudo apt-get install -y libxxf86dga1
sudo apt-get install -y libxxf86vm1
sudo apt-get install -y libyajl1
sudo apt-get install -y libyaml-tiny-perl
sudo apt-get install -y libyelp0
sudo apt-get install -y libzeitgeist-1.0-1
sudo apt-get install -y libzephyr4
sudo apt-get install -y light-themes
sudo apt-get install -y lightdm
sudo apt-get install -y linux-firmware
sudo apt-get install -y linux-generic-lts-precise
sudo apt-get install -y linux-headers-3.5.0-23
sudo apt-get install -y linux-headers-3.5.0-23-generic
sudo apt-get install -y linux-headers-generic-lts-precise
sudo apt-get install -y linux-image-3.5.0-23-generic
sudo apt-get install -y linux-image-generic-lts-precise
sudo apt-get install -y linux-libc-dev
sudo apt-get install -y linux-sound-base
sudo apt-get install -y locales
sudo apt-get install -y lockfile-progs
sudo apt-get install -y login
sudo apt-get install -y logrotate
sudo apt-get install -y lsb-base
sudo apt-get install -y lsb-release
sudo apt-get install -y lshw
sudo apt-get install -y lsof
sudo apt-get install -y ltrace
sudo apt-get install -y mahjongg
sudo apt-get install -y make
sudo apt-get install -y makedev
sudo apt-get install -y man-db
sudo apt-get install -y manpages
sudo apt-get install -y manpages-dev
sudo apt-get install -y mawk
sudo apt-get install -y media-player-info
sudo apt-get install -y memtest86+
sudo apt-get install -y metacity
sudo apt-get install -y metacity-common
sudo apt-get install -y mime-support
sudo apt-get install -y mlocate
sudo apt-get install -y mobile-broadband-provider-info
sudo apt-get install -y modemmanager
sudo apt-get install -y module-init-tools
sudo apt-get install -y mount
sudo apt-get install -y mountall
sudo apt-get install -y mousetweaks
sudo apt-get install -y mscompress
sudo apt-get install -y mtools
sudo apt-get install -y mtr-tiny
sudo apt-get install -y multiarch-support
sudo apt-get install -y nano
sudo apt-get install -y nautilus
sudo apt-get install -y nautilus-data
sudo apt-get install -y nautilus-sendto
sudo apt-get install -y nautilus-sendto-empathy
sudo apt-get install -y nautilus-share
sudo apt-get install -y ncurses-base
sudo apt-get install -y ncurses-bin
sudo apt-get install -y net-tools
sudo apt-get install -y netbase
sudo apt-get install -y netcat-openbsd
sudo apt-get install -y network-manager
sudo apt-get install -y network-manager-gnome
sudo apt-get install -y network-manager-pptp
sudo apt-get install -y network-manager-pptp-gnome
sudo apt-get install -y notify-osd
sudo apt-get install -y notify-osd-icons
sudo apt-get install -y ntfs-3g
sudo apt-get install -y ntpdate
sudo apt-get install -y nux-tools
sudo apt-get install -y nvidia-common
sudo apt-get install -y obex-data-server
sudo apt-get install -y obexd-client
sudo apt-get install -y onboard
sudo apt-get install -y oneconf
sudo apt-get install -y openprinting-ppds
sudo apt-get install -y openssh-client
sudo apt-get install -y openssl
sudo apt-get install -y os-prober
sudo apt-get install -y overlay-scrollbar
sudo apt-get install -y parted
sudo apt-get install -y passwd
sudo apt-get install -y patch
sudo apt-get install -y pciutils
sudo apt-get install -y pcmciautils
sudo apt-get install -y perl
sudo apt-get install -y perl-base
sudo apt-get install -y perl-modules
sudo apt-get install -y pkg-config
sudo apt-get install -y plymouth
sudo apt-get install -y plymouth-label
sudo apt-get install -y plymouth-theme-ubuntu-logo
sudo apt-get install -y plymouth-theme-ubuntu-text
sudo apt-get install -y pm-utils
sudo apt-get install -y policykit-1
sudo apt-get install -y policykit-1-gnome
sudo apt-get install -y policykit-desktop-privileges
sudo apt-get install -y poppler-utils
sudo apt-get install -y popularity-contest
sudo apt-get install -y powermgmt-base
sudo apt-get install -y ppp
sudo apt-get install -y pppconfig
sudo apt-get install -y pppoeconf
sudo apt-get install -y pptp-linux
sudo apt-get install -y printer-driver-c2esp
sudo apt-get install -y printer-driver-foo2zjs
sudo apt-get install -y printer-driver-gutenprint
sudo apt-get install -y printer-driver-hpcups
sudo apt-get install -y printer-driver-hpijs
sudo apt-get install -y printer-driver-min12xxw
sudo apt-get install -y printer-driver-pnm2ppa
sudo apt-get install -y printer-driver-postscript-hp
sudo apt-get install -y printer-driver-ptouch
sudo apt-get install -y printer-driver-pxljr
sudo apt-get install -y printer-driver-sag-gdi
sudo apt-get install -y printer-driver-splix
sudo apt-get install -y procps
sudo apt-get install -y protobuf-compiler
sudo apt-get install -y psmisc
sudo apt-get install -y pulseaudio
sudo apt-get install -y pulseaudio-module-bluetooth
sudo apt-get install -y pulseaudio-module-gconf
sudo apt-get install -y pulseaudio-module-x11
sudo apt-get install -y pulseaudio-utils
sudo apt-get install -y python
sudo apt-get install -y python-appindicator
sudo apt-get install -y python-apport
sudo apt-get install -y python-apt
sudo apt-get install -y python-apt-common
sudo apt-get install -y python-aptdaemon
sudo apt-get install -y python-aptdaemon.gtk3widgets
sudo apt-get install -y python-aptdaemon.pkcompat
sudo apt-get install -y python-brlapi
sudo apt-get install -y python-cairo
sudo apt-get install -y python-chardet
sudo apt-get install -y python-configglue
sudo apt-get install -y python-crypto
sudo apt-get install -y python-cups
sudo apt-get install -y python-cupshelpers
sudo apt-get install -y python-dateutil
sudo apt-get install -y python-dbus
sudo apt-get install -y python-dbus-dev
sudo apt-get install -y python-debian
sudo apt-get install -y python-debtagshw
sudo apt-get install -y python-defer
sudo apt-get install -y python-dirspec
sudo apt-get install -y python-egenix-mxdatetime
sudo apt-get install -y python-egenix-mxtools
sudo apt-get install -y python-gconf
sudo apt-get install -y python-gdbm
sudo apt-get install -y python-gi
sudo apt-get install -y python-gi-cairo
sudo apt-get install -y python-gnomekeyring
sudo apt-get install -y python-gnupginterface
sudo apt-get install -y python-gobject
sudo apt-get install -y python-gobject-2
sudo apt-get install -y python-gst0.10
sudo apt-get install -y python-gtk2
sudo apt-get install -y python-httplib2
sudo apt-get install -y python-ibus
sudo apt-get install -y python-imaging
sudo apt-get install -y python-keyring
sudo apt-get install -y python-launchpadlib
sudo apt-get install -y python-lazr.restfulclient
sudo apt-get install -y python-lazr.uri
sudo apt-get install -y python-libproxy
sudo apt-get install -y python-libxml2
sudo apt-get install -y python-louis
sudo apt-get install -y python-mako
sudo apt-get install -y python-markupsafe
sudo apt-get install -y python-minimal
sudo apt-get install -y python-notify
sudo apt-get install -y python-oauth
sudo apt-get install -y python-openssl
sudo apt-get install -y python-packagekit
sudo apt-get install -y python-pam
sudo apt-get install -y python-pexpect
sudo apt-get install -y python-piston-mini-client
sudo apt-get install -y python-pkg-resources
sudo apt-get install -y python-problem-report
sudo apt-get install -y python-protobuf
sudo apt-get install -y python-pyatspi2
sudo apt-get install -y python-pycurl
sudo apt-get install -y python-pyinotify
sudo apt-get install -y python-renderpm
sudo apt-get install -y python-reportlab
sudo apt-get install -y python-reportlab-accel
sudo apt-get install -y python-serial
sudo apt-get install -y python-simplejson
sudo apt-get install -y python-smbc
sudo apt-get install -y python-software-properties
sudo apt-get install -y python-speechd
sudo apt-get install -y python-twisted-bin
sudo apt-get install -y python-twisted-core
sudo apt-get install -y python-twisted-names
sudo apt-get install -y python-twisted-web
sudo apt-get install -y python-ubuntu-sso-client
sudo apt-get install -y python-ubuntuone-client
sudo apt-get install -y python-ubuntuone-control-panel
sudo apt-get install -y python-ubuntuone-storageprotocol
sudo apt-get install -y python-uno
sudo apt-get install -y python-virtkey
sudo apt-get install -y python-wadllib
sudo apt-get install -y python-xapian
sudo apt-get install -y python-xdg
sudo apt-get install -y python-xkit
sudo apt-get install -y python-zeitgeist
sudo apt-get install -y python-zope.interface
sudo apt-get install -y python2.7
sudo apt-get install -y python2.7-minimal
sudo apt-get install -y qdbus
sudo apt-get install -y qt-at-spi
sudo apt-get install -y radeontool
sudo apt-get install -y readline-common
sudo apt-get install -y remmina
sudo apt-get install -y remmina-common
sudo apt-get install -y remmina-plugin-rdp
sudo apt-get install -y remmina-plugin-vnc
sudo apt-get install -y resolvconf
sudo apt-get install -y rfkill
sudo apt-get install -y rhythmbox
sudo apt-get install -y rhythmbox-data
sudo apt-get install -y rhythmbox-mozilla
sudo apt-get install -y rhythmbox-plugin-cdrecorder
sudo apt-get install -y rhythmbox-plugin-magnatune
sudo apt-get install -y rhythmbox-plugin-zeitgeist
sudo apt-get install -y rhythmbox-plugins
sudo apt-get install -y rhythmbox-ubuntuone
sudo apt-get install -y rsync
sudo apt-get install -y rsyslog
sudo apt-get install -y rtkit
sudo apt-get install -y samba-common
sudo apt-get install -y samba-common-bin
sudo apt-get install -y sane-utils
sudo apt-get install -y seahorse
sudo apt-get install -y sed
sudo apt-get install -y sensible-utils
sudo apt-get install -y sessioninstaller
sudo apt-get install -y sgml-base
sudo apt-get install -y shared-mime-info
sudo apt-get install -y shotwell
sudo apt-get install -y simple-scan
sudo apt-get install -y smbclient
sudo apt-get install -y sni-qt
sudo apt-get install -y software-center
sudo apt-get install -y software-center-aptdaemon-plugins
sudo apt-get install -y software-properties-common
sudo apt-get install -y software-properties-gtk
sudo apt-get install -y sound-theme-freedesktop
sudo apt-get install -y speech-dispatcher
sudo apt-get install -y ssh-askpass-gnome
sudo apt-get install -y ssl-cert
sudo apt-get install -y strace
sudo apt-get install -y sudo
sudo apt-get install -y syslinux
sudo apt-get install -y syslinux-common
sudo apt-get install -y syslinux-legacy
sudo apt-get install -y system-config-printer-common
sudo apt-get install -y system-config-printer-gnome
sudo apt-get install -y system-config-printer-udev
sudo apt-get install -y sysv-rc
sudo apt-get install -y sysvinit-utils
sudo apt-get install -y tar
sudo apt-get install -y tcpd
sudo apt-get install -y tcpdump
sudo apt-get install -y telepathy-gabble
sudo apt-get install -y telepathy-haze
sudo apt-get install -y telepathy-idle
sudo apt-get install -y telepathy-indicator
sudo apt-get install -y telepathy-logger
sudo apt-get install -y telepathy-mission-control-5
sudo apt-get install -y telepathy-salut
sudo apt-get install -y telnet
sudo apt-get install -y thunderbird
sudo apt-get install -y thunderbird-globalmenu
sudo apt-get install -y thunderbird-gnome-support
sudo apt-get install -y time
sudo apt-get install -y toshset
sudo apt-get install -y totem
sudo apt-get install -y totem-common
sudo apt-get install -y totem-mozilla
sudo apt-get install -y totem-plugins
sudo apt-get install -y transmission-common
sudo apt-get install -y transmission-gtk
sudo apt-get install -y ttf-dejavu-core
sudo apt-get install -y ttf-freefont
sudo apt-get install -y ttf-indic-fonts-core
sudo apt-get install -y ttf-punjabi-fonts
sudo apt-get install -y ttf-ubuntu-font-family
sudo apt-get install -y ttf-wqy-microhei
sudo apt-get install -y tzdata
sudo apt-get install -y ubuntu-artwork
sudo apt-get install -y ubuntu-desktop
sudo apt-get install -y ubuntu-docs
sudo apt-get install -y ubuntu-extras-keyring
sudo apt-get install -y ubuntu-keyring
sudo apt-get install -y ubuntu-minimal
sudo apt-get install -y ubuntu-mono
sudo apt-get install -y ubuntu-sounds
sudo apt-get install -y ubuntu-sso-client
sudo apt-get install -y ubuntu-sso-client-gtk
sudo apt-get install -y ubuntu-standard
sudo apt-get install -y ubuntu-system-service
sudo apt-get install -y ubuntu-wallpapers
sudo apt-get install -y ubuntu-wallpapers-precise
sudo apt-get install -y ubuntuone-client
sudo apt-get install -y ubuntuone-client-gnome
sudo apt-get install -y ubuntuone-control-panel
sudo apt-get install -y ubuntuone-couch
sudo apt-get install -y ubuntuone-installer
sudo apt-get install -y ucf
sudo apt-get install -y udev
sudo apt-get install -y udisks
sudo apt-get install -y ufw
sudo apt-get install -y unattended-upgrades
sudo apt-get install -y unity
sudo apt-get install -y unity-2d
sudo apt-get install -y unity-2d-common
sudo apt-get install -y unity-2d-panel
sudo apt-get install -y unity-2d-shell
sudo apt-get install -y unity-2d-spread
sudo apt-get install -y unity-asset-pool
sudo apt-get install -y unity-common
sudo apt-get install -y unity-greeter
sudo apt-get install -y unity-lens-applications
sudo apt-get install -y unity-lens-files
sudo apt-get install -y unity-lens-music
sudo apt-get install -y unity-lens-video
sudo apt-get install -y unity-scope-musicstores
sudo apt-get install -y unity-scope-video-remote
sudo apt-get install -y unity-services
sudo apt-get install -y uno-libs3
sudo apt-get install -y unzip
sudo apt-get install -y update-inetd
sudo apt-get install -y update-manager
sudo apt-get install -y update-manager-core
sudo apt-get install -y update-notifier
sudo apt-get install -y update-notifier-common
sudo apt-get install -y upower
sudo apt-get install -y upstart
sudo apt-get install -y ure
sudo apt-get install -y ureadahead
sudo apt-get install -y usb-creator-common
sudo apt-get install -y usb-creator-gtk
sudo apt-get install -y usb-modeswitch
sudo apt-get install -y usb-modeswitch-data
sudo apt-get install -y usbmuxd
sudo apt-get install -y usbutils
sudo apt-get install -y util-linux
sudo apt-get install -y uuid-runtime
sudo apt-get install -y vbetool
sudo apt-get install -y vim-common
sudo apt-get install -y vim-tiny
sudo apt-get install -y vino
sudo apt-get install -y wamerican
sudo apt-get install -y wget
sudo apt-get install -y whiptail
sudo apt-get install -y whois
sudo apt-get install -y whoopsie
sudo apt-get install -y wireless-regdb
sudo apt-get install -y wireless-tools
sudo apt-get install -y wodim
sudo apt-get install -y wpasupplicant
sudo apt-get install -y x11-apps
sudo apt-get install -y x11-common
sudo apt-get install -y x11-session-utils
sudo apt-get install -y x11-utils
sudo apt-get install -y x11-xfs-utils
sudo apt-get install -y x11-xkb-utils
sudo apt-get install -y x11-xserver-utils
sudo apt-get install -y x11-xserver-utils-lts-precise
sudo apt-get install -y xauth
sudo apt-get install -y xbitmaps
sudo apt-get install -y xcursor-themes
sudo apt-get install -y xdg-user-dirs
sudo apt-get install -y xdg-user-dirs-gtk
sudo apt-get install -y xdg-utils
sudo apt-get install -y xdiagnose
sudo apt-get install -y xfonts-base
sudo apt-get install -y xfonts-encodings
sudo apt-get install -y xfonts-mathml
sudo apt-get install -y xfonts-scalable
sudo apt-get install -y xfonts-utils
sudo apt-get install -y xinit
sudo apt-get install -y xinput
sudo apt-get install -y xkb-data
sudo apt-get install -y xml-core
sudo apt-get install -y xorg
sudo apt-get install -y xorg-docs-core
sudo apt-get install -y xserver-common
sudo apt-get install -y xserver-common-lts-precise
sudo apt-get install -y xserver-xorg-core-lts-precise
sudo apt-get install -y xserver-xorg-input-all-lts-precise
sudo apt-get install -y xserver-xorg-input-evdev-lts-precise
sudo apt-get install -y xserver-xorg-input-mouse-lts-precise
sudo apt-get install -y xserver-xorg-input-synaptics-lts-precise
sudo apt-get install -y xserver-xorg-input-vmmouse-lts-precise
sudo apt-get install -y xserver-xorg-input-wacom-lts-precise
sudo apt-get install -y xserver-xorg-lts-precise
sudo apt-get install -y xserver-xorg-video-all-lts-precise
sudo apt-get install -y xserver-xorg-video-ati-lts-precise
sudo apt-get install -y xserver-xorg-video-cirrus-lts-precise
sudo apt-get install -y xserver-xorg-video-fbdev-lts-precise
sudo apt-get install -y xserver-xorg-video-intel-lts-precise
sudo apt-get install -y xserver-xorg-video-mach64-lts-precise
sudo apt-get install -y xserver-xorg-video-mga-lts-precise
sudo apt-get install -y xserver-xorg-video-modesetting-lts-precise
sudo apt-get install -y xserver-xorg-video-neomagic-lts-precise
sudo apt-get install -y xserver-xorg-video-nouveau-lts-precise
sudo apt-get install -y xserver-xorg-video-openchrome-lts-precise
sudo apt-get install -y xserver-xorg-video-r128-lts-precise
sudo apt-get install -y xserver-xorg-video-radeon-lts-precise
sudo apt-get install -y xserver-xorg-video-s3-lts-precise
sudo apt-get install -y xserver-xorg-video-savage-lts-precise
sudo apt-get install -y xserver-xorg-video-siliconmotion-lts-precise
sudo apt-get install -y xserver-xorg-video-sis-lts-precise
sudo apt-get install -y xserver-xorg-video-sisusb-lts-precise
sudo apt-get install -y xserver-xorg-video-tdfx-lts-precise
sudo apt-get install -y xserver-xorg-video-trident-lts-precise
sudo apt-get install -y xserver-xorg-video-vesa-lts-precise
sudo apt-get install -y xserver-xorg-video-vmware-lts-precise
sudo apt-get install -y xterm
sudo apt-get install -y xul-ext-ubufox
sudo apt-get install -y xz-lzma
sudo apt-get install -y xz-utils
sudo apt-get install -y yelp
sudo apt-get install -y yelp-xsl
sudo apt-get install -y zeitgeist
sudo apt-get install -y zeitgeist-core
sudo apt-get install -y zeitgeist-datahub
sudo apt-get install -y zenity
sudo apt-get install -y zenity-common
sudo apt-get install -y zip
sudo apt-get install -y zlib1g
